####################################################################################################
# Pipelex Model Deck - Custom Configurations for LLMs
####################################################################################################
#
# This file allows you to override or complete the base model decks.
#
# Documentation: https://docs.pipelex.com
# Support: https://go.pipelex.com/discord
#
####################################################################################################

####################################################################################################
# LLM Deck overrides
####################################################################################################

[llm.choice_overrides]
for_text = "disabled"
for_object = "disabled"


####################################################################################################
# Waterfalls — lists of models that will be tried in order until one of them is available
####################################################################################################

[llm.waterfalls]

# --- Waterfalls for premium LLMs -------------------------------------------------------------------
premium-llm = ["claude-4.5-opus", "gemini-3.0-pro", "gpt-5.2", "grok-4"]
premium-llm-vision = [
    "claude-4.5-opus",
    "gemini-3.0-pro",
    "gpt-5.2",
    "grok-4-fast-reasoning",
]
premium-llm-structured = [
    "claude-4.5-opus",
    "gemini-3.0-pro",
    "gpt-5.2",
    "grok-4",
]

# --- Waterfalls for large context LLMs -------------------------------------------------------------
large-context-llm-code = [
    "gemini-3.0-pro",
    "claude-4.5-opus",
    "gpt-5.2",
    "grok-4-fast-reasoning",
]
large-context-llm-text = ["gemini-2.5-flash", "claude-4.5-sonnet"]

# --- Waterfalls for lite LLMs ----------------------------------------------------------------------
small-llm = [
    "gemini-2.5-flash-lite",
    "gpt-4o-mini",
    "claude-3-haiku",
    "phi-4",
    "grok-3-mini",
]
small-llm-structured = [
    "gemini-2.5-flash-lite",
    "gpt-4o-mini",
    "claude-3-haiku",
]
small-llm-vision = ["gemini-2.5-flash-lite", "gpt-4o-mini", "claude-3-haiku"]
small-llm-creative = ["gemini-2.5-flash-lite", "gpt-4o-mini", "claude-3-haiku"]
