[pipelex-inference]
endpoint = "https://inference.pipelex.com/v1"
api_key = "${PIPELEX_INFERENCE_API_KEY}"

[blackboxai]
enabled = false
endpoint = "https://api.blackbox.ai/v1"
api_key = "${BLACKBOX_API_KEY}"

[azure_openai]
enabled = false
endpoint = "${AZURE_API_BASE}"
api_key = "${AZURE_API_KEY}"

[anthropic]
enabled = false
api_key = "${ANTHROPIC_API_KEY}"

[ollama]
enabled = false
endpoint = "http://localhost:11434/v1"

