"""Rendering helpers shared by the two Python types emitters (structures + plain pydantic).

Only the target-agnostic pieces live here: string / default-value escaping, the generated-file
header (carrying the extension-file subclassing story), the class docstring, the `= Field(...)`
assignment, the `Literal[...]` annotation, and the import block. Each Python emitter keeps its own
resolved-type -> annotation walker, because the concept spelling (runtime content classes vs.
generated models) differs.
"""

import sys
from collections import defaultdict
from datetime import date, datetime, time
from typing import Any, cast

from pipelex.codegen.resolved_concepts import ResolvedConcept
from pipelex.core.concepts.resolved_fields import ResolvedField, iter_imprecision_reasons


def python_header(*, target: str) -> str:
    """The generated-file header: an AUTOGENERATED marker plus the extension-file (subclassing) story."""
    return (
        "# ---------------------------------------------------------------------------\n"
        "# AUTOGENERATED by Pipelex codegen — DO NOT EDIT.\n"
        "#\n"
        "# This file is a projection of a normalized MTHDS library crate. It is\n"
        "# regenerated from the method; any hand edit here is overwritten.\n"
        "#\n"
        "# To customize a generated type, do NOT edit this file. Create a sibling\n"
        "# module and subclass — subclasses survive regeneration:\n"
        "#\n"
        "#     # my_types_ext.py\n"
        "#     from .structures import Report\n"
        "#\n"
        "#     class MyReport(Report):\n"
        "#         ...\n"
        "#\n"
        f"# projection: types / {target}\n"
        "# ---------------------------------------------------------------------------\n"
    )


def escape_py_string(value: str) -> str:
    """Escape a string for a double-quoted Python literal (handles quotes, backslashes, newlines)."""
    # repr() escapes everything correctly and returns a quoted literal; prefer double quotes when repr
    # chose single quotes (for consistency with the rest of the generated code).
    escaped = repr(value)
    if escaped.startswith("'") and escaped.endswith("'") and not escaped.startswith("'''"):
        inner = escaped[1:-1].replace("\\'", "'").replace('"', '\\"')
        return f'"{inner}"'
    return escaped


def format_default_value(value: Any) -> str:
    """Format a default value as Python source. Temporal values rebuild via `fromisoformat` so they
    use the bare `date` / `datetime` names the generated module imports (repr module-qualifies them).
    """
    if isinstance(value, str):
        return escape_py_string(value)
    if isinstance(value, datetime):
        return f'datetime.fromisoformat("{value.isoformat()}")'
    if isinstance(value, date):
        return f'date.fromisoformat("{value.isoformat()}")'
    if isinstance(value, time):
        return f'time.fromisoformat("{value.isoformat()}")'
    if isinstance(value, list):
        items = cast("list[Any]", value)
        return f"[{', '.join(format_default_value(item) for item in items)}]"
    if isinstance(value, dict):
        pairs = cast("dict[str, Any]", value)
        rendered = [f"{format_default_value(key)}: {format_default_value(pairs[key])}" for key in sorted(pairs)]
        return f"{{{', '.join(rendered)}}}"
    return repr(value)


def _breaks_out_of_docstring(text: str) -> bool:
    """Whether `text` cannot sit verbatim between triple quotes.

    Two families. The delimiter hazards — an embedded triple quote, or a trailing quote or backslash that
    would glue onto the closing delimiter. And any character that would not survive verbatim in a source
    file: a carriage return (line-ending normalization would rewrite it) or another control character. A
    real newline and a tab both round-trip exactly, so neither is a hazard.

    Never normalize such text — the emitted docstring is asserted to equal the authored description
    byte for byte, so a hazard routes to the fully-escaped branch, which reproduces it exactly.
    """
    if '"""' in text or text.endswith(('"', "\\")):
        return True
    return any(char not in {"\n", "\t"} and not char.isprintable() for char in text)


def class_docstring(description: str, *, extra_line: str | None = None, indent: str = "    ") -> str:
    """Render a triple-quoted class docstring; append `extra_line` (e.g. an imprecision caveat) as a second paragraph.

    Escaping is deliberately minimal. Between triple quotes a lone `"` needs no escape and a real newline is
    fine, so pushing the text through `escape_py_string` (the *single-line literal* escaper) would put
    backslashes in the docstring for an input as ordinary as `The "primary" thing`. Ruff's `D301` then
    rewrites the docstring to an `r` prefix — which changes the bytes, invalidating the codegen stamp, and
    corrupts the text, because the escapes start rendering literally. Hence three modes:

    - **plain** — nothing hazardous: emitted verbatim, quotes and newlines untouched;
    - **raw** — contains a backslash: emitted with an `r` prefix, which is both faithful and what D301 asks for;
    - **escaped** — the hazards named in `_breaks_out_of_docstring`: fully escaped. No description written in
      practice reaches this branch, and the fallback keeps the emitted file valid, which is what matters.
    """
    parts = [part for part in (description or "", extra_line or "") if part]
    if not parts:
        return f'{indent}""""""'

    if any(_breaks_out_of_docstring(part) for part in parts):
        escaped_break = "\\n\\n"
        escaped = escaped_break.join(escape_py_string(part)[1:-1] for part in parts)
        return f'{indent}"""{escaped}"""'

    prefix = "r" if any("\\" in part for part in parts) else ""
    if len(parts) == 1:
        return f'{indent}{prefix}"""{parts[0]}"""'
    body, caveat = parts
    return f'{indent}{prefix}"""{body}\n\n{indent}{caveat}\n{indent}"""'


def field_line(field: ResolvedField, *, annotation: str) -> str:
    """Render one `name: <annotation> = Field(...)` line, surfacing any type-tree imprecision inline.

    `annotation` must already carry optionality in the emitter's own idiom (`Optional[...]` or `... | None`).
    """
    params: list[str]
    if field.required and field.default_value is None:
        params = ["..."]
    elif field.default_value is not None:
        params = [f"default={format_default_value(field.default_value)}"]
    else:
        params = ["default=None"]
    params.append(f"description={escape_py_string(field.description)}")

    line = f"    {field.name}: {annotation} = Field({', '.join(params)})"
    reasons = list(dict.fromkeys(iter_imprecision_reasons(field.resolved_type)))
    if reasons:
        line += f"  # imprecise: {'; '.join(reasons)}"
    return line


def any_annotation(*, imports: set[str]) -> str:
    """The `Any` annotation, registering its import — the honest spelling for an imprecise type."""
    imports.add("from typing import Any")
    return "Any"


def literal_annotation(*, choices: list[str] | None, imports: set[str]) -> str:
    """The `Literal[...]` annotation, with double-quoted members (`repr()` would pick single quotes)."""
    imports.add("from typing import Literal")
    members = ", ".join(escape_py_string(choice) for choice in choices or [])
    return f"Literal[{members}]"


def render_import_block(imports: set[str]) -> str:
    """Render the collected imports the way isort would, so the artifact is lint-clean on arrival.

    A flat `sorted()` over the raw statements is not isort order. Two things it misses: `from X import a`
    and `from X import b` have to merge into one line, and stdlib has to be separated from third-party by
    a blank line.

    Grouping targets the **consumer's** tree, where `pipelex` is an installed dependency and therefore
    third-party. In this repo `pipelex` is first-party, so ruff here wants the opposite order — but no
    generated artifact is ever committed to this repo, and the consumer is the only one who lints these
    files. `tests/unit/pipelex/codegen/test_emitted_artifacts_are_lint_clean.py` lints them as a consumer
    would, for that reason.
    """
    names_by_module: dict[str, set[str]] = defaultdict(set)
    for statement in imports:
        module, _, names = statement.removeprefix("from ").partition(" import ")
        names_by_module[module].update(name.strip() for name in names.split(","))

    stdlib: list[str] = []
    third_party: list[str] = []
    for module in sorted(names_by_module):
        line = f"from {module} import {', '.join(sorted(names_by_module[module]))}"
        group = stdlib if module.partition(".")[0] in sys.stdlib_module_names else third_party
        group.append(line)

    return "\n\n".join("\n".join(group) for group in (stdlib, third_party) if group)


def python_module_body(*, header: str, imports: set[str], blocks: list[str]) -> str:
    """Assemble a generated module; a projection with nothing to emit is its header alone.

    The empty artifact needs an explicit canonical form, because the populated one degenerates into
    something no formatter leaves alone: the import block has no class left to use it (`F401`, which
    `ruff check --fix` deletes) and the block separator becomes a trailing blank-line run (which
    `ruff format` collapses). Either rewrite changes the body bytes the stamp hashes, so `codegen
    check` reports the file as hand-edited. A header is inert under both.

    This is reachable without a degenerate crate: `python-structures` skips natives, so an ordinary
    method that declares no concepts of its own leaves that emitter with nothing to write.
    """
    if not blocks:
        return header
    return f"{header}from __future__ import annotations\n\n{render_import_block(imports)}\n\n\n" + "\n\n\n".join(blocks) + "\n"


def order_by_base(concepts: list[ResolvedConcept], *, in_module: set[str]) -> list[ResolvedConcept]:
    """Order concepts so an in-module refinement base is defined before its subclass (inheritance is eager)."""
    by_ref = {concept.concept_ref: concept for concept in concepts}
    ordered: list[ResolvedConcept] = []
    seen: set[str] = set()

    def visit(concept: ResolvedConcept) -> None:
        if concept.concept_ref in seen:
            return
        seen.add(concept.concept_ref)
        base_ref = concept.base_ref
        if base_ref is not None and base_ref in in_module and base_ref in by_ref:
            visit(by_ref[base_ref])
        ordered.append(concept)

    for concept in concepts:
        visit(concept)
    return ordered
