"""Rendering helpers shared by the two Python types emitters (structures + plain pydantic).

Only the target-agnostic pieces live here: string / default-value escaping, the generated-file
header (carrying the extension-file subclassing story), the class docstring, the `= Field(...)`
assignment, the `Literal[...]` annotation, and the import block. Each Python emitter keeps its own
resolved-type -> annotation walker, because the concept spelling (runtime content classes vs.
generated models) differs.
"""

import sys
from collections import defaultdict
from datetime import date, datetime, time
from inspect import cleandoc
from typing import Any, cast

from pipelex.codegen.resolved_concepts import ResolvedConcept
from pipelex.core.concepts.resolved_fields import ResolvedField, iter_imprecision_reasons

# Ruff's own default `line-length`, and deliberately not this repo's 150. It is the *tightest* width a
# consumer is likely to lint at, and the threshold has to be the tightest one to be safe: anything we
# leave flat must fit under every config we claim to support. Past it we emit an already-exploded form
# with a magic trailing comma, which the formatter pins at any width — so the only shapes still at the
# mercy of a consumer's setting are flat lines under 88 columns, which a narrower config would rewrap.
PY_EXPLODE_WIDTH = 88

# One level of the generated class body. Emitted code is always 4-space indented.
_PY_INDENT = "    "


def python_header(*, target: str) -> str:
    """The generated-file header: an AUTOGENERATED marker plus the extension-file (subclassing) story."""
    return (
        "# ---------------------------------------------------------------------------\n"
        "# AUTOGENERATED by Pipelex codegen — DO NOT EDIT.\n"
        "#\n"
        "# This file is a projection of a normalized MTHDS library crate. It is\n"
        "# regenerated from the method; any hand edit here is overwritten.\n"
        "#\n"
        "# To customize a generated type, do NOT edit this file. Create a sibling\n"
        "# module and subclass — subclasses survive regeneration:\n"
        "#\n"
        "#     # my_types_ext.py\n"
        "#     from .structures import Report\n"
        "#\n"
        "#     class MyReport(Report):\n"
        "#         ...\n"
        "#\n"
        f"# projection: types / {target}\n"
        "# ---------------------------------------------------------------------------\n"
    )


def escape_py_string(value: str) -> str:
    """Escape a string as the Python literal `ruff format` would leave alone.

    Double quotes by default, and single quotes only where that **strictly reduces** the escape count —
    which is ruff's (and black's) own normalization rule, verified across the mixed and tied cases. Always
    double-quoting was the tempting simplification and it broke the stamp: a description or choice
    carrying a `"` came out double-quoted with both quotes escaped, which ruff rewrites to the
    escape-free `'say "hi"'` on a consumer's very first format run — at any line width, reporting an
    untouched artifact as hand-edited.

    `repr` does the escaping of everything else — backslashes, newlines, control characters — and picks its
    own quote by a different rule, so its choice is converted when it disagrees.
    """
    quote = "'" if value.count("'") < value.count('"') else '"'
    escaped = repr(value)
    if escaped[0] == quote:
        return escaped
    # Only repr-single -> double is reachable: repr picks `"` solely for a value carrying `'` and no `"`,
    # which is exactly the shape this rule also wants double-quoted.
    other = escaped[0]
    inner = escaped[1:-1].replace(f"\\{other}", other).replace(quote, f"\\{quote}")
    return f"{quote}{inner}{quote}"


def format_default_value(value: Any) -> str:
    """Format a default value as Python source. Temporal values rebuild via `fromisoformat` so they
    use the bare `date` / `datetime` names the generated module imports (repr module-qualifies them).
    """
    if isinstance(value, str):
        return escape_py_string(value)
    if isinstance(value, datetime):
        return f'datetime.fromisoformat("{value.isoformat()}")'
    if isinstance(value, date):
        return f'date.fromisoformat("{value.isoformat()}")'
    if isinstance(value, time):
        return f'time.fromisoformat("{value.isoformat()}")'
    if isinstance(value, list):
        items = cast("list[Any]", value)
        return f"[{', '.join(format_default_value(item) for item in items)}]"
    if isinstance(value, dict):
        pairs = cast("dict[str, Any]", value)
        rendered = [f"{format_default_value(key)}: {format_default_value(pairs[key])}" for key in sorted(pairs)]
        return f"{{{', '.join(rendered)}}}"
    return repr(value)


def normalized_docstring_text(text: str) -> str:
    """The authored text as it reads back out of `inspect.getdoc` once rendered as a docstring.

    Two normalizations compose, neither of them chosen. Per-line trailing whitespace goes because
    `ruff format` strips it inside docstrings (and `D210` trims the edges), both as auto-applied fixes
    that would otherwise rewrite the stamped bytes. Then `cleandoc` — the same call `inspect.getdoc`
    makes — expands tabs, drops the common indentation, and trims blank edges. Composing them here is
    what makes the contract exact rather than approximate: the emitter indents continuation lines to the
    class body, and `cleandoc` takes that indentation straight back off.

    This is the emitter's half of the fidelity contract, and the exact expression tests assert against:
    `inspect.getdoc(cls) == normalized_docstring_text(description)`.
    """
    return cleandoc("\n".join(line.rstrip() for line in text.splitlines()))


def _docstring_delimiter(text: str) -> str | None:
    """The triple-quote delimiter `text` can sit inside verbatim, or `None` when it must be escaped.

    Falling back to `'''` for a description containing `\"\"\"` is what keeps the docstring **backslash-free**,
    and that is the whole point: any backslash trips ruff's `D301` ("use `r\"\"\"`"), and the `r` prefix it asks
    for would then render the escapes literally, corrupting the text. `ruff format` rewrites `'''` to `\"\"\"`
    only when that needs no escaping, so a `'''` chosen here is left alone.

    `None` means no verbatim rendering exists — the text carries both triple-quote styles, a control
    character, or a trailing backslash that would glue onto the closing delimiter.
    """
    if text.endswith("\\") or any(char not in {"\n", "\t"} and not char.isprintable() for char in text):
        return None
    return next((delimiter for delimiter in ('"""', "'''") if delimiter not in text and not text.endswith(delimiter[0])), None)


def class_docstring(description: str, *, extra_line: str | None = None, indent: str = "    ") -> str:
    """Render a class docstring; append `extra_line` (e.g. an imprecision caveat) as a second paragraph.

    Shaped the way a human writes one — summary on the first line, continuation lines indented to the class
    body, closing delimiter on its own line — because that is the only shape the pydocstyle rules and
    `ruff format` both leave untouched. Every rewrite they would otherwise apply (`D207` under-indented,
    `D209` closing quotes, `D210` edge whitespace) is an auto-applied fix, and each one changes the body
    bytes the codegen stamp hashes, which is precisely the drift this module exists to prevent.

    So `__doc__` is deliberately *not* byte-identical to the authored description: it carries the
    indentation every hand-written docstring carries. The invariant that does hold is the one consumers
    read through — `inspect.getdoc(cls) == normalized_docstring_text(description)`. Exact bytes survive
    where they are consumed programmatically: `Field(description=...)`, and the crate itself.
    """
    parts = [normalized_docstring_text(part) for part in (description or "", extra_line or "") if part.strip()]
    if not parts:
        return f'{indent}""""""'

    body = "\n\n".join(parts)
    delimiter = _docstring_delimiter(body)
    if delimiter is None:
        # No verbatim rendering exists, so escape. This trips `D301`, but ruff classes that fix as *unsafe*,
        # so a consumer's `ruff check --fix` still leaves the bytes — and the stamp — alone.
        # Each rendered break carries the body indent, exactly as the verbatim branches do, so `cleandoc`
        # takes the same margin back off either way and the fidelity contract holds across both.
        escaped = f"\\n\\n{indent}".join(f"\\n{indent}".join(escape_py_string(line)[1:-1] for line in part.split("\n")) for part in parts)
        return f'{indent}"""{escaped}"""'

    prefix = "r" if "\\" in body else ""
    lines = body.split("\n")
    if len(lines) == 1:
        return f"{indent}{prefix}{delimiter}{lines[0]}{delimiter}"
    continuation = "\n".join(f"{indent}{line}" if line else "" for line in lines[1:])
    return f"{indent}{prefix}{delimiter}{lines[0]}\n{continuation}\n{indent}{delimiter}"


def field_line(field: ResolvedField, *, annotation: str, imports: set[str]) -> str:
    """Render one `name: <annotation> = Field(...)` line, surfacing any type-tree imprecision inline.

    `annotation` must already carry optionality in the emitter's own idiom (`Optional[...]` or `... | None`).

    Registers its own `Field` import, like every other renderer here: an import nobody uses is an `F401`
    that `ruff check --fix` deletes, which rewrites the body bytes and breaks the stamp. Demand-driven
    is the only way that stays true for every crate shape — a crate of only opaque concepts, or only
    concepts refining a native, emits no field line at all.
    """
    imports.add("from pydantic import Field")
    params: list[str]
    if field.required and field.default_value is None:
        params = ["..."]
    elif field.default_value is not None:
        params = [f"default={format_default_value(field.default_value)}"]
    else:
        params = ["default=None"]
    params.append(f"description={escape_py_string(field.description)}")

    reasons = list(dict.fromkeys(iter_imprecision_reasons(field.resolved_type)))
    comment = f"  # imprecise: {'; '.join(reasons)}" if reasons else ""

    flat = f"    {field.name}: {annotation} = Field({', '.join(params)})"
    # The trailing comment counts toward the width: ruff splits the call to fit `)  # imprecise: …` too.
    if len(flat) + len(comment) <= PY_EXPLODE_WIDTH:
        return flat + comment

    # Too long to be left alone: hand the formatter an already-exploded call with a magic trailing comma,
    # which pins the shape at *any* line-length (verified 60..200). A long authored description or choice
    # list has no width-independent flat form, so this is the only rendering a consumer's `ruff format`
    # cannot rewrite. The annotation gets the same treatment when the head line alone is still too long.
    opening = f"    {field.name}: "
    head_overhead = len(opening) + len(" = Field(")
    head = f"{opening}{explode_bracket(annotation, budget=PY_EXPLODE_WIDTH - head_overhead)} = Field("
    body = "".join(f"        {param},\n" for param in params)
    return f"{head}\n{body}    ){comment}"


def _split_top_level(inner: str) -> list[str]:
    """Split `a, b[c, d], e` on its top-level commas only — outside a bracket *and* outside a literal.

    The literal half is not decoration: a `Literal[...]` member is authored text, and an ordinary choice
    like `"yes, absolutely"` carries a comma. Split on it and the exploded annotation is two unterminated
    strings — generated Python that does not parse. Both quote styles have to be walked, because
    `escape_py_string` falls back to a single-quoted `repr` for a choice that itself contains a `"`.
    """
    members: list[str] = []
    depth = 0
    current = ""
    quote: str | None = None
    escaped = False
    for char in inner:
        if escaped:
            escaped = False
        elif quote is not None:
            if char == "\\":
                escaped = True
            elif char == quote:
                quote = None
        elif char in {'"', "'"}:
            quote = char
        elif char == "," and depth == 0:
            members.append(current.strip())
            current = ""
            continue
        else:
            depth += {"[": 1, "]": -1}.get(char, 0)
        current += char
    members.append(current.strip())
    return members


def explode_bracket(text: str, *, budget: int) -> str:
    """Split a `Name[a, b, c]` annotation (optionally `| None`) across lines, if it exceeds `budget`.

    Only the outermost bracket, and only when splitting it actually helps — that mirrors `ruff format`,
    which breaks at the outermost bracket first and stops as soon as the result fits, so the emitted shape
    is the one the formatter would have produced and therefore the one it leaves alone. The magic trailing
    comma is what pins it: with it, no line-length setting can rejoin the members.

    An optional annotation needs the parenthesized union form ruff wraps it in, one indent level deeper —
    `X[…] | None` is not a bracket at its tail, so the flat spelling would otherwise be left too long.
    """
    if len(text) <= budget:
        return text
    optional_suffix = " | None"
    base, is_optional = (text[: -len(optional_suffix)], True) if text.endswith(optional_suffix) else (text, False)
    if not base.endswith("]"):
        return text
    name, _, inner = base.partition("[")
    if not name or not inner:
        return text

    members = _split_top_level(inner[:-1])
    if len(members) < 2:
        return text

    depth = 3 if is_optional else 2
    rendered = "".join(f"{_PY_INDENT * depth}{member},\n" for member in members)
    exploded = f"{name}[\n{rendered}{_PY_INDENT * (depth - 1)}]"
    if not is_optional:
        return exploded
    return f"(\n{_PY_INDENT * 2}{exploded}\n{_PY_INDENT * 2}| None\n{_PY_INDENT})"


def any_annotation(*, imports: set[str]) -> str:
    """The `Any` annotation, registering its import — the honest spelling for an imprecise type."""
    imports.add("from typing import Any")
    return "Any"


def literal_annotation(*, choices: list[str] | None, imports: set[str]) -> str:
    """The `Literal[...]` annotation, with double-quoted members (`repr()` would pick single quotes)."""
    imports.add("from typing import Literal")
    members = ", ".join(escape_py_string(choice) for choice in choices or [])
    return f"Literal[{members}]"


def render_import_block(imports: set[str]) -> str:
    """Render the collected imports the way isort would, so the artifact is lint-clean on arrival.

    A flat `sorted()` over the raw statements is not isort order. Three things it misses: `from X import a`
    and `from X import b` have to merge into one line, stdlib has to be separated from third-party by
    a blank line, and a merged line past `PY_EXPLODE_WIDTH` has to arrive already exploded (see
    `_import_statement`) or the consumer's formatter explodes it for us.

    Grouping targets the **consumer's** tree, where `pipelex` is an installed dependency and therefore
    third-party. In this repo `pipelex` is first-party, so ruff here wants the opposite order — but no
    generated artifact is ever committed to this repo, and the consumer is the only one who lints these
    files. `tests/unit/pipelex/codegen/test_emitted_artifacts_are_lint_clean.py` lints them as a consumer
    would, for that reason.
    """
    names_by_module: dict[str, set[str]] = defaultdict(set)
    for statement in imports:
        module, _, names = statement.removeprefix("from ").partition(" import ")
        names_by_module[module].update(name.strip() for name in names.split(","))

    stdlib: list[str] = []
    third_party: list[str] = []
    for module in sorted(names_by_module):
        statement = _import_statement(module=module, names=sorted(names_by_module[module]))
        group = stdlib if module.partition(".")[0] in sys.stdlib_module_names else third_party
        group.append(statement)

    return "\n\n".join("\n".join(group) for group in (stdlib, third_party) if group)


def _import_statement(*, module: str, names: list[str]) -> str:
    """One `from … import …` statement, pre-exploded past `PY_EXPLODE_WIDTH` like its sibling renderers.

    A flat import line is a formatter's business exactly like a flat `Field(...)` call: past the
    consumer's `line-length`, `ruff format` rewrites it into this parenthesized, magic-trailing-comma
    form — which changes the body bytes and makes `codegen check` report the file as hand-edited.
    Emitting the exploded form ourselves makes the artifact a fixed point at any width >= the
    threshold. Ruff wraps a single overlong name the same way, so the rule needs no name-count arm.
    """
    flat = f"from {module} import {', '.join(names)}"
    if len(flat) <= PY_EXPLODE_WIDTH:
        return flat
    rendered = "".join(f"{_PY_INDENT}{name},\n" for name in names)
    return f"from {module} import (\n{rendered})"


def python_module_body(*, header: str, imports: set[str], blocks: list[str]) -> str:
    """Assemble a generated module; a projection with nothing to emit is its header alone.

    The empty artifact needs an explicit canonical form, because the populated one degenerates into
    something no formatter leaves alone: the import block has no class left to use it (`F401`, which
    `ruff check --fix` deletes) and the block separator becomes a trailing blank-line run (which
    `ruff format` collapses). Either rewrite changes the body bytes the stamp hashes, so `codegen
    check` reports the file as hand-edited. A header is inert under both.

    This is reachable without a degenerate crate: `python-structures` skips natives, so an ordinary
    method that declares no concepts of its own leaves that emitter with nothing to write.
    """
    if not blocks:
        return header
    return f"{header}from __future__ import annotations\n\n{render_import_block(imports)}\n\n\n" + "\n\n\n".join(blocks) + "\n"


def order_by_base(concepts: list[ResolvedConcept], *, in_module: set[str]) -> list[ResolvedConcept]:
    """Order concepts so an in-module refinement base is defined before its subclass (inheritance is eager)."""
    by_ref = {concept.concept_ref: concept for concept in concepts}
    ordered: list[ResolvedConcept] = []
    seen: set[str] = set()

    def visit(concept: ResolvedConcept) -> None:
        if concept.concept_ref in seen:
            return
        seen.add(concept.concept_ref)
        base_ref = concept.base_ref
        if base_ref is not None and base_ref in in_module and base_ref in by_ref:
            visit(by_ref[base_ref])
        ordered.append(concept)

    for concept in concepts:
        visit(concept)
    return ordered
