"""Rendering helpers shared by the two Python types emitters (structures + plain pydantic).

Only the target-agnostic pieces live here: string / default-value escaping, the generated-file
header (carrying the extension-file subclassing story), the class docstring, and the `= Field(...)`
assignment. Each Python emitter keeps its own resolved-type -> annotation walker, because the
container spelling (`typing.List`/`Optional` for the runtime idiom vs. builtin generics + `| None`
for plain pydantic) and the concept spelling (runtime content classes vs. generated models) differ.
"""

from datetime import date, datetime, time
from typing import Any, cast

from pipelex.codegen.resolved_concepts import ResolvedConcept
from pipelex.core.concepts.resolved_fields import ResolvedField, iter_imprecision_reasons


def python_header(*, target: str) -> str:
    """The generated-file header: an AUTOGENERATED marker plus the extension-file (subclassing) story."""
    return (
        "# ---------------------------------------------------------------------------\n"
        "# AUTOGENERATED by Pipelex codegen — DO NOT EDIT.\n"
        "#\n"
        "# This file is a projection of a normalized MTHDS library crate. It is\n"
        "# regenerated from the method; any hand edit here is overwritten.\n"
        "#\n"
        "# To customize a generated type, do NOT edit this file. Create a sibling\n"
        "# module and subclass — subclasses survive regeneration:\n"
        "#\n"
        "#     # my_types_ext.py\n"
        "#     from .structures import Report\n"
        "#\n"
        "#     class MyReport(Report):\n"
        "#         ...\n"
        "#\n"
        f"# projection: types / {target}\n"
        "# ---------------------------------------------------------------------------\n"
    )


def escape_py_string(value: str) -> str:
    """Escape a string for a double-quoted Python literal (handles quotes, backslashes, newlines)."""
    # repr() escapes everything correctly and returns a quoted literal; prefer double quotes when repr
    # chose single quotes (for consistency with the rest of the generated code).
    escaped = repr(value)
    if escaped.startswith("'") and escaped.endswith("'") and not escaped.startswith("'''"):
        inner = escaped[1:-1].replace("\\'", "'").replace('"', '\\"')
        return f'"{inner}"'
    return escaped


def format_default_value(value: Any) -> str:
    """Format a default value as Python source. Temporal values rebuild via `fromisoformat` so they
    use the bare `date` / `datetime` names the generated module imports (repr module-qualifies them).
    """
    if isinstance(value, str):
        return escape_py_string(value)
    if isinstance(value, datetime):
        return f'datetime.fromisoformat("{value.isoformat()}")'
    if isinstance(value, date):
        return f'date.fromisoformat("{value.isoformat()}")'
    if isinstance(value, time):
        return f'time.fromisoformat("{value.isoformat()}")'
    if isinstance(value, list):
        items = cast("list[Any]", value)
        return f"[{', '.join(format_default_value(item) for item in items)}]"
    if isinstance(value, dict):
        pairs = cast("dict[str, Any]", value)
        rendered = [f"{format_default_value(key)}: {format_default_value(pairs[key])}" for key in sorted(pairs)]
        return f"{{{', '.join(rendered)}}}"
    return repr(value)


def class_docstring(description: str, *, extra_line: str | None = None, indent: str = "    ") -> str:
    """Render a triple-quoted class docstring; append `extra_line` (e.g. an imprecision caveat) on its own line.

    The body goes through `escape_py_string`, which escapes every `"` (and backslashes, newlines, control
    chars), so a hostile description can never form a bare `\"\"\"` and break out of the docstring.
    """
    text = description or ""
    if extra_line:
        text = f"{text}\n\n{indent}{extra_line}" if text else extra_line
    quoted = escape_py_string(text)
    return f'{indent}"""{quoted[1:-1]}"""'


def field_line(field: ResolvedField, *, annotation: str) -> str:
    """Render one `name: <annotation> = Field(...)` line, surfacing any type-tree imprecision inline.

    `annotation` must already carry optionality in the emitter's own idiom (`Optional[...]` or `... | None`).
    """
    params: list[str]
    if field.required and field.default_value is None:
        params = ["..."]
    elif field.default_value is not None:
        params = [f"default={format_default_value(field.default_value)}"]
    else:
        params = ["default=None"]
    params.append(f"description={escape_py_string(field.description)}")

    line = f"    {field.name}: {annotation} = Field({', '.join(params)})"
    reasons = list(dict.fromkeys(iter_imprecision_reasons(field.resolved_type)))
    if reasons:
        line += f"  # imprecise: {'; '.join(reasons)}"
    return line


def any_annotation(*, imports: set[str]) -> str:
    """The `Any` annotation, registering its import — the honest spelling for an imprecise type."""
    imports.add("from typing import Any")
    return "Any"


def order_by_base(concepts: list[ResolvedConcept], *, in_module: set[str]) -> list[ResolvedConcept]:
    """Order concepts so an in-module refinement base is defined before its subclass (inheritance is eager)."""
    by_ref = {concept.concept_ref: concept for concept in concepts}
    ordered: list[ResolvedConcept] = []
    seen: set[str] = set()

    def visit(concept: ResolvedConcept) -> None:
        if concept.concept_ref in seen:
            return
        seen.add(concept.concept_ref)
        base_ref = concept.base_ref
        if base_ref is not None and base_ref in in_module and base_ref in by_ref:
            visit(by_ref[base_ref])
        ordered.append(concept)

    for concept in concepts:
        visit(concept)
    return ordered
