"""ts-zod emitter: project a crate's concept set as a pure TypeScript + Zod types file.

The purity split (see `docs/specs/pipelex-codegen.md`): this file imports **only** `zod` — Zod
schemas plus their inferred types — so it stays dependency-free and portable. The thin binder that
maps the snake_case wire payload to/from these camelCase domain types (parse / serialize helpers)
is a separate file, emitted alongside the runnable per-pipe projections.

Naming: type names are the concept codes (PascalCase, domain-qualified only on collision); field
keys are camelCase, and every field carries a JSDoc `@wire <snake_name>` tag so the snake<->camel
mapping the binder applies is documented at the type. Concept references use `z.lazy(() => XSchema)`
so schema declaration order is irrelevant and reference cycles are handled.

TypeScript customization is by declaration merging (augment the generated `interface`/module from a
sibling file), the TS analog of the Python subclassing story; the generated file is never edited.
"""

import json

from pipelex.codegen.emitters.naming import snake_to_camel, ts_type_name
from pipelex.codegen.emitters.target import EmittedFile
from pipelex.codegen.resolved_concepts import ResolvedConcept, ResolvedLibrary
from pipelex.codegen.resolved_fields import ResolvedField, ResolvedType, ResolvedTypeKind, iter_imprecision_reasons

_FILENAME = "types.ts"


def emit_ts_zod(library: ResolvedLibrary) -> list[EmittedFile]:
    """Emit the pure `types.ts` file: a `<Name>Schema` const and inferred `<Name>` type per concept."""
    by_ref = library.by_ref()
    header = _ts_header()
    blocks = [_render_schema(concept, by_ref=by_ref) for concept in library.concepts]
    body = f'{header}import {{ z }} from "zod";\n\n\n' + "\n\n\n".join(blocks) + "\n"
    return [EmittedFile(filename=_FILENAME, content=body)]


def _ts_header() -> str:
    return (
        "// ---------------------------------------------------------------------------\n"
        "// AUTOGENERATED by Pipelex codegen — DO NOT EDIT.\n"
        "//\n"
        "// This file is a projection of a normalized MTHDS library crate. It is\n"
        "// regenerated from the method; any hand edit here is overwritten.\n"
        "//\n"
        "// To customize a generated type, do NOT edit this file. Augment it from a\n"
        "// sibling module via declaration merging — augmentations survive regeneration.\n"
        "//\n"
        "// projection: types / ts-zod\n"
        "// ---------------------------------------------------------------------------\n"
    )


def _render_schema(concept: ResolvedConcept, *, by_ref: dict[str, ResolvedConcept]) -> str:
    type_name = ts_type_name(domain=concept.domain, code=concept.code, needs_qualification=concept.needs_qualification)
    doc = _jsdoc(concept.description, wire=None, imprecise=concept.imprecision_reason if concept.structureless else None)

    schema_expr = _schema_expr(concept, by_ref=by_ref)
    return f"{doc}export const {type_name}Schema = {schema_expr};\nexport type {type_name} = z.infer<typeof {type_name}Schema>;"


def _schema_expr(concept: ResolvedConcept, *, by_ref: dict[str, ResolvedConcept]) -> str:
    if concept.base_ref is not None and not concept.fields:
        base = by_ref.get(concept.base_ref)
        if base is not None:
            base_name = ts_type_name(domain=base.domain, code=base.code, needs_qualification=base.needs_qualification)
            return f"z.lazy(() => {base_name}Schema)"
        return "z.unknown()"
    if not concept.fields:
        # Structureless / opaque concept: unknown shape, surfaced (never guessed).
        return "z.unknown()"
    field_lines = "\n".join(_render_field(concept_field, by_ref=by_ref) for concept_field in concept.fields)
    return f"z.object({{\n{field_lines}\n}})"


def _render_field(concept_field: ResolvedField, *, by_ref: dict[str, ResolvedConcept]) -> str:
    key = snake_to_camel(concept_field.name)
    reasons = list(dict.fromkeys(iter_imprecision_reasons(concept_field.resolved_type)))
    doc = _jsdoc(concept_field.description, wire=concept_field.name, imprecise="; ".join(reasons) if reasons else None, indent="  ")
    expr = _zod_type(concept_field.resolved_type, by_ref=by_ref)
    if concept_field.default_value is not None:
        expr = f"{expr}.default({json.dumps(concept_field.default_value)})"
    elif not concept_field.required:
        expr = f"{expr}.optional()"
    return f"{doc}  {key}: {expr},"


def _zod_type(resolved_type: ResolvedType, *, by_ref: dict[str, ResolvedConcept]) -> str:
    match resolved_type.kind:
        case ResolvedTypeKind.TEXT:
            return "z.string()"
        case ResolvedTypeKind.NUMBER:
            return "z.number()"
        case ResolvedTypeKind.INTEGER:
            return "z.number().int()"
        case ResolvedTypeKind.BOOLEAN:
            return "z.boolean()"
        case ResolvedTypeKind.DATE | ResolvedTypeKind.DATETIME:
            # ISO date / datetime string on the wire (the `@wire` field keeps the shape documented).
            return "z.string()"
        case ResolvedTypeKind.LITERAL:
            choices = ", ".join(json.dumps(choice) for choice in resolved_type.choices or [])
            return f"z.enum([{choices}])"
        case ResolvedTypeKind.CONCEPT:
            return _concept_schema(resolved_type, by_ref=by_ref)
        case ResolvedTypeKind.LIST:
            item = _zod_type(resolved_type.item, by_ref=by_ref) if resolved_type.item else "z.unknown()"
            return f"z.array({item})"
        case ResolvedTypeKind.DICT:
            value = _zod_type(resolved_type.value, by_ref=by_ref) if resolved_type.value else "z.unknown()"
            return f"z.record(z.string(), {value})"
        case ResolvedTypeKind.ANY:
            return "z.unknown()"


def _concept_schema(resolved_type: ResolvedType, *, by_ref: dict[str, ResolvedConcept]) -> str:
    concept_ref = resolved_type.concept_ref
    if concept_ref is None:
        return "z.unknown()"
    concept = by_ref.get(concept_ref)
    if concept is not None:
        name = ts_type_name(domain=concept.domain, code=concept.code, needs_qualification=concept.needs_qualification)
        return f"z.lazy(() => {name}Schema)"
    return "z.unknown()"


def _jsdoc(description: str, *, wire: str | None, imprecise: str | None, indent: str = "") -> str:
    parts = [description] if description else []
    if wire is not None:
        parts.append(f"@wire {wire}")
    if imprecise:
        parts.append(f"@imprecise {imprecise}")
    if not parts:
        return ""
    if len(parts) == 1 and wire is None and imprecise is None:
        return f"{indent}/** {parts[0]} */\n"
    body = "".join(f"{indent} * {part}\n" for part in parts)
    return f"{indent}/**\n{body}{indent} */\n"
