"""ts-zod emitter: project a crate's concept set as a pure TypeScript + Zod types file plus a binder.

`types.ts` imports **only** `zod` — Zod schemas plus their inferred types — so it stays dependency-free
and portable. `binder.ts` is the thin companion that exposes a typed `parse<Name>` / `serialize<Name>`
pair per concept over those schemas. A pipe's IO types are concepts, so a pipe's output parser / input
serializer is just the binder pair for those concept types — the binder is the concept-set-wide
realization of the per-pipe parse/serialize helpers.

**Wire-native field keys (D10).** Object keys are the crate's snake_case field names *verbatim*, so a
schema validates a wire payload directly — no key remapping layer, and therefore no way to silently
corrupt arbitrary keys inside a `z.record()` / `z.unknown()` value (a camelCase remapping binder can't
tell a schema-declared field key from arbitrary data — e.g. `native.JSON`'s `json_obj` map). The
inferred `z.infer` types therefore carry snake_case keys. (This departs from a camelCase-TS convention;
if camelCase ergonomics are later wanted they must ride a *schema-aware* transform, not a blind deep
key remap — see D10 in `_codegen/TODOS.md`.) Concept references use `z.lazy(() => XSchema)` so schema
declaration order is irrelevant and reference cycles are handled.

TypeScript customization is by declaration merging (augment the generated `interface`/module from a
sibling file), the TS analog of the Python subclassing story; the generated files are never edited.
"""

import json
from typing import Any

from pipelex.codegen.emitters.naming import allocate_ts_type_names
from pipelex.codegen.emitters.target import EmittedFile
from pipelex.codegen.resolved_concepts import ResolvedConcept, ResolvedLibrary
from pipelex.core.concepts.resolved_fields import ResolvedField, ResolvedType, ResolvedTypeKind, iter_imprecision_reasons
from pipelex.tools.misc.json_utils import clean_json_content

_FILENAME = "types.ts"
_BINDER_FILENAME = "binder.ts"

# Prettier's default `printWidth`. The emitted files must be prettier-clean on arrival, or a consumer's
# formatter run rewrites the bytes and invalidates the codegen stamp (`pipelex codegen check` would then
# report the file as hand-edited). Two prettier behaviors drive the emitted shape: it collapses runs of
# blank lines to a single one, and it keeps an import on one line while it fits within this width.
_TS_PRINT_WIDTH = 80


def emit_ts_zod(library: ResolvedLibrary) -> list[EmittedFile]:
    """Emit the pure `types.ts` file and its `binder.ts` companion (wire<->domain parse/serialize)."""
    concepts = sorted(library.concepts, key=lambda concept: concept.concept_ref)
    by_ref = library.by_ref()
    type_name_by_ref = allocate_ts_type_names(library)
    recursive_refs = _find_recursive_concept_refs(concepts)
    header = _ts_header()
    blocks = [_render_schema(concept, by_ref=by_ref, type_name_by_ref=type_name_by_ref, recursive_refs=recursive_refs) for concept in concepts]
    if blocks:
        body = f'{header}import {{ z }} from "zod";\n\n' + "\n\n".join(blocks) + "\n"
    else:
        # Nothing to project: the header alone. Keeping the import would leave `z` unused above a trailing
        # blank-line run prettier collapses — a reformat, and a broken stamp. See `_emit_binder`.
        body = header
    return [EmittedFile(filename=_FILENAME, content=body), _emit_binder(concepts, type_name_by_ref=type_name_by_ref)]


def _ts_header() -> str:
    return (
        "// ---------------------------------------------------------------------------\n"
        "// AUTOGENERATED by Pipelex codegen — DO NOT EDIT.\n"
        "//\n"
        "// This file is a projection of a normalized MTHDS library crate. It is\n"
        "// regenerated from the method; any hand edit here is overwritten.\n"
        "//\n"
        "// To customize a generated type, do NOT edit this file. Augment it from a\n"
        "// sibling module via declaration merging — augmentations survive regeneration.\n"
        "//\n"
        "// projection: types / ts-zod\n"
        "// ---------------------------------------------------------------------------\n"
    )


def _render_schema(
    concept: ResolvedConcept,
    *,
    by_ref: dict[str, ResolvedConcept],
    type_name_by_ref: dict[str, str],
    recursive_refs: set[str],
) -> str:
    type_name = type_name_by_ref[concept.concept_ref]
    doc = _jsdoc(concept.description, imprecise=concept.imprecision_reason if concept.structureless else None)

    schema_expr = _schema_expr(concept, by_ref=by_ref, type_name_by_ref=type_name_by_ref)
    if concept.concept_ref in recursive_refs:
        type_expr = _concept_type_expr(concept, by_ref=by_ref, type_name_by_ref=type_name_by_ref)
        return f"{doc}export type {type_name} = {type_expr};\nexport const {type_name}Schema: z.ZodType<{type_name}> = {schema_expr};"
    return f"{doc}export const {type_name}Schema = {schema_expr};\nexport type {type_name} = z.infer<typeof {type_name}Schema>;"


def _schema_expr(
    concept: ResolvedConcept,
    *,
    by_ref: dict[str, ResolvedConcept],
    type_name_by_ref: dict[str, str],
) -> str:
    if concept.base_ref is not None and not concept.fields:
        base = by_ref.get(concept.base_ref)
        if base is not None:
            base_name = type_name_by_ref[base.concept_ref]
            return f"z.lazy(() => {base_name}Schema)"
        return "z.unknown()"
    if not concept.fields:
        if concept.structureless:
            # Structureless / opaque concept: unknown shape, surfaced (never guessed).
            return "z.unknown()"
        return "z.object({})"
    field_lines = "\n".join(_render_field(concept_field, by_ref=by_ref, type_name_by_ref=type_name_by_ref) for concept_field in concept.fields)
    return f"z.object({{\n{field_lines}\n}})"


def _render_field(
    concept_field: ResolvedField,
    *,
    by_ref: dict[str, ResolvedConcept],
    type_name_by_ref: dict[str, str],
) -> str:
    # Wire-native key: the crate's snake_case field name verbatim (D10), so the schema validates the
    # wire payload directly and no key transform can corrupt nested record/opaque data.
    key = concept_field.name
    reasons = list(dict.fromkeys(iter_imprecision_reasons(concept_field.resolved_type)))
    doc = _jsdoc(concept_field.description, imprecise="; ".join(reasons) if reasons else None, indent="  ")
    expr = _zod_type(concept_field.resolved_type, by_ref=by_ref, type_name_by_ref=type_name_by_ref)
    if concept_field.default_value is not None:
        expr = f"{expr}.default({_format_default_value(concept_field.default_value)})"
    elif not concept_field.required:
        expr = f"{expr}.optional()"
    return f"{doc}  {key}: {expr},"


def _format_default_value(value: Any) -> str:
    """Render a JSON-safe default canonically so mapping insertion order cannot affect output."""
    return json.dumps(clean_json_content(value), sort_keys=True)


def _concept_type_expr(
    concept: ResolvedConcept,
    *,
    by_ref: dict[str, ResolvedConcept],
    type_name_by_ref: dict[str, str],
) -> str:
    """Render the explicit TypeScript type required to break recursive schema inference."""
    if concept.base_ref is not None and not concept.fields:
        base = by_ref.get(concept.base_ref)
        return type_name_by_ref[base.concept_ref] if base is not None else "unknown"
    if concept.structureless:
        return "unknown"
    field_lines = "\n".join(_render_type_field(field, by_ref=by_ref, type_name_by_ref=type_name_by_ref) for field in concept.fields)
    return f"{{\n{field_lines}\n}}"


def _render_type_field(
    concept_field: ResolvedField,
    *,
    by_ref: dict[str, ResolvedConcept],
    type_name_by_ref: dict[str, str],
) -> str:
    optional_marker = "?" if not concept_field.required and concept_field.default_value is None else ""
    type_expr = _ts_type(concept_field.resolved_type, by_ref=by_ref, type_name_by_ref=type_name_by_ref)
    return f"  {concept_field.name}{optional_marker}: {type_expr};"


def _ts_type(
    resolved_type: ResolvedType,
    *,
    by_ref: dict[str, ResolvedConcept],
    type_name_by_ref: dict[str, str],
) -> str:
    """Render one neutral resolved type as an explicit TypeScript type expression."""
    match resolved_type.kind:
        case ResolvedTypeKind.TEXT | ResolvedTypeKind.DATE | ResolvedTypeKind.DATETIME | ResolvedTypeKind.TIME:
            return "string"
        case ResolvedTypeKind.NUMBER | ResolvedTypeKind.INTEGER:
            return "number"
        case ResolvedTypeKind.BOOLEAN:
            return "boolean"
        case ResolvedTypeKind.LITERAL:
            return " | ".join(json.dumps(choice) for choice in resolved_type.choices or [])
        case ResolvedTypeKind.CONCEPT:
            return _concept_type(resolved_type, by_ref=by_ref, type_name_by_ref=type_name_by_ref)
        case ResolvedTypeKind.LIST:
            item = _ts_type(resolved_type.item, by_ref=by_ref, type_name_by_ref=type_name_by_ref) if resolved_type.item else "unknown"
            return f"Array<{item}>"
        case ResolvedTypeKind.DICT:
            value = _ts_type(resolved_type.value, by_ref=by_ref, type_name_by_ref=type_name_by_ref) if resolved_type.value else "unknown"
            return f"Record<string, {value}>"
        case ResolvedTypeKind.ANY:
            return "unknown"


def _concept_type(
    resolved_type: ResolvedType,
    *,
    by_ref: dict[str, ResolvedConcept],
    type_name_by_ref: dict[str, str],
) -> str:
    concept_ref = resolved_type.concept_ref
    if concept_ref is None:
        return "unknown"
    concept = by_ref.get(concept_ref)
    return type_name_by_ref[concept.concept_ref] if concept is not None else "unknown"


def _find_recursive_concept_refs(concepts: list[ResolvedConcept]) -> set[str]:
    """Find concepts that can reach themselves through an in-crate type reference."""
    graph = {concept.concept_ref: _concept_dependencies(concept) for concept in concepts}
    recursive_refs: set[str] = set()
    for origin_ref, dependencies in graph.items():
        pending_refs = list(dependencies)
        visited_refs: set[str] = set()
        while pending_refs:
            current_ref = pending_refs.pop()
            if current_ref == origin_ref:
                recursive_refs.add(origin_ref)
                break
            if current_ref in visited_refs:
                continue
            visited_refs.add(current_ref)
            pending_refs.extend(graph.get(current_ref, set()))
    return recursive_refs


def _concept_dependencies(concept: ResolvedConcept) -> set[str]:
    dependencies: set[str] = {concept.base_ref} if concept.base_ref is not None else set()
    for concept_field in concept.fields:
        dependencies.update(_resolved_type_concept_refs(concept_field.resolved_type))
    return dependencies


def _resolved_type_concept_refs(resolved_type: ResolvedType) -> set[str]:
    concept_refs: set[str] = {resolved_type.concept_ref} if resolved_type.concept_ref is not None else set()
    for child_type in (resolved_type.item, resolved_type.key, resolved_type.value):
        if child_type is not None:
            concept_refs.update(_resolved_type_concept_refs(child_type))
    return concept_refs


def _zod_type(
    resolved_type: ResolvedType,
    *,
    by_ref: dict[str, ResolvedConcept],
    type_name_by_ref: dict[str, str],
) -> str:
    match resolved_type.kind:
        case ResolvedTypeKind.TEXT:
            return "z.string()"
        case ResolvedTypeKind.NUMBER:
            return "z.number()"
        case ResolvedTypeKind.INTEGER:
            return "z.number().int()"
        case ResolvedTypeKind.BOOLEAN:
            return "z.boolean()"
        case ResolvedTypeKind.DATE | ResolvedTypeKind.DATETIME | ResolvedTypeKind.TIME:
            # ISO date / datetime / time string on the wire (the `@wire` field keeps the shape documented).
            return "z.string()"
        case ResolvedTypeKind.LITERAL:
            choices = ", ".join(json.dumps(choice) for choice in resolved_type.choices or [])
            return f"z.enum([{choices}])"
        case ResolvedTypeKind.CONCEPT:
            return _concept_schema(resolved_type, by_ref=by_ref, type_name_by_ref=type_name_by_ref)
        case ResolvedTypeKind.LIST:
            item = _zod_type(resolved_type.item, by_ref=by_ref, type_name_by_ref=type_name_by_ref) if resolved_type.item else "z.unknown()"
            return f"z.array({item})"
        case ResolvedTypeKind.DICT:
            value = _zod_type(resolved_type.value, by_ref=by_ref, type_name_by_ref=type_name_by_ref) if resolved_type.value else "z.unknown()"
            return f"z.record(z.string(), {value})"
        case ResolvedTypeKind.ANY:
            return "z.unknown()"


def _concept_schema(
    resolved_type: ResolvedType,
    *,
    by_ref: dict[str, ResolvedConcept],
    type_name_by_ref: dict[str, str],
) -> str:
    concept_ref = resolved_type.concept_ref
    if concept_ref is None:
        return "z.unknown()"
    concept = by_ref.get(concept_ref)
    if concept is not None:
        name = type_name_by_ref[concept.concept_ref]
        return f"z.lazy(() => {name}Schema)"
    return "z.unknown()"


def _emit_binder(concepts: list[ResolvedConcept], *, type_name_by_ref: dict[str, str]) -> EmittedFile:
    """Emit `binder.ts`: typed `parse<Name>` / `serialize<Name>` helpers over the `types.ts` schemas.

    Keys are wire-native (D10), so parse/serialize are a direct `Schema.parse` — no key remapping, and
    thus no risk of corrupting arbitrary keys inside a `z.record()` / `z.unknown()` value.
    """
    type_names = [type_name_by_ref[concept.concept_ref] for concept in concepts]
    if not type_names:
        # No pair to bind: the header alone is the canonical empty binder. The populated shape degenerates
        # into `import {  } from "./types";` (prettier rewrites the empty brace pair) above a trailing
        # blank-line run (prettier collapses it) — either reformat breaks the stamped body hash.
        return EmittedFile(filename=_BINDER_FILENAME, content=_binder_header())

    specifiers = [specifier for name in type_names for specifier in (f"{name}Schema", f"type {name}")]
    pairs = "\n\n".join(_binder_pair(name) for name in type_names)

    # Match prettier: one line while it fits, otherwise one specifier per line.
    single_line = f'import {{ {", ".join(specifiers)} }} from "./types";'
    if len(single_line) <= _TS_PRINT_WIDTH:
        prelude = single_line
    else:
        import_lines = "\n".join(f"  {specifier}," for specifier in specifiers)
        prelude = f'import {{\n{import_lines}\n}} from "./types";'

    return EmittedFile(filename=_BINDER_FILENAME, content=f"{_binder_header()}{prelude}\n\n{pairs}\n")


def _binder_pair(type_name: str) -> str:
    """The `parse<Name>` / `serialize<Name>` pair for one concept type (wire-native, so `Schema.parse`)."""
    return (
        f"/** Parse a wire payload into a validated `{type_name}`. */\n"
        f"export function parse{type_name}(wire: unknown): {type_name} {{\n"
        f"  return {type_name}Schema.parse(wire);\n"
        f"}}\n\n"
        f"/** Validate a `{type_name}` for the wire (keys are already wire-native). */\n"
        f"export function serialize{type_name}(value: {type_name}): {type_name} {{\n"
        f"  return {type_name}Schema.parse(value);\n"
        f"}}"
    )


def _binder_header() -> str:
    return (
        "// ---------------------------------------------------------------------------\n"
        "// AUTOGENERATED by Pipelex codegen — DO NOT EDIT.\n"
        "//\n"
        "// Typed parse/serialize helpers over the pure `types.ts` schemas. Field keys are\n"
        "// wire-native (snake_case), so parse/serialize validate the wire payload directly.\n"
        "//\n"
        "// projection: types / ts-zod (binder)\n"
        "// ---------------------------------------------------------------------------\n"
    )


def _jsdoc(description: str, *, imprecise: str | None, indent: str = "") -> str:
    parts = _sanitize_jsdoc_text(description).split("\n") if description else []
    if imprecise:
        imprecise_lines = _sanitize_jsdoc_text(imprecise).split("\n")
        parts.append(f"@imprecise {imprecise_lines[0]}")
        parts.extend(imprecise_lines[1:])
    if not parts:
        return ""
    if len(parts) == 1 and imprecise is None:
        return f"{indent}/** {parts[0]} */\n"
    body = "".join(f"{indent} * {part}\n" for part in parts)
    return f"{indent}/**\n{body}{indent} */\n"


def _sanitize_jsdoc_text(value: str) -> str:
    """Normalize line endings and neutralize comment terminators in authored JSDoc text."""
    normalized = value.replace("\r\n", "\n").replace("\r", "\n")
    return normalized.replace("*/", "* /")
