from enum import StrEnum
from typing import Annotated, Any, cast

from pydantic import BaseModel, ConfigDict, Field, ValidationInfo, field_validator, model_validator
from pydantic.json_schema import SkipJsonSchema

from pipelex.core.bundles.exceptions import InvalidPipeCodeSyntaxError, NativeConceptRedeclarationError
from pipelex.core.concepts.concept_blueprint import ConceptBlueprint
from pipelex.core.concepts.concept_structure_blueprint import ConceptStructureBlueprint
from pipelex.core.concepts.native.concept_native import NativeConceptCode
from pipelex.core.concepts.validation import is_concept_code_valid
from pipelex.core.domains.exceptions import DomainCodeError
from pipelex.core.domains.validation import validate_domain_code
from pipelex.core.pipes.pipe_blueprint import normalize_typeless_signature_section
from pipelex.core.pipes.validation import is_pipe_code_valid
from pipelex.core.pipes.variable_multiplicity import parse_concept_with_multiplicity
from pipelex.pipe_controllers.batch.pipe_batch_blueprint import PipeBatchBlueprint
from pipelex.pipe_controllers.condition.pipe_condition_blueprint import PipeConditionBlueprint
from pipelex.pipe_controllers.parallel.pipe_parallel_blueprint import PipeParallelBlueprint
from pipelex.pipe_controllers.sequence.pipe_sequence_blueprint import PipeSequenceBlueprint
from pipelex.pipe_operators.compose.pipe_compose_blueprint import PipeComposeBlueprint
from pipelex.pipe_operators.extract.pipe_extract_blueprint import PipeExtractBlueprint
from pipelex.pipe_operators.func.pipe_func_blueprint import PipeFuncBlueprint
from pipelex.pipe_operators.img_gen.pipe_img_gen_blueprint import PipeImgGenBlueprint
from pipelex.pipe_operators.llm.pipe_llm_blueprint import PipeLLMBlueprint
from pipelex.pipe_operators.search.pipe_search_blueprint import PipeSearchBlueprint
from pipelex.pipe_operators.structure.pipe_structure_blueprint import PipeStructureBlueprint
from pipelex.pipe_signature.pipe_signature_blueprint import PipeSignatureBlueprint
from pipelex.urls import URLs


def _strippable_same_domain_pipe_code(code: str, *, domain: str | None, existing_pipe_codes: set[str] | None = None) -> str | None:
    """Return the namespace-stripped bare code when ``code`` is a safely-strippable same-domain
    over-qualification (``<domain>.<bare>``), else ``None`` — the raise-site gate for
    ``strip-namespace``.

    Strippable requires: a dotted code whose prefix equals the bundle's own ``domain``, a bare tail
    that is itself a valid snake_case pipe code, and — for a declaration key, where
    ``existing_pipe_codes`` is supplied — no bare code already occupying that key (the rename would
    collide). ``main_pipe`` passes ``existing_pipe_codes=None``: it is a single value, not a table
    key, and the ``pipe`` field is not yet validated when the ``main_pipe`` validator runs — its
    safety gate lives in the blueprint categorizer (``_main_pipe_strip_is_safe``), which holds the
    raw bundle dict and drops the enrichment when stripping would retarget ``main_pipe`` to a
    different declaration or rewrite it to a pipe that does not exist.
    """
    if domain is None or "." not in code:
        return None
    prefix, bare = code.rsplit(".", 1)
    if prefix != domain or not is_pipe_code_valid(bare):
        return None
    if existing_pipe_codes is not None and bare in existing_pipe_codes:
        return None
    return bare


PipeBlueprintUnion = Annotated[
    PipeFuncBlueprint
    | PipeImgGenBlueprint
    | PipeComposeBlueprint
    | PipeLLMBlueprint
    | PipeExtractBlueprint
    | PipeSearchBlueprint
    | PipeStructureBlueprint
    | PipeBatchBlueprint
    | PipeConditionBlueprint
    | PipeParallelBlueprint
    | PipeSequenceBlueprint
    | PipeSignatureBlueprint,
    Field(discriminator="type"),
]


class StepRole(StrEnum):
    """Role played by a synthetic pipe inside an elaborated bundle.

    DRAFT_TEXT: step-1 of a `preliminary_text` elaboration — the pipe that produces the draft Text.
    STRUCTURE: step-2 of a `preliminary_text` elaboration — the pipe that turns the draft Text into the structured concept.
    """

    DRAFT_TEXT = "draft_text"
    STRUCTURE = "structure"


class ElaborationMetadata(BaseModel):
    """Side-table entry recording how a synthetic pipe was generated by the bundle elaborator."""

    parent_pipe_code: str
    step_role: StepRole


class PipelexBundleBlueprint(BaseModel):
    model_config = ConfigDict(extra="forbid")

    source: str | None = None
    domain: str
    description: str | None = None
    system_prompt: str | None = None
    main_pipe: str | None = None

    concept: dict[str, ConceptBlueprint | str] | None = Field(default_factory=dict)

    pipe: dict[str, PipeBlueprintUnion] | None = Field(default_factory=dict)

    # Process-local side-table populated by `BundleElaborator`. `exclude=True` drops it from
    # `model_dump()` / `model_validate()` round-trips so MTHDS / TOML / JSON exports stay
    # clean. `SkipJsonSchema[...]` ALSO hides the field (and its `ElaborationMetadata` /
    # `StepRole` definitions) from the generated JSON schema — Pydantic v2's `exclude=True`
    # by itself does not affect `model_json_schema()`. Persisting it for downstream
    # consumers — graph viewer, Temporal payload, library cache — is captured as a
    # follow-up in TODOS.md.
    elaboration_metadata: SkipJsonSchema[dict[str, ElaborationMetadata] | None] = Field(default=None, exclude=True)

    @field_validator("domain", mode="before")
    @classmethod
    def validate_domain_syntax(cls, domain_code: str) -> str:
        try:
            validate_domain_code(code=domain_code)
        except DomainCodeError as exc:
            msg = f"Error when trying to validate the pipelex bundle at domain '{domain_code}': {exc}"
            raise ValueError(msg) from exc
        return domain_code

    @field_validator("concept", mode="before")
    @classmethod
    def validate_concept_keys(cls, concept: dict[str, ConceptBlueprint | str] | None) -> dict[str, ConceptBlueprint | str] | None:
        if concept is None:
            return None
        native_concept_codes = [native.value for native in NativeConceptCode.values_list()]
        for concept_code in concept:
            if not is_concept_code_valid(concept_code=concept_code):
                msg = f"Concept code '{concept_code}' is not a valid concept code"
                raise ValueError(msg)
            if concept_code in native_concept_codes:
                msg = (
                    f"Cannot declare a concept named '{concept_code}' because it is natively available in Pipelex. "
                    f"Native concepts are: {', '.join(native_concept_codes)}. "
                    f"See {URLs.native_concepts_docs}"
                )
                # Typed (still a ValueError, so pydantic wraps it into ``ctx["error"]``) so the
                # blueprint categorizer recovers the offending code structurally for the fix planner.
                raise NativeConceptRedeclarationError(msg, concept_code=concept_code)
        return concept

    @field_validator("main_pipe", mode="before")
    @classmethod
    def validate_main_pipe_syntax(cls, main_pipe: str | None, info: ValidationInfo) -> str | None:
        if main_pipe is None:
            return None
        if not is_pipe_code_valid(main_pipe):
            msg = f"Invalid main pipe syntax '{main_pipe}'. Must be in snake_case."
            stripped = _strippable_same_domain_pipe_code(main_pipe, domain=cast("str | None", info.data.get("domain")))
            if stripped is not None:
                # Typed (still a ValueError, so pydantic wraps it into ``ctx["error"]``) so the
                # blueprint categorizer recovers the strip target structurally for the fix planner.
                raise InvalidPipeCodeSyntaxError(msg, offending_code=main_pipe, stripped_code=stripped)
            raise ValueError(msg)
        return main_pipe

    @field_validator("pipe", mode="before")
    @classmethod
    def validate_pipe_keys(cls, pipe: Any, info: ValidationInfo) -> Any:
        """Validate pipe codes and normalize typeless sections before the discriminated union runs.

        A `[pipe.x]` section with no `type` whose keys are exactly the signature contract
        (`SIGNATURE_ONLY_KEYS`) is normalized by injecting the internal `PipeSignature`
        discriminator, so the union routes it to `PipeSignatureBlueprint` — the author never writes
        the tag. A typeless section that declares anything more is describing an implementation
        without naming its type, which is a hard error. A section that already names a `type` (or is
        an already-built blueprint instance rather than a raw dict) passes through untouched.
        """
        if pipe is None:
            return None
        if not isinstance(pipe, dict):
            # Let the field type raise its own "should be a dict" error.
            return pipe
        typed_pipe = cast("dict[Any, Any]", pipe)
        domain = cast("str | None", info.data.get("domain"))
        existing_pipe_codes = {key for key in typed_pipe if isinstance(key, str)}
        normalized: dict[Any, Any] = {}
        for pipe_code, pipe_section in typed_pipe.items():
            if isinstance(pipe_code, str) and not is_pipe_code_valid(pipe_code=pipe_code):
                msg = f"Pipe code '{pipe_code}' is not a valid pipe code. Must be in snake_case."
                stripped = _strippable_same_domain_pipe_code(pipe_code, domain=domain, existing_pipe_codes=existing_pipe_codes)
                if stripped is not None:
                    # Typed (still a ValueError) so the categorizer recovers the rename target
                    # (offending dotted key + stripped bare key) structurally for the fix planner.
                    raise InvalidPipeCodeSyntaxError(msg, offending_code=pipe_code, stripped_code=stripped)
                raise ValueError(msg)
            normalized[pipe_code] = normalize_typeless_signature_section(pipe_code=pipe_code, pipe_section=pipe_section)
        return normalized

    @model_validator(mode="after")
    def validate_main_pipe(self) -> "PipelexBundleBlueprint":
        if self.main_pipe and (not self.pipe or (self.main_pipe not in self.pipe)):
            msg = f"Main pipe '{self.main_pipe}' could not be found in pipelex bundle at source '{self.source}' and domain '{self.domain}'"
            raise ValueError(msg)
        return self

    def get_elaboration_for(self, pipe_code: str) -> ElaborationMetadata | None:
        """Return the elaboration metadata for a synthetic pipe, or None if the pipe is user-authored."""
        if not self.elaboration_metadata:
            return None
        return self.elaboration_metadata.get(pipe_code)

    def collect_pipe_references(self) -> list[tuple[str, str]]:
        """Collect all pipe references from controller blueprints.

        Returns:
            List of (pipe_ref_string, context_description) tuples
        """
        pipe_refs: list[tuple[str, str]] = []
        if not self.pipe:
            return pipe_refs

        for pipe_code, pipe_blueprint in self.pipe.items():
            if isinstance(pipe_blueprint, PipeSequenceBlueprint):
                for step_index, step in enumerate(pipe_blueprint.steps):
                    pipe_refs.append((step.pipe, f"pipe.{pipe_code}.steps[{step_index}].pipe"))
            elif isinstance(pipe_blueprint, PipeBatchBlueprint):
                pipe_refs.append((pipe_blueprint.branch_pipe_code, f"pipe.{pipe_code}.branch_pipe_code"))
            elif isinstance(pipe_blueprint, PipeConditionBlueprint):
                for outcome_key, outcome_pipe in pipe_blueprint.outcomes.items():
                    pipe_refs.append((outcome_pipe, f"pipe.{pipe_code}.outcomes[{outcome_key}]"))
                pipe_refs.append((pipe_blueprint.default_outcome, f"pipe.{pipe_code}.default_outcome"))
            elif isinstance(pipe_blueprint, PipeParallelBlueprint):
                for branch_index, branch in enumerate(pipe_blueprint.branches):
                    pipe_refs.append((branch.pipe, f"pipe.{pipe_code}.branches[{branch_index}].pipe"))

        return pipe_refs

    def collect_concept_references(self) -> list[tuple[str, str]]:
        """Collect all concept references from this bundle's concepts and pipes.

        Mirrors collect_pipe_references(): returns every concept reference (bare code,
        same-domain, external-domain, or cross-package) paired with a context path. The
        caller decides which references to resolve and where. Reference resolution for
        same-domain refs is performed at library level over the merged crate, not per file,
        so a concept declared in one file can be referenced from a sibling file.

        Returns:
            List of (concept_ref_or_code, context_description) tuples
        """
        local_refs: list[tuple[str, str]] = []

        # Collect from concepts
        if self.concept:
            for concept_code, concept_blueprint in self.concept.items():
                local_refs.extend(self._collect_local_refs_from_concept(concept_code, concept_blueprint=concept_blueprint))

        # Collect from pipes
        if self.pipe:
            for pipe_code, pipe_blueprint in self.pipe.items():
                local_refs.extend(self._collect_local_refs_from_pipe(pipe_code, pipe_blueprint=pipe_blueprint))

        return local_refs

    def _collect_local_refs_from_concept(self, concept_code: str, *, concept_blueprint: ConceptBlueprint | str) -> list[tuple[str, str]]:
        local_refs: list[tuple[str, str]] = []

        if isinstance(concept_blueprint, str):
            return local_refs

        # Check refines field
        if concept_blueprint.refines:
            local_refs.append((concept_blueprint.refines, f"concept.{concept_code}.refines"))

        # Check structure fields
        if isinstance(concept_blueprint.structure, dict):
            for field_name, field_blueprint in concept_blueprint.structure.items():
                if isinstance(field_blueprint, ConceptStructureBlueprint):
                    # Check concept_ref
                    if field_blueprint.concept_ref:
                        local_refs.append((field_blueprint.concept_ref, f"concept.{concept_code}.structure.{field_name}.concept_ref"))
                    # Check item_concept_ref
                    if field_blueprint.item_concept_ref:
                        local_refs.append((field_blueprint.item_concept_ref, f"concept.{concept_code}.structure.{field_name}.item_concept_ref"))

        return local_refs

    def _collect_local_refs_from_pipe(self, pipe_code: str, *, pipe_blueprint: PipeBlueprintUnion) -> list[tuple[str, str]]:
        local_refs: list[tuple[str, str]] = []

        # Check inputs
        if pipe_blueprint.inputs:
            for input_name, input_concept_spec in pipe_blueprint.inputs.items():
                local_ref = parse_concept_with_multiplicity(input_concept_spec).concept_ref_or_code
                local_refs.append((local_ref, f"pipe.{pipe_code}.inputs.{input_name}"))

        # Check output
        local_ref = parse_concept_with_multiplicity(pipe_blueprint.output).concept_ref_or_code
        local_refs.append((local_ref, f"pipe.{pipe_code}.output"))

        return local_refs
