import base64
import hashlib

import httpx

from pipelex import log
from pipelex.cogt.content_generation.exceptions import NeitherUrlNorDataError
from pipelex.cogt.extract.extract_output import ExtractOutput
from pipelex.cogt.image.generated_image import GeneratedImageRawDetails
from pipelex.config import get_config
from pipelex.core.stuffs.image_content import ImageContent
from pipelex.core.stuffs.page_content import PageContent
from pipelex.core.stuffs.text_and_images_content import TextAndImagesContent
from pipelex.core.stuffs.text_content import TextContent
from pipelex.system.storage_scope import GENERATED_CONTENT_LEAF
from pipelex.tools.misc.base64_utils import extract_base64_str_from_base64_url_if_possible
from pipelex.tools.misc.file_fetch_utils import fetch_file_from_url_httpx
from pipelex.tools.misc.image_utils import ImageFormat
from pipelex.tools.storage.storage_provider_abstract import StorageProviderAbstract


class GeneratedContentFactory:
    def __init__(self, storage_provider: StorageProviderAbstract) -> None:
        self.storage_provider = storage_provider

    def _build_storage_key(
        self,
        storage_scope: str,
        *,
        data: bytes,
        mime_type: str,
    ) -> str:
        """Build a storage key using a SHA-256 hash of the data.

        Args:
            storage_scope: The run's opaque storage prefix — see
                `pipelex.system.storage_scope`. It replaced a
                `primary_id` / `secondary_id` pair that was always
                `(user_id, pipeline_run_id)` — WHO ran the pipe, then WHICH run.
                Collapsing them into one host-supplied string is what lets a host
                key generated content by tenant instead of by uploader, without
                the runtime learning what a tenant is.
            data: The binary data to hash
            mime_type: The resolved effective MIME type — the same value the
                resulting content reports. It alone decides the file extension,
                so the key can never disagree with the content's `mime_type`
                (a provider may return a different format than requested).

        Returns:
            `{storage_scope}/generated/<filename>`, where the filename is
            rendered from the configured `uri_format` (`{hash}`, `{extension}`).
        """
        hash_digest = hashlib.sha256(data).hexdigest()[:16]

        match mime_type:
            case "image/jpeg":
                extension = "jpg"
            case "image/png":
                extension = "png"
            case "image/webp":
                extension = "webp"
            case _:
                extension = "jpg"
        # The `generated/` leaf is HARDCODED, and `uri_format` renders only the
        # filename under it. It used to render the whole key, `{storage_scope}/…`,
        # which put generated bytes loose at the root of the scope while the
        # other two writers used a named leaf (`assets/` for what came in,
        # `results/` for what was delivered). Loose files belong to no leaf, so
        # nothing that lists a run's content by category could see them, and a
        # future leaf could collide with a file whose hash spelled its name.
        #
        # Config cannot supply the leaf, deliberately: a placeholder an operator
        # may omit is an invariant that does not hold. What `uri_format` still
        # decides is the filename — including any subdirectory under the leaf.
        uri_format = get_config().runtime.storage.uri_format
        filename = uri_format.format(hash=hash_digest, extension=extension)
        return f"{storage_scope}/{GENERATED_CONTENT_LEAF}/{filename}"

    async def _fetch_remote_content(self, url: str) -> bytes:
        return await fetch_file_from_url_httpx(url=url)

    async def make_image_content(
        self,
        storage_scope: str,
        *,
        raw_details: GeneratedImageRawDetails,
    ) -> ImageContent:
        image_format: ImageFormat | None = None
        base64_extracted_mime_type: str | None = None
        if raw_details.image_format:
            image_format = ImageFormat(raw_details.image_format)

        # Parse the raw details into either a remote URL or actual bytes,
        # extracting the mime type embedded in a base64 data-URL when present.
        remote_url: str | None = None
        actual_bytes: bytes | None = None
        if raw_details.actual_url:
            remote_url = raw_details.actual_url
        elif raw_details.base64_str:
            actual_bytes = base64.b64decode(raw_details.base64_str)
        elif raw_details.actual_url_or_prefixed_base64:
            if raw_details.actual_url_or_prefixed_base64.startswith("http"):
                remote_url = raw_details.actual_url_or_prefixed_base64
            elif result := extract_base64_str_from_base64_url_if_possible(possibly_base64_url=raw_details.actual_url_or_prefixed_base64):
                base64_str, base64_extracted_mime_type = result
                actual_bytes = base64.b64decode(base64_str)
            else:
                msg = "No URL or base64 string could be extracted"
                raise NeitherUrlNorDataError(msg)
        elif raw_details.actual_bytes:
            actual_bytes = raw_details.actual_bytes
        else:
            msg = "No URL or bytes or image found"
            raise NeitherUrlNorDataError(msg)

        # Resolve the effective mime type ONCE, before any storage key is built:
        # the provider's actual answer first (reported mime, then base64-extracted),
        # the REQUESTED image format only as a fallback. The storage-key extension
        # derives from this same resolution, so key and mime cannot diverge when a
        # provider returns a different format than requested.
        mime_type: str
        if raw_details.mime_type:
            mime_type = raw_details.mime_type
        elif base64_extracted_mime_type:
            mime_type = base64_extracted_mime_type
        elif image_format:
            mime_type = image_format.as_mime_type
        else:
            mime_type = "image/jpeg"

        is_remote_url: bool
        url: str
        if remote_url:
            url = remote_url
            is_remote_url = True
        elif actual_bytes:
            storage_key = self._build_storage_key(
                storage_scope=storage_scope,
                data=actual_bytes,
                mime_type=mime_type,
            )
            url = await self.storage_provider.store(data=actual_bytes, key=storage_key)
            is_remote_url = False
        else:
            msg = "No URL or bytes found"
            raise NeitherUrlNorDataError(msg)

        public_url: str | None
        if is_remote_url and get_config().runtime.storage.is_fetch_remote_content_enabled:
            try:
                actual_bytes = await self._fetch_remote_content(url=url)
            except (httpx.HTTPStatusError, httpx.RequestError) as exc:
                log.warning(f"Failed to fetch a remote image: {exc}")
                public_url = url
            else:
                storage_key = self._build_storage_key(
                    storage_scope=storage_scope,
                    data=actual_bytes,
                    mime_type=mime_type,
                )
                url = await self.storage_provider.store(data=actual_bytes, key=storage_key)
                public_url = await self.storage_provider.public_url(uri=url)
        elif not is_remote_url:
            public_url = await self.storage_provider.public_url(uri=url)
        else:
            public_url = url

        return ImageContent(
            url=url,
            public_url=public_url,
            width=raw_details.size.width if raw_details.size else None,
            height=raw_details.size.height if raw_details.size else None,
            mime_type=mime_type,
            caption=raw_details.caption,
        )

    async def make_page_contents(
        self,
        storage_scope: str,
        *,
        extract_output: ExtractOutput,
    ) -> list[PageContent]:
        page_contents: list[PageContent] = []
        for page_index in sorted(extract_output.pages.keys()):
            page = extract_output.pages[page_index]
            page_images: list[ImageContent] = []
            for extracted_image in page.extracted_images:
                image_content = await self.make_image_content(
                    storage_scope=storage_scope,
                    raw_details=extracted_image,
                )
                page_images.append(image_content)
            page_contents.append(
                PageContent(
                    text_and_images=TextAndImagesContent(
                        text=TextContent(text=page.text) if page.text else None,
                        images=page_images,
                        raw_html=page.raw_html,
                    ),
                )
            )
        return page_contents
