import base64
import hashlib

from pipelex import log
from pipelex.cogt.content_generation.exceptions import NeitherUrlNorDataError
from pipelex.cogt.extract.extract_output import ExtractOutput
from pipelex.cogt.image.generated_image import GeneratedImageRawDetails
from pipelex.config import get_config
from pipelex.core.stuffs.image_content import ImageContent
from pipelex.core.stuffs.page_content import PageContent
from pipelex.core.stuffs.text_and_images_content import TextAndImagesContent
from pipelex.core.stuffs.text_content import TextContent
from pipelex.system.storage_scope import GENERATED_CONTENT_LEAF
from pipelex.tools.misc.base64_utils import extract_base64_str_from_base64_url_if_possible
from pipelex.tools.misc.exceptions import RemoteFileFetchError
from pipelex.tools.misc.file_fetch_utils import fetch_file_and_content_type_from_url_httpx
from pipelex.tools.misc.image_utils import ImageFormat
from pipelex.tools.storage.storage_provider_abstract import StorageProviderAbstract


class GeneratedContentFactory:
    def __init__(self, storage_provider: StorageProviderAbstract) -> None:
        self.storage_provider = storage_provider

    def _build_storage_key(
        self,
        storage_scope: str,
        *,
        data: bytes,
        mime_type: str,
    ) -> str:
        """Build a storage key using a SHA-256 hash of the data.

        Args:
            storage_scope: The run's opaque storage prefix — see
                `pipelex.system.storage_scope`. It replaced a
                `primary_id` / `secondary_id` pair that was always
                `(user_id, pipeline_run_id)` — WHO ran the pipe, then WHICH run.
                Collapsing them into one host-supplied string is what lets a host
                key generated content by tenant instead of by uploader, without
                the runtime learning what a tenant is.
            data: The binary data to hash
            mime_type: The resolved effective MIME type — the same value the
                resulting content reports. It alone decides the file extension,
                so the key can never disagree with the content's `mime_type`
                (a provider may return a different format than requested).

        Returns:
            `{storage_scope}/generated/<filename>`, where the filename is
            rendered from the configured `uri_format` (`{hash}`, `{extension}`).
        """
        hash_digest = hashlib.sha256(data).hexdigest()[:16]

        match mime_type:
            case "image/jpeg":
                extension = "jpg"
            case "image/png":
                extension = "png"
            case "image/webp":
                extension = "webp"
            case _:
                # A media type this runtime does not itself produce can still arrive,
                # because a remote URL may serve one. The extension follows the subtype
                # so that the key keeps agreeing with the content type the object is
                # stored under; a subtype that is not a plain token (`svg+xml`) would
                # not make a filename, and falls back with the key alone imprecise.
                subtype = mime_type.removeprefix("image/")
                extension = subtype if subtype.isalnum() else "jpg"
        # The `generated/` leaf is HARDCODED, and `uri_format` renders only the
        # filename under it. It used to render the whole key, `{storage_scope}/…`,
        # which put generated bytes loose at the root of the scope while the
        # other two writers used a named leaf (`assets/` for what came in,
        # `results/` for what was delivered). Loose files belong to no leaf, so
        # nothing that lists a run's content by category could see them, and a
        # future leaf could collide with a file whose hash spelled its name.
        #
        # Config cannot supply the leaf, deliberately: a placeholder an operator
        # may omit is an invariant that does not hold. What `uri_format` still
        # decides is the filename — including any subdirectory under the leaf.
        uri_format = get_config().runtime.storage.uri_format
        filename = uri_format.format(hash=hash_digest, extension=extension)
        return f"{storage_scope}/{GENERATED_CONTENT_LEAF}/{filename}"

    async def _fetch_remote_content(self, url: str) -> tuple[bytes, str | None]:
        """Fetch the bytes at `url` and the image media type the server declared for them.

        Any `image/<subtype>` the server names is kept, not merely the three formats
        `ImageFormat` can itself produce: that enum says what this runtime generates and
        converts, which is a different question from what a remote URL is allowed to
        serve. A remote image really can be a GIF, an AVIF or a TIFF — an extract
        provider surfacing an embedded document image is the ordinary way one arrives —
        and storing such an object under `image/jpeg` because the enum does not list it
        is the confident error this whole fix exists to remove.

        What is dropped is everything that is not an image at all: the
        `application/octet-stream` of a store that never learned better, or the
        `text/html` of an error page a server dressed as a 200.
        """
        raw_bytes, media_type = await fetch_file_and_content_type_from_url_httpx(url)
        if media_type and media_type.startswith("image/"):
            return raw_bytes, media_type
        return raw_bytes, None

    async def make_image_content(
        self,
        storage_scope: str,
        *,
        raw_details: GeneratedImageRawDetails,
    ) -> ImageContent:
        image_format: ImageFormat | None = None
        base64_extracted_mime_type: str | None = None
        if raw_details.image_format:
            image_format = ImageFormat(raw_details.image_format)

        # Parse the raw details into either a remote URL or actual bytes,
        # extracting the mime type embedded in a base64 data-URL when present.
        remote_url: str | None = None
        actual_bytes: bytes | None = None
        if raw_details.actual_url:
            remote_url = raw_details.actual_url
        elif raw_details.base64_str:
            actual_bytes = base64.b64decode(raw_details.base64_str)
        elif raw_details.actual_url_or_prefixed_base64:
            if raw_details.actual_url_or_prefixed_base64.startswith("http"):
                remote_url = raw_details.actual_url_or_prefixed_base64
            elif result := extract_base64_str_from_base64_url_if_possible(possibly_base64_url=raw_details.actual_url_or_prefixed_base64):
                base64_str, base64_extracted_mime_type = result
                actual_bytes = base64.b64decode(base64_str)
            else:
                msg = "No URL or base64 string could be extracted"
                raise NeitherUrlNorDataError(msg)
        elif raw_details.actual_bytes:
            actual_bytes = raw_details.actual_bytes
        else:
            msg = "No URL or bytes or image found"
            raise NeitherUrlNorDataError(msg)

        # Resolve the effective mime type ONCE, before any storage key is built:
        # what the provider actually declared about these bytes first (its reported
        # mime, then the one a base64 data-URL carries), the REQUESTED image format
        # only as a fallback, and a hardcoded default only when nothing said anything.
        # The storage-key extension and the content type the object is stored under
        # both derive from this same resolution, so key, stored type and mime cannot
        # diverge when a provider returns a different format than requested. Passing
        # it to `store` is not optional: a store that receives no content type falls
        # back to its own default (S3 answers `binary/octet-stream`), and every
        # consumer that trusts the stored type then serves the wrong one.
        #
        # A remote URL is the one case where nothing has declared anything yet, which
        # `GeneratedImageRawDetails` permits on purpose — the type is settled when the
        # bytes are downloaded, below, from the response's own `Content-Type`. That
        # answer beats the requested format and the default, and loses to a declared
        # one: storing a fetched PNG as the `image/jpeg` somebody asked for is not a
        # smaller error than storing it untyped, it is the same error made confidently.
        declared_mime_type: str | None = raw_details.mime_type or base64_extracted_mime_type
        mime_type: str
        if declared_mime_type:
            mime_type = declared_mime_type
        elif image_format:
            mime_type = image_format.as_mime_type
        else:
            mime_type = "image/jpeg"

        is_remote_url: bool
        url: str
        if remote_url:
            url = remote_url
            is_remote_url = True
        elif actual_bytes:
            storage_key = self._build_storage_key(
                storage_scope=storage_scope,
                data=actual_bytes,
                mime_type=mime_type,
            )
            url = await self.storage_provider.store(data=actual_bytes, key=storage_key, content_type=mime_type)
            is_remote_url = False
        else:
            msg = "No URL or bytes found"
            raise NeitherUrlNorDataError(msg)

        public_url: str | None
        if is_remote_url and get_config().runtime.storage.is_fetch_remote_content_enabled:
            try:
                # `RemoteFileFetchError` is the ONLY exception this can raise: the fetch
                # helper converts every httpx failure into it. Catching the httpx classes
                # here, as this used to, caught nothing — a 404 or a timeout on a remote
                # image escaped and failed the whole pipe instead of degrading to the URL.
                actual_bytes, fetched_mime_type = await self._fetch_remote_content(url=url)
            except RemoteFileFetchError as exc:
                log.warning(f"Failed to fetch a remote image: {exc}")
                public_url = url
            else:
                if not declared_mime_type and fetched_mime_type:
                    mime_type = fetched_mime_type
                storage_key = self._build_storage_key(
                    storage_scope=storage_scope,
                    data=actual_bytes,
                    mime_type=mime_type,
                )
                url = await self.storage_provider.store(data=actual_bytes, key=storage_key, content_type=mime_type)
                public_url = await self.storage_provider.public_url(uri=url)
        elif not is_remote_url:
            public_url = await self.storage_provider.public_url(uri=url)
        else:
            public_url = url

        return ImageContent(
            url=url,
            public_url=public_url,
            width=raw_details.size.width if raw_details.size else None,
            height=raw_details.size.height if raw_details.size else None,
            mime_type=mime_type,
            caption=raw_details.caption,
        )

    async def make_page_contents(
        self,
        storage_scope: str,
        *,
        extract_output: ExtractOutput,
    ) -> list[PageContent]:
        page_contents: list[PageContent] = []
        for page_index in sorted(extract_output.pages.keys()):
            page = extract_output.pages[page_index]
            page_images: list[ImageContent] = []
            for extracted_image in page.extracted_images:
                image_content = await self.make_image_content(
                    storage_scope=storage_scope,
                    raw_details=extracted_image,
                )
                page_images.append(image_content)
            page_contents.append(
                PageContent(
                    text_and_images=TextAndImagesContent(
                        text=TextContent(text=page.text) if page.text else None,
                        images=page_images,
                        raw_html=page.raw_html,
                    ),
                )
            )
        return page_contents
