"""The structures-refusal check, shared by the CLI, the fetcher and the library loader.

The rule (execution locus decides): `.mthds` content is data, always acceptable. PipeFunc `.py`
executes in the network-blocked sandbox, acceptable on sandbox-hosted deployments. A class
subclassing `StructuredContent` would have to be imported into the runner's own process to back a
concept, so hosted execution refuses any method content that declares one, loudly, with an error
that names the rule. The discrimination is what the AST declares, never mere `.py` presence:
PipeFunc-only Python is supported.

Two doors apply it. A fetched package is scanned on disk before it is installed
(`ensure_no_structured_content_python`). Every sandbox-hosted library load, whatever the content's
origin (an inline bundle, a stored method, a host directory), scans the sources it would ship to
the sandbox before it keeps any of them (`ensure_no_structured_content_in_library_sources`). Both
run the same walk over one source string, so the two refusals cannot drift apart.

One file declaring such classes is not refused: the `python-structures` projection that
`pipelex build structures` writes, left as generated. It is a copy of the method's own MTHDS
concepts, which is exactly what the refusal asks for. A hosted load imports it no more than any other
file, and does not ship it either, since the sandbox generates its own from the same concepts. Its
stamp is not a signature, anyone can compute its hash, so the exemption is sound only because
nothing it lets through is imported into the runner; a hand-edited copy is refused.

The scan is alias-aware: a base written as `StructuredContent`, imported under another name
(`from ... import StructuredContent as SC`), or reached as an attribute
(`module.StructuredContent`, whatever the module was imported as) is caught. It remains a static
pre-check, and honestly so: dynamic tricks (rebinding through assignments, metaclass construction,
`type(...)` calls) are out of its scope. Its job is that straightforward declarations and
straightforward aliasing cannot defeat the refusal. On a sandbox-hosted load that is enough,
because the loader imports none of the customer's Python: a file that escapes the scan travels to
the sandbox as source and never executes in the runner. A subclass of a class declared elsewhere
escapes it the same way, whether its base comes from the exempt generated module or from Pipelex
itself: it is never imported here, so a concept naming it fails to resolve its structure class
instead of getting this refusal.
"""

import ast
from collections.abc import Mapping
from pathlib import Path

from pydantic import BaseModel, ConfigDict

from pipelex.codegen.stamp import compute_content_hash, parse_stamped
from pipelex.methods.exceptions import MethodStructuresRefusedError

STRUCTURE_BASE_CLASS_NAME = "StructuredContent"

STRUCTURES_REFUSAL_RULE = "hosted execution accepts MTHDS concepts and sandboxed PipeFuncs, not in-process Python"

# What every message about the rule tells the author to do, whether it refuses or only predicts a refusal.
STRUCTURES_REFUSAL_REMEDY = (
    "Declare these types as MTHDS concepts with inline structures; a PipeFunc can return them by importing the classes "
    "the sandbox generates from those concepts (`from structures import <domain>__<Concept>`). A structures module "
    "generated by `pipelex build structures` is accepted as long as it is left as generated."
)

_SKIPPED_DIR_NAMES = {".git", "__pycache__"}


def _collect_base_name_bindings(*, tree: ast.Module) -> set[str]:
    """Names bound to `StructuredContent` in this module: the literal name plus `import ... as` aliases."""
    bindings = {STRUCTURE_BASE_CLASS_NAME}
    for node in ast.walk(tree):
        if isinstance(node, ast.ImportFrom):
            for import_alias in node.names:
                if import_alias.name == STRUCTURE_BASE_CLASS_NAME and import_alias.asname:
                    bindings.add(import_alias.asname)
    return bindings


def _structured_content_class_names(*, tree: ast.Module) -> list[str]:
    """Class names in *tree* whose declared bases resolve to `StructuredContent`.

    A base matches when it is a name bound to `StructuredContent` (directly or via an
    `import ... as` alias) or an attribute access ending in `.StructuredContent` — the
    attribute form always spells the real class name, whatever the module alias.
    """
    bindings = _collect_base_name_bindings(tree=tree)
    class_names: list[str] = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.ClassDef):
            continue
        for base in node.bases:
            if isinstance(base, ast.Name) and base.id in bindings:
                class_names.append(node.name)
                break
            if isinstance(base, ast.Attribute) and base.attr == STRUCTURE_BASE_CLASS_NAME:
                class_names.append(node.name)
                break
    return class_names


class StructuredContentViolation(BaseModel):
    """One `.py` file inside a package that declares `StructuredContent` subclasses."""

    model_config = ConfigDict(frozen=True)

    relative_path: str
    class_names: list[str]


def structured_content_class_names_in_source(*, source: str, filename: str) -> list[str]:
    """Class names declared in one Python source whose bases resolve to `StructuredContent`.

    This is the one walk both refusals run, over the text itself, so the fetch-time scan of a
    directory and the load-time scan of captured sources cannot drift apart. A source that does not
    parse declares nothing: it cannot be imported either, so it cannot smuggle a structure class
    into the process. That includes a source nested deeply enough to exhaust the parser, which
    Python's own import rejects the same way.

    Args:
        source: The Python source text.
        filename: The name reported by the parser, never shown to a caller.

    Returns:
        The declared subclass names, in source order; empty when the source does not parse.
    """
    try:
        tree = ast.parse(source, filename=filename)
    except (SyntaxError, ValueError):
        return []
    except (RecursionError, MemoryError):
        # A deep attribute chain exhausts the AST builder's recursion, a deep run of unary operators
        # overflows the parser's stack ("Parser stack overflowed"): too complex to import, like a syntax error.
        return []
    return _structured_content_class_names(tree=tree)


def is_generated_structures_module(*, source: str) -> bool:
    """Whether a source is the stamped `python-structures` projection, unedited below its stamp.

    That projection is what `pipelex build structures` writes into a bundle: the method's own MTHDS
    concepts rendered as `StructuredContent` classes. The stamp's hash proves only that the body was
    not edited after stamping, not who stamped it, so this is never a trust decision: it spares an
    author who generated their types a refusal whose remedy they already applied.
    """
    parsed = parse_stamped(source, comment_prefix="#")
    if parsed is None:
        return False
    return parsed.stamp.target.is_python_structures and parsed.stamp.content_hash == compute_content_hash(parsed.body)


def _refused_class_names(*, source: str, filename: str) -> list[str]:
    """The structure classes a source would be refused for: none for the generated projection, else the walk's."""
    if is_generated_structures_module(source=source):
        return []
    return structured_content_class_names_in_source(source=source, filename=filename)


def scan_structured_content_classes(*, package_dir: Path) -> list[StructuredContentViolation]:
    """AST-scan a package directory for `.py` files declaring `StructuredContent` subclasses.

    Alias-aware: bases reached through `from ... import StructuredContent as SC` or through
    an attribute access (`module.StructuredContent`) are caught alongside the literal name.
    Files that cannot be read or parsed are skipped: such a file cannot be imported either,
    so it cannot smuggle a structure class into the process. The generated `python-structures`
    projection, left as generated, is not a violation (`is_generated_structures_module`).

    Args:
        package_dir: The package directory to scan.

    Returns:
        One violation per offending file, with the subclass names it declares.
    """
    violations: list[StructuredContentViolation] = []
    for py_file in sorted(package_dir.rglob("*.py")):
        relative = py_file.relative_to(package_dir)
        if any(part in _SKIPPED_DIR_NAMES for part in relative.parts):
            continue
        try:
            source = py_file.read_text(encoding="utf-8")
        except (OSError, ValueError):
            continue
        class_names = _refused_class_names(source=source, filename=str(py_file))
        if class_names:
            violations.append(StructuredContentViolation(relative_path=relative.as_posix(), class_names=class_names))
    return violations


def scan_structured_content_sources(*, sources: Mapping[str, str]) -> list[StructuredContentViolation]:
    """Scan captured Python sources, keyed by relative path, for `StructuredContent` subclasses.

    The sandbox-hosted loader calls this on the very mapping it would ship, so the bytes it refuses
    are exactly the bytes that would travel, with no second read of the disk. The generated
    `python-structures` projection, left as generated, is not a violation (`is_generated_structures_module`).

    Args:
        sources: POSIX relative path to source text, as `FuncRegistryUtils.read_py_sources` returns it.

    Returns:
        One violation per offending source, ordered by relative path.
    """
    violations: list[StructuredContentViolation] = []
    for relative_path in sorted(sources):
        class_names = _refused_class_names(source=sources[relative_path], filename=relative_path)
        if class_names:
            violations.append(StructuredContentViolation(relative_path=relative_path, class_names=class_names))
    return violations


def describe_structured_content_violations(*, violations: list[StructuredContentViolation]) -> str:
    """Render violations as a compact, human-readable listing."""
    return "; ".join(f"{violation.relative_path} defines {', '.join(violation.class_names)}" for violation in violations)


def ensure_no_structured_content_python(*, package_dir: Path, package_address: str) -> None:
    """Refuse a package that declares in-process Python structure classes.

    Args:
        package_dir: The package directory to check.
        package_address: The package's full address, named in the error.

    Raises:
        MethodStructuresRefusedError: If the package declares `StructuredContent` subclasses.
            The message names the rule and teaches the fix.
    """
    violations = scan_structured_content_classes(package_dir=package_dir)
    if not violations:
        return
    details = describe_structured_content_violations(violations=violations)
    msg = (
        f"Method package '{package_address}' declares Python structure classes ({details}), which would be imported "
        f"into the runner's own process. Refused: {STRUCTURES_REFUSAL_RULE}. {STRUCTURES_REFUSAL_REMEDY}"
    )
    raise MethodStructuresRefusedError(msg)


def ensure_no_structured_content_in_library_sources(*, sources_by_dir: Mapping[Path, Mapping[str, str]]) -> None:
    """Refuse a sandbox-hosted library load whose Python declares structure classes.

    Every directory is scanned before anything is raised, so one refusal names every offending file
    of the load. The message names files by their path relative to their library directory, never
    the directory itself: on a host that directory is a temporary one, which is not the caller's to read.

    Args:
        sources_by_dir: For each library directory of the load, the Python sources it would ship,
            keyed by POSIX relative path.

    Raises:
        MethodStructuresRefusedError: If any source declares a `StructuredContent` subclass.
            The message names the rule and teaches the fix.
    """
    violations: list[StructuredContentViolation] = []
    for sources in sources_by_dir.values():
        for violation in scan_structured_content_sources(sources=sources):
            # Two directories shipping the same file would otherwise be listed twice.
            if violation not in violations:
                violations.append(violation)
    if not violations:
        return
    details = describe_structured_content_violations(violations=violations)
    msg = (
        f"This method declares Python structure classes ({details}), which would be imported into the runner's "
        f"own process. Refused: {STRUCTURES_REFUSAL_RULE}. {STRUCTURES_REFUSAL_REMEDY}"
    )
    raise MethodStructuresRefusedError(msg)
