site_name: Pipelex Documentation
site_url: https://docs.pipelex.com/
site_description: "Official documentation for Pipelex, a framework and language for building deterministic, repeatable AI workflows and knowledge pipelines."
docs_dir: doc
repo_url: "https://github.com/Pipelex/pipelex"
repo_name: "Pipelex on GitHub"
watch: [README.md, CONTRIBUTING.md, CHANGELOG.md, MANIFESTO.md, LICENSE]

theme:
  name: material
  custom_dir: doc/overrides
  favicon: images/pipelex-favicon-32.png
  logo: https://pipelex-web.s3.amazonaws.com/logo/Pipelex-logo-wot-mono-560x176.png
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
  palette:
  - scheme: default          # light
    primary: teal
    accent: deep purple
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
  - scheme: slate            # dark
    primary: teal
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode

copyright: "© 2025 Evotis S.A.S. <br/>Pipelex is a trademark of Evotis S.A.S."

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Pipelex/pipelex
      name: Pipelex on GitHub
    - icon: fontawesome/brands/twitter
      link: https://x.com/PipelexAI
      name: Pipelex on X
    - icon: fontawesome/brands/discord
      link: https://discord.gg/SReshKQjWt
      name: Pipelex on Discord
  generator: false

plugins:
  - meta-manager
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      auto_caption: false
      caption_position: bottom

markdown_extensions:
  - meta
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: .
      check_paths: true

nav:
  - Home:
    - Welcome: index.md
    - Installation: pages/installation/index.md
    - Quick-start: pages/quick-start/index.md
    - Understand Pipelex:
      - The Knowledge Pipeline Manifesto: manifesto.md
      - The   Pipelex Paradigm: pages/pipelex-paradigm-for-repeatable-ai-workflows/index.md
    - Open-source:
      - Changelog: changelog.md
      - License: license.md
  - Build with Pipelex:
    - Overview: pages/how-to-build-pipelex-pipelines/index.md
    - Libraries: pages/how-to-build-pipelex-pipelines/libraries.md
    - Domains: pages/how-to-build-pipelex-pipelines/domains.md
    - Concepts: pages/how-to-build-pipelex-pipelines/concepts.md
    - Pipes: pages/how-to-build-pipelex-pipelines/pipes.md
    - Pipe Operators:
      - Overview: pages/how-to-build-pipelex-pipelines/pipe-operators/index.md
      - PipeLLM: pages/how-to-build-pipelex-pipelines/pipe-operators/PipeLLM.md
      - PipeOcr: pages/how-to-build-pipelex-pipelines/pipe-operators/PipeOcr.md
      - PipeFunc: pages/how-to-build-pipelex-pipelines/pipe-operators/PipeFunc.md
      - PipeImgGen: pages/how-to-build-pipelex-pipelines/pipe-operators/PipeImgGen.md
    - Pipe Controllers:
      - Overview: pages/how-to-build-pipelex-pipelines/pipe-controllers/index.md
      - PipeSequence: pages/how-to-build-pipelex-pipelines/pipe-controllers/PipeSequence.md
      - PipeCondition: pages/how-to-build-pipelex-pipelines/pipe-controllers/PipeCondition.md
  - Configuration:
    - Overview: pages/configuration/index.md
    - LLM Configuration: pages/configuration/llm-configuration.md
    - AWS Configuration: pages/configuration/aws-config.md
    - Cogt Configuration: pages/configuration/cogt-config.md
    - Dry Run Configuration: pages/configuration/dry-run-config.md
    - Feature Configuration: pages/configuration/feature-config.md
    - Generic Template Names: pages/configuration/generic-template-names.md
    - Library Configuration: pages/configuration/library-config.md
    - Logging Configuration: pages/configuration/logging-config.md
    - Pipe Run Configuration: pages/configuration/pipe-run-config.md
    - Plugins Configuration: pages/configuration/plugins-config.md
    - Prompting Configuration: pages/configuration/prompting-config.md
    - Reporting Configuration: pages/configuration/reporting-config.md
    - Static Validation Configuration: pages/configuration/static-validation-config.md
    - Structure Configuration: pages/configuration/structure-config.md
    - Tracker Configuration: pages/configuration/tracker-config.md
  - Dependency Injection:
    - Overview: pages/dependency-injection/index.md
    - Activity Manager: pages/dependency-injection/activity-manager-injection.md
    - Content Generator: pages/dependency-injection/content-generator-injection.md
    - Inference Manager: pages/dependency-injection/inference-manager-injection.md
    - LLM Model Provider: pages/dependency-injection/llm-model-provider-injection.md
    - Pipe Router: pages/dependency-injection/pipe-router-injection.md
    - Pipeline Tracker: pages/dependency-injection/pipeline-tracker-injection.md
    - Plugin Manager: pages/dependency-injection/plugin-manager-injection.md
    - Reporting Delegate: pages/dependency-injection/reporting-delegate-injection.md
    - Secrets Provider: pages/dependency-injection/secrets-provider-injection.md
    - Template Provider: pages/dependency-injection/template-provider-injection.md
  - Tools:
    - CLI: pages/tools/cli.md
    - Logging: pages/tools/logging.md
    - Jinja2 & Templates: pages/tools/jinja2-templating.md
  