site_name: Pipelex Documentation
site_url: https://docs.pipelex.com/
site_description: "Official documentation for Pipelex, a framework and language for building deterministic, repeatable AI workflows and knowledge pipelines."
docs_dir: docs
repo_url: "https://github.com/Pipelex/pipelex"
repo_name: "Pipelex on GitHub"
watch: [README.md, CONTRIBUTING.md, CHANGELOG.md, MANIFESTO.md, LICENSE]

theme:
  name: material
  custom_dir: docs/overrides
  favicon: images/pipelex-favicon-32.png
  logo: https://pipelex-web.s3.amazonaws.com/logo/Pipelex-logo-wot-mono-560x176.png
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
  palette:
  - scheme: default          # light
    primary: teal
    accent: deep purple
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
  - scheme: slate            # dark
    primary: teal
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode

copyright: "© 2025 Evotis S.A.S. <br/>Pipelex is a trademark of Evotis S.A.S."

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Pipelex/pipelex
      name: Pipelex on GitHub
    - icon: fontawesome/brands/twitter
      link: https://x.com/PipelexAI
      name: Pipelex on X
    - icon: fontawesome/brands/discord
      link: https://discord.gg/SReshKQjWt
      name: Pipelex on Discord
  generator: false

plugins:
  - meta-manager
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      auto_caption: false
      caption_position: bottom

markdown_extensions:
  - meta
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: .
      check_paths: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home:
    - Welcome: index.md
    - Installation: pages/installation/index.md
    - Quick-start: pages/quick-start/index.md
    - Understand Pipelex:
      - The Knowledge Pipeline Manifesto: manifesto.md
      - The Pipelex Paradigm: pages/pipelex-paradigm-for-repeatable-ai-workflows/index.md
    - Open-source:
      - Changelog: changelog.md
      - License: license.md
  - Build Reliable AI Workflows:
    - What are Domains?: pages/build-reliable-ai-workflows-with-pipelex/what-are-domains.md
    - Setup AI Pipeline Project: pages/build-reliable-ai-workflows-with-pipelex/setup-ai-pipeline-project.md
    - Define Your Concepts: pages/build-reliable-ai-workflows-with-pipelex/define_your_concepts.md
    - Design and Run Pipelines: 
      - pages/build-reliable-ai-workflows-with-pipelex/design_and_run_pipelines.md
      - Pipe Operators:
        - Overview: pages/build-reliable-ai-workflows-with-pipelex/pipe-operators/index.md
        - PipeLLM: pages/build-reliable-ai-workflows-with-pipelex/pipe-operators/PipeLLM.md
        - PipeOcr: pages/build-reliable-ai-workflows-with-pipelex/pipe-operators/PipeOcr.md
        - PipeFunc: pages/build-reliable-ai-workflows-with-pipelex/pipe-operators/PipeFunc.md
        - PipeImgGen: pages/build-reliable-ai-workflows-with-pipelex/pipe-operators/PipeImgGen.md
        - PipeJinja2: pages/build-reliable-ai-workflows-with-pipelex/pipe-operators/PipeJinja2.md
      - Pipe Controllers:
        - Overview: pages/build-reliable-ai-workflows-with-pipelex/pipe-controllers/index.md
        - PipeSequence: pages/build-reliable-ai-workflows-with-pipelex/pipe-controllers/PipeSequence.md
        - PipeCondition: pages/build-reliable-ai-workflows-with-pipelex/pipe-controllers/PipeCondition.md
        - PipeBatch: pages/build-reliable-ai-workflows-with-pipelex/pipe-controllers/PipeBatch.md
        - PipeParallel: pages/build-reliable-ai-workflows-with-pipelex/pipe-controllers/PipeParallel.md
    - Configure AI LLM to optimize workflows: pages/build-reliable-ai-workflows-with-pipelex/configure-ai-llm-to-optimize-workflows.md
    - LLM Structured Generation: pages/build-reliable-ai-workflows-with-pipelex/llm-structured-generation-config.md
    - LLM Prompting Style: pages/build-reliable-ai-workflows-with-pipelex/adapt-to-llm-prompting-style-openai-anthropic-mistral.md
    - AI Plugins for multi-LLM workflows: pages/build-reliable-ai-workflows-with-pipelex/ai-plugins-for-multi-llm-workflows.md
  - Configuration:
    - Overview: pages/configuration/index.md
    - Technical Configuration:
      - AWS Configuration: pages/configuration/config-technical/aws-config.md
      - Cogt Configuration: pages/configuration/config-technical/cogt-config.md
      - Library Configuration: pages/configuration/config-technical/library-config.md
    - Pipeline Validation:
      - Dry Run Configuration: pages/configuration/config-pipeline-validation/dry-run-config.md
      - Static Validation Configuration: pages/configuration/config-pipeline-validation/static-validation-config.md
    - Advanced Configuration:
      - Feature Configuration: pages/configuration/config-advanced/feature-config.md
    - Practical Configuration:
      - Logging Configuration: pages/configuration/config-practical/logging-config.md
      - Pipe Run Configuration: pages/configuration/config-practical/pipe-run-config.md
      - Reporting Configuration: pages/configuration/config-practical/reporting-config.md
      - Tracker Configuration: pages/configuration/config-practical/tracker-config.md
  - Advanced Customization:
    - Overview: pages/dependency-injection/index.md
    - Secrets Provider: pages/dependency-injection/secrets-provider-injection.md
    - Reporting Delegate: pages/dependency-injection/reporting-delegate-injection.md
    - Pipeline Tracker: pages/dependency-injection/pipeline-tracker-injection.md
    - Activity Manager: pages/dependency-injection/activity-manager-injection.md
    - Template Provider: pages/dependency-injection/template-provider-injection.md
    - Content Generator: pages/dependency-injection/content-generator-injection.md
    - LLM Model Provider: pages/dependency-injection/llm-model-provider-injection.md
    - Pipe Router: pages/dependency-injection/pipe-router-injection.md
    - Plugin Manager: pages/dependency-injection/plugin-manager-injection.md
    - Inference Manager: pages/dependency-injection/inference-manager-injection.md
  - Tools:
    - CLI: pages/tools/cli.md
    - Logging: pages/tools/logging.md
    - Jinja2 & Templates: pages/tools/jinja2-templating.md
  