[mypy]
check_untyped_defs = True
exclude = ^.*\.venv/.*$
mypy_path = .
packages = pipelex, tests
plugins = pydantic.mypy
python_version = 3.11
warn_return_any = True
warn_unused_configs = True

[mypy-filetype]
ignore_missing_imports = True

[mypy-json2html]
ignore_missing_imports = True

[mypy-pypdfium2]
ignore_missing_imports = True

[mypy-pypdfium2.raw]
ignore_missing_imports = True

