default_sdk = "openai"

# OpenAI Models
[gpt-4o-mini]
model_id = "pipelex/gpt-4o-mini"
inputs = ["text", "images"]
outputs = ["text", "structured"]
costs = { input = 0.17, output = 0.66 }

[gpt-image-1]
model_id = "pipelex/gpt-image-1"
inputs = ["text"]
outputs = ["images"]
costs = { input = 5, output = 0.01 }

# Anthropic Models
["claude-4-sonnet"]
model_id = "pipelex/claude-4-sonnet"
inputs = ["text", "images"]
outputs = ["text", "structured"]
costs = { input = 3, output = 15 }

# Google Models using Google API
["gemini-2.0-flash"]
model_id = "gemini/gemini-2.0-flash"
inputs = ["text", "images"]
outputs = ["text", "structured"]
costs = { input = 0.10, output = 0.40 }

["gemini-2.5-flash"]
model_id = "gemini/gemini-2.5-flash"
inputs = ["text", "images"]
outputs = ["text", "structured"]
costs = { input = 0.30, output = 2.50 }

# XAI Models
[grok-3-mini]
model_id = "grok-3-mini"
inputs = ["text"]
outputs = ["text"]
costs = { input = 0.3, output = 0.5 }

# Flux Models
[fast-lightning-sdxl]
model_id = "pipelex/fast-lightning-sdxl"
inputs = ["text"]
outputs = ["images"]
costs = { input = 0.01, output = 0.01 }

