import pytest

from pipelex import pretty_print
from pipelex.cogt.content_generation.generated_content_factory import GeneratedContentFactory
from pipelex.cogt.img_gen.img_gen_job_components import AspectRatio, Background, ImgGenJobParams, OutputFormat
from pipelex.cogt.img_gen.img_gen_job_factory import ImgGenJobFactory
from pipelex.hub import get_img_gen_worker
from pipelex.pipeline.job_metadata import JobMetadata
from tests.integration.pipelex.test_data import ImageGenTestCases


@pytest.mark.img_gen
@pytest.mark.inference
@pytest.mark.asyncio(loop_scope="class")
@pytest.mark.usefixtures("routing_profile_override")
class TestImageGeneration:
    @pytest.mark.parametrize(("topic", "img_gen_prompt_text"), ImageGenTestCases.IMAGE_DESC)
    async def test_img_gen_single_opaque(
        self,
        img_gen_handle: str,
        img_gen_job_params: ImgGenJobParams,
        topic: str,
        img_gen_prompt_text: str,
        generated_content_factory: GeneratedContentFactory,
        dummy_job_metadata: JobMetadata,
    ):
        pretty_print(f"Testing image generation with handle '{img_gen_handle}', output format '{img_gen_job_params.output_format}'")
        img_gen_worker_async = get_img_gen_worker(img_gen_handle=img_gen_handle)
        img_gen_job = ImgGenJobFactory.make_img_gen_job_from_prompt_contents(
            positive_text=img_gen_prompt_text,
            job_metadata=dummy_job_metadata,
            img_gen_job_params=img_gen_job_params,
        )
        generated_image_raw_details = await img_gen_worker_async.gen_image(
            img_gen_job=img_gen_job,
        )
        pretty_print(generated_image_raw_details, title=f"Generated image raw details for topic '{topic}'")
        generated_image_resolved = await generated_content_factory.make_generated_image(
            primary_id="primary_id",
            secondary_id="secondary_id",
            raw_details=generated_image_raw_details,
        )
        pretty_print(generated_image_resolved, title=f"Generated image resolved for topic '{topic}'")

    @pytest.mark.parametrize(("topic", "img_gen_prompt_text"), ImageGenTestCases.IMAGE_DESC)
    async def test_img_gen_single_transparent(
        self,
        img_gen_handle: str,
        topic: str,
        img_gen_prompt_text: str,
        generated_content_factory: GeneratedContentFactory,
        dummy_job_metadata: JobMetadata,
    ):
        img_gen_worker_async = get_img_gen_worker(img_gen_handle=img_gen_handle)
        img_gen_job_params = ImgGenJobParams(
            aspect_ratio=AspectRatio.SQUARE,
            is_raw=None,
            background=Background.TRANSPARENT,
            output_format=OutputFormat.PNG,
        )
        img_gen_job = ImgGenJobFactory.make_img_gen_job_from_prompt_contents(
            positive_text=img_gen_prompt_text,
            job_metadata=dummy_job_metadata,
            img_gen_job_params=img_gen_job_params,
        )
        generated_image_raw_details = await img_gen_worker_async.gen_image(
            img_gen_job=img_gen_job,
        )
        pretty_print(generated_image_raw_details, title=f"Generated image raw details for topic '{topic}'")
        generated_image_resolved = await generated_content_factory.make_generated_image(
            primary_id="primary_id",
            secondary_id="secondary_id",
            raw_details=generated_image_raw_details,
        )
        pretty_print(generated_image_resolved, title=f"Generated image resolved for topic '{topic}'")

    @pytest.mark.parametrize(("topic", "img_gen_prompt_text"), ImageGenTestCases.IMAGE_DESC)
    async def test_img_gen_multiple(
        self,
        img_gen_handle: str,
        img_gen_job_params: ImgGenJobParams,
        topic: str,
        img_gen_prompt_text: str,
        generated_content_factory: GeneratedContentFactory,
        dummy_job_metadata: JobMetadata,
    ):
        img_gen_worker_async = get_img_gen_worker(img_gen_handle=img_gen_handle)
        img_gen_job = ImgGenJobFactory.make_img_gen_job_from_prompt_contents(
            positive_text=img_gen_prompt_text,
            job_metadata=dummy_job_metadata,
            img_gen_job_params=img_gen_job_params,
        )
        generated_image_raw_details_list = await img_gen_worker_async.gen_image_list(
            img_gen_job=img_gen_job,
            nb_images=3,
        )
        pretty_print(generated_image_raw_details_list, title=f"Images generated by '{img_gen_handle}' for topic '{topic}'")
        generated_image_resolved_list = [
            (
                await generated_content_factory.make_generated_image(
                    primary_id="primary_id",
                    secondary_id="secondary_id",
                    raw_details=generated_image_raw_details,
                )
            )
            for generated_image_raw_details in generated_image_raw_details_list
        ]
        pretty_print(generated_image_resolved_list, title=f"Generated images resolved for topic '{topic}'")
