import pytest

from pipelex import pretty_print
from pipelex.cogt.img_gen.img_gen_job_components import AspectRatio, Background, ImgGenJobParams, OutputFormat
from pipelex.cogt.img_gen.img_gen_job_factory import ImgGenJobFactory
from pipelex.hub import get_img_gen_worker
from tests.helpers.image_helpers import save_generated_image
from tests.integration.pipelex.test_data import ImageGenTestCases


@pytest.mark.img_gen
@pytest.mark.inference
@pytest.mark.asyncio(loop_scope="class")
@pytest.mark.usefixtures("routing_profile_override")
class TestImageGeneration:
    @pytest.mark.parametrize(("topic", "img_gen_prompt_text"), ImageGenTestCases.IMAGE_DESC)
    async def test_img_gen_opaque(self, img_gen_handle: str, img_gen_job_params: ImgGenJobParams, topic: str, img_gen_prompt_text: str):
        img_gen_worker_async = get_img_gen_worker(img_gen_handle=img_gen_handle)
        img_gen_job = ImgGenJobFactory.make_img_gen_job_from_prompt_contents(
            positive_text=img_gen_prompt_text,
            img_gen_job_params=img_gen_job_params,
        )
        generated_image = await img_gen_worker_async.gen_image(
            img_gen_job=img_gen_job,
        )
        pretty_print(generated_image, title=f"Image generation by '{img_gen_handle}' for topic '{topic}'")

        saved_path = save_generated_image(generated_image, topic)
        if saved_path is None:
            pretty_print(generated_image.url, title="Image URL")

    @pytest.mark.parametrize(("topic", "img_gen_prompt_text"), ImageGenTestCases.IMAGE_DESC)
    async def test_img_gen_transparent(self, img_gen_handle: str, topic: str, img_gen_prompt_text: str):
        img_gen_worker_async = get_img_gen_worker(img_gen_handle=img_gen_handle)
        img_gen_job_params = ImgGenJobParams(
            aspect_ratio=AspectRatio.SQUARE,
            is_raw=False,
            background=Background.TRANSPARENT,
            output_format=OutputFormat.PNG,
        )
        img_gen_job = ImgGenJobFactory.make_img_gen_job_from_prompt_contents(
            positive_text=img_gen_prompt_text,
            img_gen_job_params=img_gen_job_params,
        )
        generated_image = await img_gen_worker_async.gen_image(
            img_gen_job=img_gen_job,
        )
        pretty_print(generated_image, title=f"Image generated by '{img_gen_handle}' for topic '{topic}'")

        save_generated_image(generated_image, topic)

    @pytest.mark.parametrize(("topic", "img_gen_prompt_text"), ImageGenTestCases.IMAGE_DESC)
    async def test_img_gen_multiple(self, img_gen_handle: str, topic: str, img_gen_prompt_text: str):
        img_gen_worker_async = get_img_gen_worker(img_gen_handle=img_gen_handle)
        img_gen_job = ImgGenJobFactory.make_img_gen_job_from_prompt_contents(
            positive_text=img_gen_prompt_text,
        )
        generated_image_list = await img_gen_worker_async.gen_image_list(
            img_gen_job=img_gen_job,
            nb_images=3,
        )
        pretty_print(generated_image_list, title=f"Images generated by '{img_gen_handle}' for topic '{topic}'")
