[pipelex.log_config]
default_log_level = "INFO"

[pipelex.log_config.package_log_levels]
pipelex = "INFO"

[cogt.llm_config]
# is_dump_text_prompts_enabled = true
# is_dump_response_text_enabled = true

[cogt.llm_config.instructor_config]
# is_dump_kwargs_enabled = true
# is_dump_response_enabled = true
# is_dump_error_enabled = true

[pipelex.observer_config]
observer_dir = "results/observer"

[pipelex.feature_config]
# WIP/Experimental feature flags
# is_pipeline_tracking_enabled = true
# is_activity_tracking_enabled = true
is_reporting_enabled = true

[telemetry]
telemetry_mode = "off" # Values: "off" | "anonymous" | "identified"
host = "https://eu.i.posthog.com"
project_api_key = "phc_HPJnNKpIXh0SxNDYyTAyUtnq9KxNNZJWQszynsWVx4Y"
respect_dnt = true
redact = [
    "prompt",
    "system_prompt",
    "response",
    "file_path",
    "url",
] # allowlist elsewhere
debug = true # if true, log events locally instead of sending
# Optional, populated only if user opts in:
user_id = "" # user-provided, not inferred
org_id = ""  # optional, user-provided
