"""Round-trip: a light default JSON template generated by ``build inputs`` feeds ``run --dry-run``.

The D11 flip is only useful if the light template it produces is actually runnable — the bug the
Date ``/review`` caught was a template that would not ``run``. Here the light template is generated
from the entry pipe's signature (``render_inputs`` with the light default), then fed straight into a
dry run of that same pipe. It must complete, and every bare value must shape to its declared concept
just as a hand-written light inputs file would.

The TOML twin of this round trip (through the real binary) lives in
``tests/e2e/pipelex/cli/test_toml_inputs_build.py``.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import TYPE_CHECKING, Any

import pytest

from pipelex.core.pipes.inputs.input_renderer import render_inputs
from pipelex.method_hub import clear_current_library, get_current_library_id_or_none, get_library_manager, get_required_pipe, set_current_library
from pipelex.pipe_run.pipe_run_mode import PipeRunMode
from pipelex.pipeline.pipeline_response import RunState
from pipelex.pipeline.runner import PipelexMTHDSProtocol
from pipelex.pipeline.validate_bundle import validate_bundle

if TYPE_CHECKING:
    from collections.abc import Callable

_FIXTURE_DIR = Path(__file__).parent / "smart_inputs_triage"
_BUNDLE = _FIXTURE_DIR / "smart_inputs_triage.mthds"


def _teardown_validation_library(outer_library_id: str) -> None:
    validation_library_id = get_current_library_id_or_none()
    if validation_library_id is not None and validation_library_id != outer_library_id:
        set_current_library(library_id=outer_library_id)
        get_library_manager().teardown(library_id=validation_library_id)
    clear_current_library()


@pytest.mark.asyncio(loop_scope="class")
class TestSmartInputsLightRoundTrip:
    async def test_generated_light_template_dry_runs(self, load_empty_library: Callable[[], str]) -> None:
        """Render the light default template, then dry-run the pipe with it — it completes and shapes correctly."""
        outer_library_id = load_empty_library()
        try:
            await validate_bundle(mthds_file_path=_BUNDLE)
            the_pipe = get_required_pipe(pipe_code="smart_inputs_demo.triage_case")
            light_inputs: dict[str, Any] = json.loads(render_inputs(the_pipe))
        finally:
            _teardown_validation_library(outer_library_id)

        # A fresh runner loads its own library from the fixture dir and shapes the generated values.
        runner = PipelexMTHDSProtocol(library_dirs=[str(_FIXTURE_DIR)], pipe_run_mode=PipeRunMode.DRY)
        response = await runner.execute(pipe_code="triage_case", inputs=light_inputs)

        assert response.state == RunState.COMPLETED
        working_memory = response.pipe_output.working_memory
        assert working_memory.get_stuff("question").concept.concept_ref == "smart_inputs_demo.Question"
        assert working_memory.get_stuff("priority").concept.concept_ref == "smart_inputs_demo.Priority"
        assert working_memory.get_stuff("invoice").concept.concept_ref == "smart_inputs_demo.Invoice"
        assert working_memory.get_stuff("tags").concept.concept_ref == "smart_inputs_demo.Tag"
