"""Tests for StructureGenerator with concept-to-concept references.

This module tests the generation of Pydantic classes that have fields
referencing other concepts (type = "concept" with concept_ref).
"""

from pipelex.core.concepts.concept_structure_blueprint import ConceptStructureBlueprint, ConceptStructureBlueprintFieldType
from pipelex.core.concepts.structure_generation.generator import StructureGenerator
from pipelex.core.stuffs.structured_content import StructuredContent


class TestStructureGeneratorConceptRefs:
    """Test StructureGenerator with concept type fields."""

    def test_single_concept_ref_field(self):
        """Test generation of a class with a single concept reference field."""
        structure_blueprint = {
            "customer": ConceptStructureBlueprint(
                description="The customer for this invoice",
                type=ConceptStructureBlueprintFieldType.CONCEPT,
                concept_ref="myapp.Customer",
                required=True,
            ),
            "total": ConceptStructureBlueprint(
                description="Invoice total",
                type=ConceptStructureBlueprintFieldType.NUMBER,
                required=True,
            ),
        }

        concept_ref_to_class_name = {
            "myapp.Customer": "Customer",
        }

        generator = StructureGenerator(concept_ref_to_class_name=concept_ref_to_class_name)
        generated_code, generated_class = generator.generate_from_structure_blueprint("Invoice", structure_blueprint)

        expected_code = '''\
"""
AUTOGENERATED CODE - DO NOT EDIT

If you want to customize this structure:
  1. Copy this file to your own module
  2. Remove the 'structure' or 'refines' declaration from the concept in the PLX file
     and declare it in inline mode (see https://docs.pipelex.com/home/6-build-reliable-ai-workflows/concepts/define_your_concepts/#basic-concept-definition)
  3. Make sure your custom class is importable and registered

To regenerate: pipelex build structures <target_directory>
"""

from enum import Enum
from pipelex.core.stuffs.structured_content import StructuredContent
from pydantic import Field
from typing import Optional, List, Dict, Any, Literal


class Invoice(StructuredContent):
    """Generated Invoice class"""

    customer: "Customer" = Field(..., description="The customer for this invoice")
    total: float = Field(..., description="Invoice total")
'''

        assert generated_code == expected_code
        assert issubclass(generated_class, StructuredContent)

    def test_list_of_concepts(self):
        """Test generation of a class with a list of concept references."""
        structure_blueprint = {
            "line_items": ConceptStructureBlueprint(
                description="List of line items",
                type=ConceptStructureBlueprintFieldType.LIST,
                item_type="concept",
                item_concept_ref="myapp.LineItem",
                required=True,
            ),
            "total": ConceptStructureBlueprint(
                description="Invoice total",
                type=ConceptStructureBlueprintFieldType.NUMBER,
                required=True,
            ),
        }

        concept_ref_to_class_name = {
            "myapp.LineItem": "LineItem",
        }

        generator = StructureGenerator(concept_ref_to_class_name=concept_ref_to_class_name)
        generated_code, generated_class = generator.generate_from_structure_blueprint("Invoice", structure_blueprint)

        expected_code = '''\
"""
AUTOGENERATED CODE - DO NOT EDIT

If you want to customize this structure:
  1. Copy this file to your own module
  2. Remove the 'structure' or 'refines' declaration from the concept in the PLX file
     and declare it in inline mode (see https://docs.pipelex.com/home/6-build-reliable-ai-workflows/concepts/define_your_concepts/#basic-concept-definition)
  3. Make sure your custom class is importable and registered

To regenerate: pipelex build structures <target_directory>
"""

from enum import Enum
from pipelex.core.stuffs.structured_content import StructuredContent
from pydantic import Field
from typing import Optional, List, Dict, Any, Literal


class Invoice(StructuredContent):
    """Generated Invoice class"""

    line_items: List["LineItem"] = Field(..., description="List of line items")
    total: float = Field(..., description="Invoice total")
'''

        assert generated_code == expected_code
        assert issubclass(generated_class, StructuredContent)

    def test_optional_concept_ref_field(self):
        """Test generation of an optional concept reference field."""
        structure_blueprint = {
            "parent": ConceptStructureBlueprint(
                description="Optional parent reference",
                type=ConceptStructureBlueprintFieldType.CONCEPT,
                concept_ref="myapp.Category",
                required=False,
            ),
            "name": ConceptStructureBlueprint(
                description="Category name",
                type=ConceptStructureBlueprintFieldType.TEXT,
                required=True,
            ),
        }

        concept_ref_to_class_name = {
            "myapp.Category": "Category",
        }

        generator = StructureGenerator(concept_ref_to_class_name=concept_ref_to_class_name)
        generated_code, generated_class = generator.generate_from_structure_blueprint("Category", structure_blueprint)

        expected_code = '''\
"""
AUTOGENERATED CODE - DO NOT EDIT

If you want to customize this structure:
  1. Copy this file to your own module
  2. Remove the 'structure' or 'refines' declaration from the concept in the PLX file
     and declare it in inline mode (see https://docs.pipelex.com/home/6-build-reliable-ai-workflows/concepts/define_your_concepts/#basic-concept-definition)
  3. Make sure your custom class is importable and registered

To regenerate: pipelex build structures <target_directory>
"""

from enum import Enum
from pipelex.core.stuffs.structured_content import StructuredContent
from pydantic import Field
from typing import Optional, List, Dict, Any, Literal


class Category(StructuredContent):
    """Generated Category class"""

    parent: Optional["Category"] = Field(default=None, description="Optional parent reference")
    name: str = Field(..., description="Category name")
'''

        assert generated_code == expected_code
        assert issubclass(generated_class, StructuredContent)

    def test_optional_list_of_concepts(self):
        """Test generation of an optional list of concept references."""
        structure_blueprint = {
            "children": ConceptStructureBlueprint(
                description="Optional child categories",
                type=ConceptStructureBlueprintFieldType.LIST,
                item_type="concept",
                item_concept_ref="myapp.Category",
                required=False,
            ),
        }

        concept_ref_to_class_name = {
            "myapp.Category": "Category",
        }

        generator = StructureGenerator(concept_ref_to_class_name=concept_ref_to_class_name)
        generated_code, generated_class = generator.generate_from_structure_blueprint("Parent", structure_blueprint)

        expected_code = '''\
"""
AUTOGENERATED CODE - DO NOT EDIT

If you want to customize this structure:
  1. Copy this file to your own module
  2. Remove the 'structure' or 'refines' declaration from the concept in the PLX file
     and declare it in inline mode (see https://docs.pipelex.com/home/6-build-reliable-ai-workflows/concepts/define_your_concepts/#basic-concept-definition)
  3. Make sure your custom class is importable and registered

To regenerate: pipelex build structures <target_directory>
"""

from enum import Enum
from pipelex.core.stuffs.structured_content import StructuredContent
from pydantic import Field
from typing import Optional, List, Dict, Any, Literal


class Parent(StructuredContent):
    """Generated Parent class"""

    children: Optional[List["Category"]] = Field(default=None, description="Optional child categories")
'''

        assert generated_code == expected_code
        assert issubclass(generated_class, StructuredContent)

    def test_cross_domain_concept_ref(self):
        """Test generation with cross-domain concept references."""
        structure_blueprint = {
            "customer": ConceptStructureBlueprint(
                description="Customer from CRM domain",
                type=ConceptStructureBlueprintFieldType.CONCEPT,
                concept_ref="crm.Customer",
                required=True,
            ),
            "products": ConceptStructureBlueprint(
                description="Products from inventory domain",
                type=ConceptStructureBlueprintFieldType.LIST,
                item_type="concept",
                item_concept_ref="inventory.Product",
                required=True,
            ),
        }

        concept_ref_to_class_name = {
            "crm.Customer": "Customer",
            "inventory.Product": "Product",
        }

        generator = StructureGenerator(concept_ref_to_class_name=concept_ref_to_class_name)
        generated_code, generated_class = generator.generate_from_structure_blueprint("Order", structure_blueprint)

        expected_code = '''\
"""
AUTOGENERATED CODE - DO NOT EDIT

If you want to customize this structure:
  1. Copy this file to your own module
  2. Remove the 'structure' or 'refines' declaration from the concept in the PLX file
     and declare it in inline mode (see https://docs.pipelex.com/home/6-build-reliable-ai-workflows/concepts/define_your_concepts/#basic-concept-definition)
  3. Make sure your custom class is importable and registered

To regenerate: pipelex build structures <target_directory>
"""

from enum import Enum
from pipelex.core.stuffs.structured_content import StructuredContent
from pydantic import Field
from typing import Optional, List, Dict, Any, Literal


class Order(StructuredContent):
    """Generated Order class"""

    customer: "Customer" = Field(..., description="Customer from CRM domain")
    products: List["Product"] = Field(..., description="Products from inventory domain")
'''

        assert generated_code == expected_code
        assert issubclass(generated_class, StructuredContent)

    def test_concept_ref_without_mapping_uses_fallback(self):
        """Test that concept_ref without mapping falls back to extracting concept code."""
        structure_blueprint = {
            "item": ConceptStructureBlueprint(
                description="An item reference",
                type=ConceptStructureBlueprintFieldType.CONCEPT,
                concept_ref="unknown_domain.SomeItem",
                required=True,
            ),
        }

        # No mapping provided - should fall back to extracting concept code
        generator = StructureGenerator()
        generated_code, generated_class = generator.generate_from_structure_blueprint("Container", structure_blueprint)

        expected_code = '''\
"""
AUTOGENERATED CODE - DO NOT EDIT

If you want to customize this structure:
  1. Copy this file to your own module
  2. Remove the 'structure' or 'refines' declaration from the concept in the PLX file
     and declare it in inline mode (see https://docs.pipelex.com/home/6-build-reliable-ai-workflows/concepts/define_your_concepts/#basic-concept-definition)
  3. Make sure your custom class is importable and registered

To regenerate: pipelex build structures <target_directory>
"""

from enum import Enum
from pipelex.core.stuffs.structured_content import StructuredContent
from pydantic import Field
from typing import Optional, List, Dict, Any, Literal


class Container(StructuredContent):
    """Generated Container class"""

    item: "SomeItem" = Field(..., description="An item reference")
'''

        assert generated_code == expected_code
        assert issubclass(generated_class, StructuredContent)

    def test_mixed_concept_and_primitive_fields(self):
        """Test generation with a mix of concept references and primitive fields."""
        structure_blueprint = {
            "id": ConceptStructureBlueprint(
                description="Unique identifier",
                type=ConceptStructureBlueprintFieldType.INTEGER,
                required=True,
            ),
            "name": ConceptStructureBlueprint(
                description="Name",
                type=ConceptStructureBlueprintFieldType.TEXT,
                required=True,
            ),
            "owner": ConceptStructureBlueprint(
                description="Owner reference",
                type=ConceptStructureBlueprintFieldType.CONCEPT,
                concept_ref="myapp.User",
                required=False,
            ),
            "tags": ConceptStructureBlueprint(
                description="Tags",
                type=ConceptStructureBlueprintFieldType.LIST,
                item_type="text",
                required=False,
            ),
            "related_items": ConceptStructureBlueprint(
                description="Related items",
                type=ConceptStructureBlueprintFieldType.LIST,
                item_type="concept",
                item_concept_ref="myapp.Item",
                required=False,
            ),
            "metadata": ConceptStructureBlueprint(
                description="Metadata",
                type=ConceptStructureBlueprintFieldType.DICT,
                key_type="text",
                value_type="text",
                required=False,
            ),
        }

        concept_ref_to_class_name = {
            "myapp.User": "User",
            "myapp.Item": "Item",
        }

        generator = StructureGenerator(concept_ref_to_class_name=concept_ref_to_class_name)
        generated_code, generated_class = generator.generate_from_structure_blueprint("ComplexEntity", structure_blueprint)

        expected_code = '''\
"""
AUTOGENERATED CODE - DO NOT EDIT

If you want to customize this structure:
  1. Copy this file to your own module
  2. Remove the 'structure' or 'refines' declaration from the concept in the PLX file
     and declare it in inline mode (see https://docs.pipelex.com/home/6-build-reliable-ai-workflows/concepts/define_your_concepts/#basic-concept-definition)
  3. Make sure your custom class is importable and registered

To regenerate: pipelex build structures <target_directory>
"""

from enum import Enum
from pipelex.core.stuffs.structured_content import StructuredContent
from pydantic import Field
from typing import Optional, List, Dict, Any, Literal


class ComplexEntity(StructuredContent):
    """Generated ComplexEntity class"""

    id: int = Field(..., description="Unique identifier")
    name: str = Field(..., description="Name")
    owner: Optional["User"] = Field(default=None, description="Owner reference")
    tags: Optional[List[str]] = Field(default=None, description="Tags")
    related_items: Optional[List["Item"]] = Field(default=None, description="Related items")
    metadata: Optional[Dict[str, str]] = Field(default=None, description="Metadata")
'''

        assert generated_code == expected_code
        assert issubclass(generated_class, StructuredContent)

    def test_native_concept_ref(self):
        """Test generation with native concept references."""
        structure_blueprint = {
            "text_content": ConceptStructureBlueprint(
                description="Text content reference",
                type=ConceptStructureBlueprintFieldType.CONCEPT,
                concept_ref="native.Text",
                required=True,
            ),
        }

        concept_ref_to_class_name = {
            "native.Text": "TextContent",
        }

        generator = StructureGenerator(concept_ref_to_class_name=concept_ref_to_class_name)
        generated_code, generated_class = generator.generate_from_structure_blueprint("Wrapper", structure_blueprint)

        expected_code = '''\
"""
AUTOGENERATED CODE - DO NOT EDIT

If you want to customize this structure:
  1. Copy this file to your own module
  2. Remove the 'structure' or 'refines' declaration from the concept in the PLX file
     and declare it in inline mode (see https://docs.pipelex.com/home/6-build-reliable-ai-workflows/concepts/define_your_concepts/#basic-concept-definition)
  3. Make sure your custom class is importable and registered

To regenerate: pipelex build structures <target_directory>
"""

from enum import Enum
from pipelex.core.stuffs.structured_content import StructuredContent
from pydantic import Field
from typing import Optional, List, Dict, Any, Literal


class Wrapper(StructuredContent):
    """Generated Wrapper class"""

    text_content: "TextContent" = Field(..., description="Text content reference")
'''

        assert generated_code == expected_code
        assert issubclass(generated_class, StructuredContent)
