"""Tests for CodeMerger utility that handles safe code regeneration."""

from pipelex.core.concepts.structure_generation.code_merger import CodeMerger


class TestCodeMerger:
    """Test code merger functionality for preserving custom code during regeneration."""

    def test_has_autogen_markers_with_markers(self):
        """Test detection of autogen markers in file content."""
        file_content = """# <AUTOGENERATED>
class Foo:
    pass
# </AUTOGENERATED>
"""
        assert CodeMerger.has_autogen_markers(file_content) is True

    def test_has_autogen_markers_without_markers(self):
        """Test detection when file has no autogen markers."""
        file_content = """class Foo:
    pass
"""
        assert CodeMerger.has_autogen_markers(file_content) is False

    def test_has_autogen_markers_partial_markers(self):
        """Test detection when file has only one marker."""
        file_content_start_only = """# <AUTOGENERATED>
class Foo:
    pass
"""
        assert CodeMerger.has_autogen_markers(file_content_start_only) is False

        file_content_end_only = """class Foo:
    pass
# </AUTOGENERATED>
"""
        assert CodeMerger.has_autogen_markers(file_content_end_only) is False

    def test_extract_custom_code_after_marker_no_markers(self):
        """Test extraction when file has no markers returns empty."""
        file_content = """class Foo:
    def custom_method(self):
        return "custom"
"""
        result = CodeMerger.extract_custom_code_after_marker(file_content)
        assert result == ""

    def test_extract_custom_code_after_marker_with_custom_section(self):
        """Test extraction of custom code after end marker."""
        file_content = """from pydantic import Field

# <AUTOGENERATED>
class Foo:
    name: str = Field(..., description="Name")
# </AUTOGENERATED>

# Custom code added by user
def custom_function():
    return "custom"

class CustomClass:
    pass
"""
        result = CodeMerger.extract_custom_code_after_marker(file_content)
        expected = """

# Custom code added by user
def custom_function():
    return "custom"

class CustomClass:
    pass
"""
        assert result == expected

    def test_extract_custom_code_after_marker_only_whitespace(self):
        """Test extraction when only whitespace exists after marker."""
        file_content = (
            '# <AUTOGENERATED>\nfrom pydantic import Field\n\n\nclass Foo:\n    name: str = Field(..., description="Name")\n# </AUTOGENERATED>\n\n'
        )
        result = CodeMerger.extract_custom_code_after_marker(file_content)
        # Should return empty when only whitespace after marker
        assert result == "" or result.strip() == ""

    def test_extract_custom_code_before_marker_no_custom_imports(self):
        """Test extraction when nothing is before the marker (new structure)."""
        file_content = (
            "# <AUTOGENERATED>\n"
            "from pydantic import Field\n"
            "from typing import Optional\n"
            "\n\n"
            "class Foo:\n"
            '    name: str = Field(..., description="Name")\n'
            "# </AUTOGENERATED>\n"
        )
        result = CodeMerger.extract_custom_code_before_marker(file_content)
        assert result == ""

    def test_extract_custom_code_before_marker_with_custom_imports(self):
        """Test extraction of custom imports before marker (new structure)."""
        file_content = (
            "# Custom imports added by user\n"
            "import re\n"
            "from mymodule import custom_validator\n"
            "\n"
            "# <AUTOGENERATED>\n"
            "from pydantic import Field\n"
            "from typing import Optional\n"
            "\n\n"
            "class Foo:\n"
            '    name: str = Field(..., description="Name")\n'
            "# </AUTOGENERATED>\n"
        )
        result = CodeMerger.extract_custom_code_before_marker(file_content)
        # Should contain custom imports
        assert "import re" in result
        assert "from mymodule import custom_validator" in result
        # Should contain the comment
        assert "# Custom imports added by user" in result

    def test_merge_first_generation_no_existing_file(self):
        """Test merge when there's no existing file (first generation)."""
        new_code = (
            "# <AUTOGENERATED>\n"
            "# The code between <AUTOGENERATED> and </AUTOGENERATED> is automatically generated.\n"
            "# Any changes between those tags will be overwritten on regeneration.\n"
            "# To regenerate, use: pipelex build structures <library_dir>\n"
            "# You can add custom code above <AUTOGENERATED> or below </AUTOGENERATED>.\n"
            "from pydantic import Field\n"
            "\n\n"
            "class Person:\n"
            '    name: str = Field(..., description="Name")\n'
            "# </AUTOGENERATED>\n"
        )
        # When there's no existing file, return new code as-is
        result = CodeMerger.merge_with_existing(new_code, "")
        assert "# <AUTOGENERATED>" in result
        assert "# </AUTOGENERATED>" in result
        assert "class Person:" in result
        assert 'name: str = Field(..., description="Name")' in result

    def test_merge_regeneration_without_custom_code(self):
        """Test regeneration when user hasn't added any custom code."""
        existing_file = (
            "# <AUTOGENERATED>\n"
            "# The code between <AUTOGENERATED> and </AUTOGENERATED> is automatically generated.\n"
            "# Any changes between those tags will be overwritten on regeneration.\n"
            "from pydantic import Field\n"
            "\n\n"
            "class Person:\n"
            '    name: str = Field(..., description="Name")\n'
            "# </AUTOGENERATED>\n"
            "\n"
            "# You can add custom imports above <AUTOGENERATED> and custom code below </AUTOGENERATED>.\n"
            "# These sections will be preserved during regeneration.\n"
        )

        new_generated = (
            "# <AUTOGENERATED>\n"
            "# The code between <AUTOGENERATED> and </AUTOGENERATED> is automatically generated.\n"
            "# Any changes between those tags will be overwritten on regeneration.\n"
            "from pydantic import Field\n"
            "\n\n"
            "class Person:\n"
            '    name: str = Field(..., description="Name")\n'
            '    age: int = Field(..., description="Age")\n'
            "# </AUTOGENERATED>\n"
            "\n"
            "# You can add custom imports above <AUTOGENERATED> and custom code below </AUTOGENERATED>.\n"
            "# These sections will be preserved during regeneration.\n"
        )

        result = CodeMerger.merge_with_existing(new_generated, existing_file)

        # Should contain new generated section with age field
        assert "age: int" in result
        # Should have markers
        assert "# <AUTOGENERATED>" in result
        assert "# </AUTOGENERATED>" in result

    def test_merge_regeneration_with_custom_code(self):
        """Test regeneration preserves user's custom code."""
        existing_file = (
            "# <AUTOGENERATED>\n"
            "# The code between <AUTOGENERATED> and </AUTOGENERATED> is automatically generated.\n"
            "# Any changes between those tags will be overwritten on regeneration.\n"
            "from pydantic import Field\n"
            "\n\n"
            "class Person:\n"
            '    name: str = Field(..., description="Name")\n'
            "# </AUTOGENERATED>\n"
            "\n"
            "# Custom validation method added by user\n"
            "def validate_person(person):\n"
            '    return person.name != ""\n'
            "\n"
            "class PersonValidator:\n"
            "    def is_valid(self, person):\n"
            "        return validate_person(person)\n"
        )

        new_generated = (
            "# <AUTOGENERATED>\n"
            "# The code between <AUTOGENERATED> and </AUTOGENERATED> is automatically generated.\n"
            "# Any changes between those tags will be overwritten on regeneration.\n"
            "from pydantic import Field\n"
            "\n\n"
            "class Person:\n"
            '    name: str = Field(..., description="Name")\n'
            '    age: int = Field(..., description="Age")\n'
            '    email: str = Field(..., description="Email")\n'
            "# </AUTOGENERATED>\n"
            "\n"
            "# You can add custom imports above <AUTOGENERATED> and custom code below </AUTOGENERATED>.\n"
            "# These sections will be preserved during regeneration.\n"
        )

        result = CodeMerger.merge_with_existing(new_generated, existing_file)

        # Should contain new generated fields
        assert "age: int" in result
        assert "email: str" in result

        # Should preserve custom code
        assert "def validate_person(person):" in result
        assert "class PersonValidator:" in result

        # Should have markers
        assert "# <AUTOGENERATED>" in result
        assert "# </AUTOGENERATED>" in result

        # Custom code should come after end marker
        autogen_end_idx = result.index("# </AUTOGENERATED>")
        validate_idx = result.index("def validate_person")
        assert validate_idx > autogen_end_idx

    def test_merge_regeneration_user_modified_generated_section(self):
        """Test that user modifications in autogenerated section are overwritten."""
        existing_file = (
            "# <AUTOGENERATED>\n"
            "# The code between <AUTOGENERATED> and </AUTOGENERATED> is automatically generated.\n"
            "# Any changes between those tags will be overwritten on regeneration.\n"
            "from pydantic import Field\n"
            "\n\n"
            "class Person:\n"
            '    name: str = Field(..., description="Name")\n'
            "    # User added this field in the autogenerated section (will be lost!)\n"
            '    custom_field: str = Field(..., description="This will be overwritten")\n'
            "# </AUTOGENERATED>\n"
            "\n"
            "# This custom code is safe\n"
            "def my_function():\n"
            "    pass\n"
        )

        new_generated = (
            "# <AUTOGENERATED>\n"
            "# The code between <AUTOGENERATED> and </AUTOGENERATED> is automatically generated.\n"
            "# Any changes between those tags will be overwritten on regeneration.\n"
            "from pydantic import Field\n"
            "\n\n"
            "class Person:\n"
            '    name: str = Field(..., description="Name")\n'
            '    age: int = Field(..., description="Age")\n'
            "# </AUTOGENERATED>\n"
            "\n"
            "# You can add custom imports above <AUTOGENERATED> and custom code below </AUTOGENERATED>.\n"
            "# These sections will be preserved during regeneration.\n"
        )

        result = CodeMerger.merge_with_existing(new_generated, existing_file)

        # User's modification in autogenerated section should be gone
        assert "custom_field" not in result

        # New generated code should be present
        assert "age: int" in result

        # Custom code after marker should be preserved
        assert "def my_function():" in result

    def test_merge_with_changed_imports(self):
        """Test that import changes are reflected in regeneration."""
        existing_file = (
            "# <AUTOGENERATED>\n"
            "# The code between <AUTOGENERATED> and </AUTOGENERATED> is automatically generated.\n"
            "# Any changes between those tags will be overwritten on regeneration.\n"
            "from pydantic import Field\n"
            "\n\n"
            "class Person:\n"
            '    name: str = Field(..., description="Name")\n'
            "# </AUTOGENERATED>\n"
            "\n"
            "# You can add custom imports above <AUTOGENERATED> and custom code below </AUTOGENERATED>.\n"
            "# These sections will be preserved during regeneration.\n"
        )

        new_generated = (
            "# <AUTOGENERATED>\n"
            "# The code between <AUTOGENERATED> and </AUTOGENERATED> is automatically generated.\n"
            "# Any changes between those tags will be overwritten on regeneration.\n"
            "from datetime import datetime\n"
            "from pydantic import Field\n"
            "\n\n"
            "class Person:\n"
            '    name: str = Field(..., description="Name")\n'
            '    birthdate: datetime = Field(..., description="Birthdate")\n'
            "# </AUTOGENERATED>\n"
            "\n"
            "# You can add custom imports above <AUTOGENERATED> and custom code below </AUTOGENERATED>.\n"
            "# These sections will be preserved during regeneration.\n"
        )

        result = CodeMerger.merge_with_existing(new_generated, existing_file)

        # New imports should be present inside autogenerated section
        assert "from datetime import datetime" in result
        assert "from pydantic import Field" in result

        # New field should be present
        assert "birthdate: datetime" in result

    def test_merge_with_inheritance_change(self):
        """Test regeneration when base class changes (refines changes)."""
        existing_file = (
            "from pipelex.core.stuffs import TextContent\n"
            "from pydantic import Field\n"
            "\n"
            "# <AUTOGENERATED>\n"
            "# The code between <AUTOGENERATED> and </AUTOGENERATED> is automatically generated.\n"
            "# Any changes between those tags will be overwritten on regeneration.\n"
            "class Question(TextContent):\n"
            '    """Generated Question class"""\n'
            "\n"
            "    pass\n"
            "# </AUTOGENERATED>\n"
            "\n"
            "def validate_question(q):\n"
            "    return len(q.text) > 0\n"
        )

        new_generated = (
            "from pipelex.core.stuffs import TextContent\n"
            "from pydantic import Field\n"
            "\n"
            "# <AUTOGENERATED>\n"
            "# The code between <AUTOGENERATED> and </AUTOGENERATED> is automatically generated.\n"
            "# Any changes between those tags will be overwritten on regeneration.\n"
            "class Question(TextContent):\n"
            '    """Generated Question class"""\n'
            "\n"
            '    author: str = Field(..., description="Question author")\n'
            "# </AUTOGENERATED>\n"
            "\n"
            "# You can add custom methods, properties, and nested classes below this line.\n"
            "# This section will be preserved during regeneration.\n"
        )

        result = CodeMerger.merge_with_existing(new_generated, existing_file)

        # New field should be present
        assert "author: str" in result

        # Custom function should be preserved
        assert "def validate_question(q):" in result

    def test_merge_preserves_multiple_custom_sections(self):
        """Test that complex custom code with multiple elements is preserved."""
        existing_file = (
            "# <AUTOGENERATED>\n"
            "# The code between <AUTOGENERATED> and </AUTOGENERATED> is automatically generated.\n"
            "# Any changes between those tags will be overwritten on regeneration.\n"
            "from pydantic import Field\n"
            "\n\n"
            "class Person:\n"
            '    name: str = Field(..., description="Name")\n'
            "# </AUTOGENERATED>\n"
            "\n"
            "# Custom imports for validation\n"
            "import re\n"
            "from typing import ClassVar\n"
            "\n"
            "# Constants\n"
            'NAME_PATTERN: ClassVar[str] = r"^[A-Z][a-z]+"\n'
            "\n"
            "# Helper functions\n"
            "def validate_name(name: str) -> bool:\n"
            "    return bool(re.match(NAME_PATTERN, name))\n"
            "\n"
            "# Extension class\n"
            "class PersonExtensions:\n"
            "    @staticmethod\n"
            "    def format_name(person):\n"
            "        return person.name.upper()\n"
        )

        new_generated = (
            "# <AUTOGENERATED>\n"
            "# The code between <AUTOGENERATED> and </AUTOGENERATED> is automatically generated.\n"
            "# Any changes between those tags will be overwritten on regeneration.\n"
            "from pydantic import Field\n"
            "\n\n"
            "class Person:\n"
            '    name: str = Field(..., description="Name")\n'
            '    age: int = Field(..., description="Age")\n'
            "# </AUTOGENERATED>\n"
            "\n"
            "# You can add custom imports above <AUTOGENERATED> and custom code below </AUTOGENERATED>.\n"
            "# These sections will be preserved during regeneration.\n"
        )

        result = CodeMerger.merge_with_existing(new_generated, existing_file)

        # New generated field
        assert "age: int" in result

        # All custom elements preserved
        assert "import re" in result
        assert "from typing import ClassVar" in result
        assert "NAME_PATTERN" in result
        assert "def validate_name(name: str)" in result
        assert "class PersonExtensions:" in result
        assert "def format_name(person):" in result

    def test_merge_preserves_custom_code_before_and_after_markers(self):
        """Test that custom code both before and after markers is preserved."""
        existing_file = (
            "# Custom imports added by user\n"
            "import re\n"
            "from datetime import datetime as dt\n"
            "\n"
            "# <AUTOGENERATED>\n"
            "# The code between <AUTOGENERATED> and </AUTOGENERATED> is automatically generated.\n"
            "# Any changes between those tags will be overwritten on regeneration.\n"
            "from pydantic import Field\n"
            "from typing import Optional\n"
            "\n\n"
            "class Person:\n"
            '    """Generated Person class"""\n'
            "\n"
            '    name: str = Field(..., description="Name")\n'
            "# </AUTOGENERATED>\n"
            "\n"
            "# Custom validation\n"
            "def validate_name(name: str) -> bool:\n"
            "    return bool(re.match(r'^[A-Z]', name))\n"
        )

        new_generated = (
            "# <AUTOGENERATED>\n"
            "# The code between <AUTOGENERATED> and </AUTOGENERATED> is automatically generated.\n"
            "# Any changes between those tags will be overwritten on regeneration.\n"
            "from pydantic import Field\n"
            "from typing import Optional, List\n"
            "\n\n"
            "class Person:\n"
            '    """Generated Person class"""\n'
            "\n"
            '    name: str = Field(..., description="Name")\n'
            '    age: int = Field(..., description="Age")\n'
            '    emails: Optional[List[str]] = Field(default=None, description="Email addresses")\n'
            "# </AUTOGENERATED>\n"
            "\n"
            "# You can add custom imports above <AUTOGENERATED> and custom code below </AUTOGENERATED>.\n"
            "# These sections will be preserved during regeneration.\n"
        )

        result = CodeMerger.merge_with_existing(new_generated, existing_file)

        # Custom imports before marker should be preserved
        assert "import re" in result
        assert "from datetime import datetime as dt" in result

        # New generated fields should be present
        assert "age: int" in result
        assert "emails: Optional[List[str]]" in result

        # Custom code after marker should be preserved
        assert "def validate_name(name: str)" in result

        # Verify order: custom imports -> autogen marker -> generated code -> end marker -> custom code
        assert result.index("import re") < result.index("# <AUTOGENERATED>")
        assert result.index("# <AUTOGENERATED>") < result.index("from pydantic import Field")
        assert result.index("# </AUTOGENERATED>") < result.index("def validate_name")
