import pytest

from pipelex import pretty_print
from pipelex.core.concepts.concept_structure_blueprint import ConceptStructureBlueprint, ConceptStructureBlueprintFieldType
from pipelex.core.concepts.helpers import normalize_structure_blueprint
from pipelex.core.concepts.structure_generation.exceptions import ConceptStructureValidationError
from pipelex.core.concepts.structure_generation.generator import StructureGenerator
from pipelex.core.stuffs.structured_content import StructuredContent


class TestStructureGenerator:
    def test_simple_structure_generation(self):
        """Test generation of a simple structure with basic fields."""
        structure_blueprint = {
            "name": ConceptStructureBlueprint(description="Name field", type=ConceptStructureBlueprintFieldType.TEXT, required=True),
            "age": ConceptStructureBlueprint(description="Age field", type=ConceptStructureBlueprintFieldType.INTEGER, required=False),
            "active": ConceptStructureBlueprint(
                description="Active status",
                type=ConceptStructureBlueprintFieldType.BOOLEAN,
                required=False,
                default_value=True,
            ),
        }

        result, _ = StructureGenerator().generate_from_structure_blueprint("TestModel", structure_blueprint)

        pretty_print(structure_blueprint, title="Source Blueprint")
        pretty_print(result, title="Generated Result")

        # Check that generated code contains required elements
        assert "class TestModel(StructuredContent):" in result
        assert '    name: str = Field(..., description="Name field")' in result
        assert '    age: Optional[int] = Field(default=None, description="Age field")' in result
        assert '    active: Optional[bool] = Field(default=True, description="Active status")' in result
        # Check for autogen header
        assert "AUTOGENERATED CODE - DO NOT EDIT" in result

    def test_complex_types_generation(self):
        """Test generation with complex types like lists and dicts."""
        structure_blueprint = {
            "tags": ConceptStructureBlueprint(
                description="List of tags",
                type=ConceptStructureBlueprintFieldType.LIST,
                item_type="text",
                required=False,
            ),
            "metadata": ConceptStructureBlueprint(
                description="Metadata dictionary",
                type=ConceptStructureBlueprintFieldType.DICT,
                key_type="text",
                value_type="text",
                required=False,
            ),
            "scores": ConceptStructureBlueprint(
                description="List of scores",
                type=ConceptStructureBlueprintFieldType.LIST,
                item_type="number",
                required=True,
            ),
        }

        result, _ = StructureGenerator().generate_from_structure_blueprint("ComplexModel", structure_blueprint)

        pretty_print(structure_blueprint, title="Source Blueprint")
        pretty_print(result, title="Generated Result")

        # Check that generated code contains required elements
        assert "class ComplexModel(StructuredContent):" in result
        assert '    tags: Optional[List[str]] = Field(default=None, description="List of tags")' in result
        assert '    metadata: Optional[Dict[str, str]] = Field(default=None, description="Metadata dictionary")' in result
        assert '    scores: List[float] = Field(..., description="List of scores")' in result
        # Check for autogen header
        assert "AUTOGENERATED CODE - DO NOT EDIT" in result

    def test_choices_generation(self):
        """Test generation with inline choices (Literal type)."""
        structure_blueprint = {
            "name": ConceptStructureBlueprint(description="Product name", type=ConceptStructureBlueprintFieldType.TEXT, required=False),
            "category": ConceptStructureBlueprint(
                description="Product category", choices=["electronics", "clothing", "food", "books"], required=True
            ),
            "size": ConceptStructureBlueprint(description="Size of the product", choices=["XS", "S", "M", "L", "XL"], required=False),
        }

        result, _ = StructureGenerator().generate_from_structure_blueprint("Product", structure_blueprint)

        pretty_print(structure_blueprint, title="Source Blueprint")
        pretty_print(result, title="Generated Result")

        # Check that generated code contains required elements
        assert "class Product(StructuredContent):" in result
        assert '    name: Optional[str] = Field(default=None, description="Product name")' in result
        assert "    category: Literal['electronics', 'clothing', 'food', 'books']" in result
        assert "    size: Optional[Literal['XS', 'S', 'M', 'L', 'XL']]" in result
        # Check for autogen header
        assert "AUTOGENERATED CODE - DO NOT EDIT" in result

    def test_empty_structure(self):
        """Test generation of structure with no fields."""
        structure_blueprint: dict[str, ConceptStructureBlueprint] = {}

        result, _ = StructureGenerator().generate_from_structure_blueprint("EmptyModel", structure_blueprint)

        pretty_print(structure_blueprint, title="Source Blueprint")
        pretty_print(result, title="Generated Result")

        # Check that generated code contains required elements
        assert "class EmptyModel(StructuredContent):" in result
        assert '"""Generated EmptyModel class"""' in result
        # No pass needed when there's a docstring
        # Check for autogen header
        assert "AUTOGENERATED CODE - DO NOT EDIT" in result

    def test_concept_get_structure_method(self):
        """Test the get_structure method on Concept class."""
        structure_blueprint = {
            "title": ConceptStructureBlueprint(description="Document title", type=ConceptStructureBlueprintFieldType.TEXT, required=True),
            "page_count": ConceptStructureBlueprint(description="Number of pages", type=ConceptStructureBlueprintFieldType.INTEGER, required=False),
        }

        result, _ = StructureGenerator().generate_from_structure_blueprint("DocumentInfo", structure_blueprint)

        pretty_print(structure_blueprint, title="Source Blueprint")
        pretty_print(result, title="Generated Result")

        # Check that generated code contains required elements
        assert "class DocumentInfo(StructuredContent):" in result
        assert '    title: str = Field(..., description="Document title")' in result
        assert '    page_count: Optional[int] = Field(default=None, description="Number of pages")' in result
        # Check for autogen header
        assert "AUTOGENERATED CODE - DO NOT EDIT" in result

    def test_generate_from_blueprint_dict_function(self):
        """Test the convenience function for generating from blueprint dict."""
        structure_blueprint = {
            "value": ConceptStructureBlueprint(description="Test value", type=ConceptStructureBlueprintFieldType.TEXT, required=True),
        }

        result, _ = StructureGenerator().generate_from_structure_blueprint("ConvenienceTest", structure_blueprint)

        pretty_print(structure_blueprint, title="Source Blueprint")
        pretty_print(result, title="Generated Result")

        # Check that generated code contains required elements
        assert "class ConvenienceTest(StructuredContent):" in result
        assert '    value: str = Field(..., description="Test value")' in result
        # Check for autogen header
        assert "AUTOGENERATED CODE - DO NOT EDIT" in result

    def test_all_field_types(self):
        """Test that all field types are properly handled."""
        structure_blueprint = {
            "text_field": ConceptStructureBlueprint(description="Text field", type=ConceptStructureBlueprintFieldType.TEXT, required=False),
            "number_field": ConceptStructureBlueprint(description="Number field", type=ConceptStructureBlueprintFieldType.NUMBER, required=False),
            "integer_field": ConceptStructureBlueprint(description="Integer field", type=ConceptStructureBlueprintFieldType.INTEGER, required=False),
            "boolean_field": ConceptStructureBlueprint(description="Boolean field", type=ConceptStructureBlueprintFieldType.BOOLEAN, required=False),
            "list_field": ConceptStructureBlueprint(
                description="List field",
                type=ConceptStructureBlueprintFieldType.LIST,
                item_type="text",
                required=False,
            ),
            "dict_field": ConceptStructureBlueprint(
                description="Dict field",
                type=ConceptStructureBlueprintFieldType.DICT,
                key_type="text",
                value_type="integer",
                required=False,
            ),
        }

        result, _ = StructureGenerator().generate_from_structure_blueprint("TypeMappingTest", structure_blueprint)

        pretty_print(structure_blueprint, title="Source Blueprint")
        pretty_print(result, title="Generated Result")

        # Check that generated code contains all required field types
        assert "class TypeMappingTest(StructuredContent):" in result
        assert '    text_field: Optional[str] = Field(default=None, description="Text field")' in result
        assert '    number_field: Optional[float] = Field(default=None, description="Number field")' in result
        assert '    integer_field: Optional[int] = Field(default=None, description="Integer field")' in result
        assert '    boolean_field: Optional[bool] = Field(default=None, description="Boolean field")' in result
        assert '    list_field: Optional[List[str]] = Field(default=None, description="List field")' in result
        assert '    dict_field: Optional[Dict[str, int]] = Field(default=None, description="Dict field")' in result
        # Check for autogen header
        assert "AUTOGENERATED CODE - DO NOT EDIT" in result

    def test_required_vs_optional_fields(self):
        """Test that fields can be marked as required vs optional."""
        structure_blueprint = {
            "title": ConceptStructureBlueprint(description="Required title", type=ConceptStructureBlueprintFieldType.TEXT, required=True),
            "optional_field": ConceptStructureBlueprint(description="Optional field", type=ConceptStructureBlueprintFieldType.TEXT, required=False),
        }

        result, _ = StructureGenerator().generate_from_structure_blueprint("RequiredFieldsModel", structure_blueprint)

        pretty_print(structure_blueprint, title="Source Blueprint")
        pretty_print(result, title="Generated Result")

        # Check that generated code contains required elements
        assert "class RequiredFieldsModel(StructuredContent):" in result
        assert '    title: str = Field(..., description="Required title")' in result
        assert '    optional_field: Optional[str] = Field(default=None, description="Optional field")' in result
        # Check for autogen header
        assert "AUTOGENERATED CODE - DO NOT EDIT" in result

    def test_default_values(self):
        """Test fields with default values."""
        structure_blueprint = {
            "name": ConceptStructureBlueprint(
                description="Person name",
                type=ConceptStructureBlueprintFieldType.TEXT,
                required=False,
                default_value="Anonymous",
            ),
            "age": ConceptStructureBlueprint(
                description="Person age",
                type=ConceptStructureBlueprintFieldType.INTEGER,
                required=False,
                default_value=0,
            ),
            "active": ConceptStructureBlueprint(
                description="Is active",
                type=ConceptStructureBlueprintFieldType.BOOLEAN,
                required=False,
                default_value=True,
            ),
        }

        result, _ = StructureGenerator().generate_from_structure_blueprint("PersonWithDefaults", structure_blueprint)

        pretty_print(structure_blueprint, title="Source Blueprint")
        pretty_print(result, title="Generated Result")

        # Check that generated code contains required elements with default values
        assert "class PersonWithDefaults(StructuredContent):" in result
        assert '    name: Optional[str] = Field(default="Anonymous", description="Person name")' in result
        assert '    age: Optional[int] = Field(default=0, description="Person age")' in result
        assert '    active: Optional[bool] = Field(default=True, description="Is active")' in result
        # Check for autogen header
        assert "AUTOGENERATED CODE - DO NOT EDIT" in result

    def test_nested_list_types(self):
        """Test nested list types with different item types."""
        structure_blueprint = {
            "text_list": ConceptStructureBlueprint(
                description="List of text items",
                type=ConceptStructureBlueprintFieldType.LIST,
                item_type="text",
                required=False,
            ),
            "number_list": ConceptStructureBlueprint(
                description="List of numbers",
                type=ConceptStructureBlueprintFieldType.LIST,
                item_type="number",
                required=True,
            ),
            "integer_list": ConceptStructureBlueprint(
                description="List of integers",
                type=ConceptStructureBlueprintFieldType.LIST,
                item_type="integer",
                required=False,
            ),
        }

        result, _ = StructureGenerator().generate_from_structure_blueprint("ListTypesModel", structure_blueprint)

        pretty_print(structure_blueprint, title="Source Blueprint")
        pretty_print(result, title="Generated Result")

        # Check that generated code contains required list types
        assert "class ListTypesModel(StructuredContent):" in result
        assert '    text_list: Optional[List[str]] = Field(default=None, description="List of text items")' in result
        assert '    number_list: List[float] = Field(..., description="List of numbers")' in result
        assert '    integer_list: Optional[List[int]] = Field(default=None, description="List of integers")' in result
        # Check for autogen header
        assert "AUTOGENERATED CODE - DO NOT EDIT" in result

    def test_nested_dict_types(self):
        """Test nested dict types with different key/value combinations."""
        structure_blueprint = {
            "string_to_string": ConceptStructureBlueprint(
                description="String to string mapping",
                type=ConceptStructureBlueprintFieldType.DICT,
                key_type="text",
                value_type="text",
                required=False,
            ),
            "string_to_number": ConceptStructureBlueprint(
                description="String to number mapping",
                type=ConceptStructureBlueprintFieldType.DICT,
                key_type="text",
                value_type="number",
                required=True,
            ),
            "string_to_integer": ConceptStructureBlueprint(
                description="String to integer mapping",
                type=ConceptStructureBlueprintFieldType.DICT,
                key_type="text",
                value_type="integer",
                required=False,
            ),
        }

        result, _ = StructureGenerator().generate_from_structure_blueprint("DictTypesModel", structure_blueprint)

        pretty_print(structure_blueprint, title="Source Blueprint")
        pretty_print(result, title="Generated Result")

        # Check that generated code contains required dict types
        assert "class DictTypesModel(StructuredContent):" in result
        assert '    string_to_string: Optional[Dict[str, str]] = Field(default=None, description="String to string mapping")' in result
        assert '    string_to_number: Dict[str, float] = Field(..., description="String to number mapping")' in result
        assert '    string_to_integer: Optional[Dict[str, int]] = Field(default=None, description="String to integer mapping")' in result
        # Check for autogen header
        assert "AUTOGENERATED CODE - DO NOT EDIT" in result

    def test_mixed_complexity_structure(self):
        """Test a structure with mixed complexity - simple and complex types together."""
        structure_blueprint = {
            "id": ConceptStructureBlueprint(description="Unique identifier", type=ConceptStructureBlueprintFieldType.INTEGER, required=True),
            "name": ConceptStructureBlueprint(description="Display name", type=ConceptStructureBlueprintFieldType.TEXT, required=True),
            "tags": ConceptStructureBlueprint(
                description="Associated tags",
                type=ConceptStructureBlueprintFieldType.LIST,
                item_type="text",
                required=False,
            ),
            "metadata": ConceptStructureBlueprint(
                description="Additional metadata",
                type=ConceptStructureBlueprintFieldType.DICT,
                key_type="text",
                value_type="text",
                required=False,
            ),
            "active": ConceptStructureBlueprint(
                description="Whether item is active",
                type=ConceptStructureBlueprintFieldType.BOOLEAN,
                required=False,
                default_value=True,
            ),
            "priority": ConceptStructureBlueprint(
                description="Priority level",
                choices=["low", "medium", "high", "urgent"],
                required=False,
                default_value="medium",
            ),
        }

        result, _ = StructureGenerator().generate_from_structure_blueprint("ComplexItem", structure_blueprint)

        pretty_print(structure_blueprint, title="Source Blueprint")
        pretty_print(result, title="Generated Result")

        # Check that generated code contains all required complex elements
        assert "class ComplexItem(StructuredContent):" in result
        assert '    id: int = Field(..., description="Unique identifier")' in result
        assert '    name: str = Field(..., description="Display name")' in result
        assert '    tags: Optional[List[str]] = Field(default=None, description="Associated tags")' in result
        assert '    metadata: Optional[Dict[str, str]] = Field(default=None, description="Additional metadata")' in result
        assert '    active: Optional[bool] = Field(default=True, description="Whether item is active")' in result
        assert "priority: Optional[Literal['low', 'medium', 'high', 'urgent']]" in result
        # Check for autogen header
        assert "AUTOGENERATED CODE - DO NOT EDIT" in result

    def test_mixed_structure_blueprint_normalization(self):
        """Test that mixed structure blueprints (strings and ConceptStructureBlueprint objects) are properly normalized."""
        # Create a mixed structure blueprint similar to what would come from TOML parsing
        mixed_structure_blueprint: dict[str, str | ConceptStructureBlueprint] = {
            "name": "The name of the person",  # Simple string definition
            "age": ConceptStructureBlueprint(description="The age of the person", type=ConceptStructureBlueprintFieldType.NUMBER, required=True),
            "birthdate": ConceptStructureBlueprint(
                description="The birthdate of the person",
                type=ConceptStructureBlueprintFieldType.DATE,
                required=True,
            ),
        }

        normalized_structure = normalize_structure_blueprint(mixed_structure_blueprint)

        result, _ = StructureGenerator().generate_from_structure_blueprint("PersonInfo", normalized_structure)

        pretty_print(mixed_structure_blueprint, title="Source Mixed Blueprint")
        pretty_print(normalized_structure, title="Normalized Blueprint")
        pretty_print(result, title="Generated Result")

        # Check that generated code contains required elements including datetime
        assert "from datetime import datetime" in result
        assert "class PersonInfo(StructuredContent):" in result
        assert '    name: str = Field(..., description="The name of the person")' in result
        assert '    age: float = Field(..., description="The age of the person")' in result
        assert '    birthdate: datetime = Field(..., description="The birthdate of the person")' in result
        # Check for autogen header
        assert "AUTOGENERATED CODE - DO NOT EDIT" in result

        # Verify that the string was properly converted to ConceptStructureBlueprint
        assert isinstance(normalized_structure["name"], ConceptStructureBlueprint)
        assert normalized_structure["name"].description == "The name of the person"
        assert normalized_structure["name"].type == ConceptStructureBlueprintFieldType.TEXT
        assert normalized_structure["name"].required

    def test_code_validation_success(self):
        """Test that valid generated code passes validation."""
        structure_blueprint = {
            "name": ConceptStructureBlueprint(description="Name field", type=ConceptStructureBlueprintFieldType.TEXT, required=True),
        }

        generator = StructureGenerator()
        python_code, the_class = generator.generate_from_structure_blueprint("ValidTestModel", structure_blueprint)

        # The generation should succeed (validation happens internally)
        assert "class ValidTestModel(StructuredContent):" in python_code
        assert isinstance(the_class, type)
        assert issubclass(the_class, StructuredContent)

        # Test validation directly
        generator.validate_generated_code(python_code=python_code, expected_class_name="ValidTestModel")

    def test_code_validation_syntax_error(self):
        """Test that invalid syntax fails validation."""
        generator = StructureGenerator()
        invalid_code = """
from pydantic import Field
from pipelex.core.stuffs.structured_content import StructuredContent

class InvalidModel(StructuredContent):
    name: str = Field(..., description="Name field"  # Missing closing parenthesis
"""

        with pytest.raises(SyntaxError):
            generator.validate_generated_code(python_code=invalid_code, expected_class_name="InvalidModel")

    def test_code_validation_missing_class(self):
        """Test that code without the expected class fails validation."""
        generator = StructureGenerator()
        code_without_expected_class = """
from pydantic import Field
from pipelex.core.stuffs.structured_content import StructuredContent

class WrongClassName(StructuredContent):
    name: str = Field(..., description="Name field")
"""

        with pytest.raises(ConceptStructureValidationError):
            generator.validate_generated_code(python_code=code_without_expected_class, expected_class_name="ExpectedClassName")

    def test_inheritance_from_text_content(self):
        """Test generating a class that inherits from TextContent."""
        structure_blueprint = {
            "author": ConceptStructureBlueprint(
                description="The author of the question",
                type=ConceptStructureBlueprintFieldType.TEXT,
                required=False,
            ),
        }

        generator = StructureGenerator()
        generated_code, generated_class = generator.generate_from_structure_blueprint(
            "Question",
            structure_blueprint,
            base_class_name="TextContent",
        )

        pretty_print(structure_blueprint, title="Source Blueprint")
        pretty_print(generated_code, title="Generated Result")

        # Verify the code compiles
        import ast  # noqa: PLC0415

        ast.parse(generated_code)
        compile(generated_code, "<generated>", "exec")

        # Verify correct import is present
        assert "from pipelex.core.stuffs.text_content import TextContent" in generated_code

        # Verify class inherits from TextContent
        assert "class Question(TextContent):" in generated_code

        # Verify the generated class is valid
        from pipelex.core.stuffs.text_content import TextContent  # noqa: PLC0415

        assert issubclass(generated_class, TextContent)
        from pipelex.core.stuffs.stuff_content import StuffContent  # noqa: PLC0415

        assert issubclass(generated_class, StuffContent)

        # Test instantiation (TextContent requires 'text' field)
        instance = generated_class(text="Sample text", author="John Doe")  # pyright: ignore[reportCallIssue]
        assert instance.author == "John Doe"  # type: ignore[attr-defined]  # pyright: ignore[reportAttributeAccessIssue]

    def test_inheritance_from_image_content(self):
        """Test generating a class that inherits from ImageContent."""
        structure_blueprint = {
            "table_name": ConceptStructureBlueprint(
                description="Name of the table in the screenshot",
                type=ConceptStructureBlueprintFieldType.TEXT,
                required=False,
            ),
            "row_count": ConceptStructureBlueprint(
                description="Number of rows in the table",
                type=ConceptStructureBlueprintFieldType.INTEGER,
                required=False,
            ),
        }

        generator = StructureGenerator()
        generated_code, generated_class = generator.generate_from_structure_blueprint(
            "TableScreenshot",
            structure_blueprint,
            base_class_name="ImageContent",
        )

        pretty_print(structure_blueprint, title="Source Blueprint")
        pretty_print(generated_code, title="Generated Result")

        # Verify correct import is present
        assert "from pipelex.core.stuffs.image_content import ImageContent" in generated_code

        # Verify class inherits from ImageContent
        assert "class TableScreenshot(ImageContent):" in generated_code

        # Verify the generated class is valid
        from pipelex.core.stuffs.image_content import ImageContent  # noqa: PLC0415

        assert issubclass(generated_class, ImageContent)
        from pipelex.core.stuffs.stuff_content import StuffContent  # noqa: PLC0415

        assert issubclass(generated_class, StuffContent)

    def test_inheritance_from_number_content(self):
        """Test generating a class that inherits from NumberContent."""
        structure_blueprint = {
            "unit": ConceptStructureBlueprint(
                description="Unit of measurement",
                type=ConceptStructureBlueprintFieldType.TEXT,
                required=False,
            ),
        }

        generator = StructureGenerator()
        generated_code, generated_class = generator.generate_from_structure_blueprint(
            "Temperature",
            structure_blueprint,
            base_class_name="NumberContent",
        )

        # Verify correct import is present
        assert "from pipelex.core.stuffs.number_content import NumberContent" in generated_code

        # Verify class inherits from NumberContent
        assert "class Temperature(NumberContent):" in generated_code

        # Verify the generated class is valid
        from pipelex.core.stuffs.number_content import NumberContent  # noqa: PLC0415

        assert issubclass(generated_class, NumberContent)
        from pipelex.core.stuffs.stuff_content import StuffContent  # noqa: PLC0415

        assert issubclass(generated_class, StuffContent)

    def test_inheritance_from_json_content(self):
        """Test generating a class that inherits from JSONContent."""
        structure_blueprint = {
            "schema_version": ConceptStructureBlueprint(
                description="Version of the schema",
                type=ConceptStructureBlueprintFieldType.TEXT,
                required=False,
            ),
        }

        generator = StructureGenerator()
        generated_code, generated_class = generator.generate_from_structure_blueprint(
            "ConfigData",
            structure_blueprint,
            base_class_name="JSONContent",
        )

        # Verify correct import is present
        assert "from pipelex.core.stuffs.json_content import JSONContent" in generated_code

        # Verify class inherits from JSONContent
        assert "class ConfigData(JSONContent):" in generated_code

        # Verify the generated class is valid
        from pipelex.core.stuffs.json_content import JSONContent  # noqa: PLC0415

        assert issubclass(generated_class, JSONContent)
        from pipelex.core.stuffs.stuff_content import StuffContent  # noqa: PLC0415

        assert issubclass(generated_class, StuffContent)

    def test_inheritance_with_empty_structure(self):
        """Test generating a class with no additional fields that just inherits from a base class."""
        structure_blueprint: dict[str, ConceptStructureBlueprint] = {}

        generator = StructureGenerator()
        generated_code, generated_class = generator.generate_from_structure_blueprint(
            "EnhancedText",
            structure_blueprint,
            base_class_name="TextContent",
        )

        pretty_print(generated_code, title="Generated Result with Empty Structure")

        # Verify correct import is present
        assert "from pipelex.core.stuffs.text_content import TextContent" in generated_code

        # Verify class inherits from TextContent
        assert "class EnhancedText(TextContent):" in generated_code

        # Verify it has docstring (no pass needed)
        assert '"""Generated EnhancedText class"""' in generated_code

        # Verify the generated class is valid
        from pipelex.core.stuffs.text_content import TextContent  # noqa: PLC0415

        assert issubclass(generated_class, TextContent)
        from pipelex.core.stuffs.stuff_content import StuffContent  # noqa: PLC0415

        assert issubclass(generated_class, StuffContent)

        # Test instantiation works (TextContent requires 'text' field)
        instance = generated_class(text="Sample text")  # pyright: ignore[reportCallIssue]
        assert instance is not None

    def test_inheritance_from_pdf_content(self):
        """Test generating a class that inherits from PDFContent."""
        structure_blueprint = {
            "document_type": ConceptStructureBlueprint(
                description="Type of PDF document",
                type=ConceptStructureBlueprintFieldType.TEXT,
                required=False,
            ),
        }

        generator = StructureGenerator()
        generated_code, generated_class = generator.generate_from_structure_blueprint(
            "Invoice",
            structure_blueprint,
            base_class_name="PDFContent",
        )

        # Verify correct import is present
        assert "from pipelex.core.stuffs.pdf_content import PDFContent" in generated_code

        # Verify class inherits from PDFContent
        assert "class Invoice(PDFContent):" in generated_code

        # Verify the generated class is valid
        from pipelex.core.stuffs.pdf_content import PDFContent  # noqa: PLC0415

        assert issubclass(generated_class, PDFContent)
        from pipelex.core.stuffs.stuff_content import StuffContent  # noqa: PLC0415

        assert issubclass(generated_class, StuffContent)

    def test_multiple_inheritance_scenarios(self):
        """Test multiple classes with different inheritance scenarios."""
        from pipelex.core.stuffs.stuff_content import StuffContent  # noqa: PLC0415

        test_cases = [
            ("TextContent", "text_content", "Question", {"source": "The source of the question"}),
            ("ImageContent", "image_content", "Diagram", {"diagram_type": "Type of diagram"}),
            ("NumberContent", "number_content", "Score", {"max_value": "Maximum possible score"}),
        ]

        for base_class_name, module_name, class_name, field_dict in test_cases:
            structure_blueprint = {
                field_name: ConceptStructureBlueprint(
                    description=description,
                    type=ConceptStructureBlueprintFieldType.TEXT,
                    required=False,
                )
                for field_name, description in field_dict.items()
            }

            generator = StructureGenerator()
            generated_code, generated_class = generator.generate_from_structure_blueprint(
                class_name,
                structure_blueprint,
                base_class_name=base_class_name,
            )

            # Verify correct import is present
            assert f"from pipelex.core.stuffs.{module_name} import {base_class_name}" in generated_code

            # Verify class inherits from correct base
            assert f"class {class_name}({base_class_name}):" in generated_code

            # Verify it's a valid subclass of StuffContent
            assert issubclass(generated_class, StuffContent)
