from typing import Callable

import pytest

from pipelex import pretty_print
from pipelex.core.concepts.native.concept_native import NativeConceptCode
from pipelex.core.pipes.pipe_factory import PipeFactory
from pipelex.hub import get_pipe_router
from pipelex.pipe_operators.img_gen.pipe_img_gen import PipeImgGen
from pipelex.pipe_operators.img_gen.pipe_img_gen_blueprint import PipeImgGenBlueprint
from pipelex.pipe_run.pipe_job_factory import PipeJobFactory
from pipelex.pipe_run.pipe_run_params import PipeRunMode
from pipelex.pipe_run.pipe_run_params_factory import PipeRunParamsFactory
from tests.integration.pipelex.test_data import ImageGenTestCases


@pytest.mark.dry_runnable
@pytest.mark.img_gen
@pytest.mark.inference
@pytest.mark.asyncio(loop_scope="class")
class TestPipeImgGenRun:
    @pytest.mark.parametrize(("topic", "image_desc"), ImageGenTestCases.IMAGE_DESC)
    async def test_pipe_img_gen_run(
        self,
        pipe_run_mode: PipeRunMode,
        img_gen_handle: str,
        topic: str,
        image_desc: str,
        load_empty_library: Callable[[], None],
    ):
        load_empty_library()
        pipe_img_gen_blueprint = PipeImgGenBlueprint(
            description="Image generation test",
            img_gen_prompt=image_desc,
            model=img_gen_handle,
            output=NativeConceptCode.IMAGE,
        )

        pipe_job = PipeJobFactory.make_pipe_job(
            pipe=PipeFactory[PipeImgGen].make_from_blueprint(
                domain_code="generic",
                pipe_code="adhoc_for_test_pipe_img_gen",
                blueprint=pipe_img_gen_blueprint,
            ),
            pipe_run_params=PipeRunParamsFactory.make_run_params(pipe_run_mode=pipe_run_mode),
        )
        pipe_output = await get_pipe_router().run(
            pipe_job=pipe_job,
        )
        image = pipe_output.main_stuff_as_image

        pretty_print(image, title=f"Image generated by '{img_gen_handle}' for topic '{topic}'")
