####################################################################################################
# Pipelex Model Deck - Custom Configurations for Document Extraction Models
####################################################################################################
#
# This file allows you to override or complete the base model decks.
#
# Documentation: https://docs.pipelex.com
# Support: https://go.pipelex.com/discord
#
####################################################################################################


####################################################################################################
# Waterfalls — lists of models that will be tried in order until one of them is available
####################################################################################################

[extract.waterfalls]

document_extractor = ["azure-document-intelligence", "mistral-document-ai-2505"]
pdf_text_extractor = [
    "azure-document-intelligence",
    "mistral-document-ai-2505",
    "pypdfium2-extract-pdf",
]
image_text_extractor = [
    "azure-document-intelligence",
    "mistral-document-ai-2505",
]
