from unittest.mock import Mock, patch

from pipelex.core.pipe_input_spec import PipeInputSpec
from pipelex.pipe_controllers.pipe_sequence import PipeSequence
from pipelex.pipe_controllers.sub_pipe import SubPipe


class TestPipeSequenceValidation:
    """Tests for PipeSequence validate_inputs method"""

    def test_pipe_sequence_validate_inputs_basic(self):
        """Test basic input validation for a simple PipeSequence"""
        # Create a simple PipeSequence with proper inputs
        pipe_sequence = PipeSequence(
            domain="test_domain",
            code="test_sequence",
            inputs=PipeInputSpec(root={"text": "test_domain.Text"}),
            output_concept_code="test_domain.ProcessedText",
            sequential_sub_pipes=[SubPipe(pipe_code="test_pipe_1", output_name="intermediate_result")],
        )

        # The validate_inputs method should run without error
        # since it's called during model validation
        assert pipe_sequence.code == "test_sequence"
        assert pipe_sequence.domain == "test_domain"
        assert len(pipe_sequence.sequential_sub_pipes) == 1

    def test_pipe_sequence_needed_inputs_calculation(self):
        """Test that needed_inputs correctly calculates required inputs minus generated outputs"""
        # This is a simplified test that demonstrates the concept
        # In practice, this would require actual pipes to be loaded
        pipe_sequence = PipeSequence(
            domain="test_domain",
            code="test_sequence",
            inputs=PipeInputSpec(root={"initial_input": "test_domain.Text"}),
            output_concept_code="test_domain.FinalOutput",
            sequential_sub_pipes=[SubPipe(pipe_code="step_1", output_name="step_1_output"), SubPipe(pipe_code="step_2", output_name="step_2_output")],
        )

        # Test that the pipe sequence is created successfully
        assert pipe_sequence.code == "test_sequence"
        assert len(pipe_sequence.sequential_sub_pipes) == 2

        # The actual needed_inputs testing would require mocking the pipes
        # For now, we just verify the structure is correct
        assert pipe_sequence.inputs.root["initial_input"] == "test_domain.Text"

    @patch("pipelex.pipe_controllers.pipe_sequence.get_required_pipe")
    def test_pipe_sequence_needed_inputs_with_mocked_pipes(self, mock_get_pipe: Mock):
        """Test needed_inputs calculation with mocked pipe dependencies"""

        # Set up the mock to return different pipes based on pipe_code
        def mock_get_pipe_side_effect(pipe_code: str):
            if pipe_code == "step_1":
                # Mock pipe that needs "initial_input"
                mock_pipe = Mock()
                mock_pipe.inputs = PipeInputSpec(root={"initial_input": "test_domain.Text"})
                # Remove needed_inputs so hasattr returns False and it uses .inputs
                del mock_pipe.needed_inputs
                return mock_pipe
            elif pipe_code == "step_2":
                # Mock pipe that needs "intermediate"
                mock_pipe = Mock()
                mock_pipe.inputs = PipeInputSpec(root={"intermediate": "test_domain.Intermediate"})
                del mock_pipe.needed_inputs
                return mock_pipe
            else:
                raise Exception(f"Unknown pipe: {pipe_code}")

        mock_get_pipe.side_effect = mock_get_pipe_side_effect

        # Create PipeSequence
        pipe_sequence = PipeSequence(
            domain="test_domain",
            code="test_sequence",
            inputs=PipeInputSpec(root={"initial_input": "test_domain.Text"}),
            output_concept_code="test_domain.FinalOutput",
            sequential_sub_pipes=[SubPipe(pipe_code="step_1", output_name="intermediate"), SubPipe(pipe_code="step_2", output_name="final_output")],
        )

        # Test needed_inputs calculation
        needed_inputs = pipe_sequence.needed_inputs()

        # Should only need "initial_input" since "intermediate" is generated by step_1
        assert "initial_input" in needed_inputs.root
        assert "intermediate" not in needed_inputs.root
        assert len(needed_inputs.root) == 1
