"""Utilities for merging generated code with user customizations."""


class CodeMerger:
    """Handles merging of auto-generated code with user customizations."""

    AUTOGEN_START_MARKER = "# <AUTOGENERATED>"
    AUTOGEN_END_MARKER = "# </AUTOGENERATED>"

    @classmethod
    def merge_with_existing(cls, new_generated_code: str, existing_file_content: str) -> str:
        """Merge new generated code with existing file, preserving custom sections.

        Structure:
        - Custom imports/code (BEFORE <AUTOGENERATED>)
        - <AUTOGENERATED> marker
        - Auto-generated imports + class definition
        - </AUTOGENERATED> marker
        - Custom methods/classes (AFTER </AUTOGENERATED>)

        Args:
            new_generated_code: Newly generated code with markers
            existing_file_content: Content of existing file (may have custom code)

        Returns:
            Merged code with new generated sections and preserved custom sections

        """
        # Extract custom code sections from existing file
        custom_code_before = cls.extract_custom_code_before_marker(existing_file_content)
        custom_code_after = cls.extract_custom_code_after_marker(existing_file_content)

        # Extract the complete autogenerated section from new code (with markers)
        new_code_parts = new_generated_code.split(cls.AUTOGEN_START_MARKER, 1)
        if len(new_code_parts) != 2:
            # No markers in new code, return as-is
            return new_generated_code

        new_autogen_parts = new_code_parts[1].split(cls.AUTOGEN_END_MARKER, 1)
        if len(new_autogen_parts) != 2:
            # Malformed markers, return as-is
            return new_generated_code

        # Build the complete autogenerated section (with markers)
        autogen_section = cls.AUTOGEN_START_MARKER + new_autogen_parts[0] + cls.AUTOGEN_END_MARKER

        # Assemble final code: custom_before + autogen + custom_after
        result_parts: list[str] = []

        if custom_code_before.strip():
            result_parts.append(custom_code_before.rstrip())
            result_parts.append("")  # Blank line before marker

        result_parts.append(autogen_section)

        if custom_code_after.strip():
            # DO NOT use lstrip() - it would remove indentation!
            # DO NOT add blank line - custom_code_after already has its own spacing
            # Just append directly to avoid accumulating blank lines on each regeneration
            return "\n".join(result_parts) + custom_code_after

        return "\n".join(result_parts)

    @classmethod
    def extract_custom_code_before_marker(cls, file_content: str) -> str:
        """Extract custom code/imports before <AUTOGENERATED> marker.

        With the new structure, <AUTOGENERATED> is at the very beginning,
        so everything BEFORE it is custom user code.

        Args:
            file_content: Content of the existing file

        Returns:
            Custom code/imports section (everything before <AUTOGENERATED>)

        """
        if cls.AUTOGEN_START_MARKER not in file_content:
            # No markers, no custom code to extract
            return ""

        # Split by start marker and get everything before it
        parts = file_content.split(cls.AUTOGEN_START_MARKER, 1)
        if len(parts) != 2:
            return ""

        # Everything before the marker is custom code
        custom_before = parts[0].rstrip()

        # If it's only whitespace, return empty
        if not custom_before.strip():
            return ""

        return custom_before

    @classmethod
    def extract_custom_code_after_marker(cls, file_content: str) -> str:
        """Extract custom code section after </AUTOGENERATED> marker.

        Args:
            file_content: Content of the existing file

        Returns:
            Custom code section (everything after </AUTOGENERATED> marker)

        """
        if cls.AUTOGEN_END_MARKER not in file_content:
            # No markers, assume entire file is custom
            return ""

        # Split by end marker and return everything after it
        parts = file_content.split(cls.AUTOGEN_END_MARKER, 1)
        if len(parts) == 2:
            custom_section = parts[1]
            # Return custom section if it has content (whitespace-only means no custom code)
            if custom_section.strip():
                return custom_section
            return ""

        return ""

    @classmethod
    def has_autogen_markers(cls, file_content: str) -> bool:
        """Check if file has autogeneration markers.

        Args:
            file_content: Content of the file to check

        Returns:
            True if file has both start and end markers

        """
        return cls.AUTOGEN_START_MARKER in file_content and cls.AUTOGEN_END_MARKER in file_content
