import ast
import textwrap
from datetime import date, datetime, time
from enum import Enum
from typing import Any, List, Literal, Optional, cast

from kajson.class_registry_abstract import ClassRegistryAbstract
from pydantic import Field

from pipelex.codegen.resolved_fields import ResolvedField, ResolvedType, ResolvedTypeKind, resolve_structure_fields
from pipelex.core.concepts.concept_structure_blueprint import ConceptStructureBlueprint
from pipelex.core.concepts.helpers import extract_concept_code_from_concept_ref_or_code, make_qualified_structure_class_name
from pipelex.core.concepts.native.concept_native import NativeConceptCode
from pipelex.core.concepts.structure_generation.exceptions import ConceptStructureGeneratorError, ConceptStructureValidationError, SyntaxErrorData
from pipelex.core.qualified_ref import QualifiedRef
from pipelex.core.stuffs.stuff_content import StuffContent

# Target line length for emitted code (matches the project's ruff config).
# Each emitted line stays under this so ruff E501 doesn't trigger on long descriptions.
_MAX_LINE_LENGTH = 150
_WRAP_WIDTH = 120  # conservative: leaves headroom for indentation and syntax overhead


def _get_class_registry() -> ClassRegistryAbstract:
    """Lazy import to break circular dependency with hub.py."""
    import importlib  # noqa: PLC0415

    hub = importlib.import_module("pipelex.hub")
    return hub.get_class_registry()  # type: ignore[no-any-return]


class StructureGenerator:
    """Generate Pydantic BaseModel classes from concept structure blueprints."""

    def __init__(self, local_domain: str | None = None):
        """Initialize the StructureGenerator.

        Args:
            local_domain: Optional domain to use when resolving bare concept refs
                (refs without a domain prefix, e.g. "ColorPalette") to their
                domain-qualified structure class name.
        """
        self.imports = {
            "from typing import Optional, List, Dict, Any, Literal",
            "from enum import Enum",
            "from pipelex.core.stuffs.structured_content import StructuredContent",
            "from pydantic import Field",
        }
        self.local_domain = local_domain

    def generate_from_structure_blueprint(
        self,
        *,
        class_name: str,
        structure_blueprint: dict[str, ConceptStructureBlueprint],
        base_class_name: str | None = None,
        description: str = "",
    ) -> tuple[str, type]:
        """Generate Python module content from structure blueprint.

        Args:
            class_name: Name of the class to generate
            structure_blueprint: Dictionary mapping field names to their ConceptStructureBlueprint definitions
            base_class_name: Optional base class name to inherit from (defaults to StructuredContent)
            description: Description for the class docstring (uses class_name if empty)

        Returns:
            Generated Python module content, the generated class

        Raises:
            ConceptStructureGeneratorError: If the generated code is not syntactically correct or does not inherit from the required base class

        """
        # Generate the class
        class_code = self._generate_class_source_code_from_blueprint(
            class_name=class_name, structure_blueprint=structure_blueprint, base_class_name=base_class_name, description=description
        )

        # Generate the complete module with a header comment
        imports_section = "\n".join(sorted(self.imports))

        autogen_header = (
            '"""\n'
            "AUTOGENERATED CODE - DO NOT EDIT\n"
            "\n"
            "If you want to customize this structure:\n"
            "  1. Copy this file to your own module\n"
            "  2. Remove the 'structure' or 'refines' declaration from the concept in the MTHDS file\n"
            "     and declare it in inline mode (see https://docs.pipelex.com/latest/building-methods/concepts/define_your_concepts/#basic-concept-definition)\n"
            "  3. Make sure your custom class is importable and registered\n"
            "\n"
            "To regenerate: pipelex build structures <target_directory>\n"
            '"""\n\n'
        )

        generated_code = f"{autogen_header}{imports_section}\n\n\n{class_code}\n"

        # Validate the generated code
        try:
            the_class = self.validate_generated_code(
                python_code=generated_code,
                expected_class_name=class_name,
                base_class_name=base_class_name,
            )
        except SyntaxError as syntax_error:
            msg = f"Error validating generated code: {syntax_error}"
            syntax_error_data = SyntaxErrorData.from_syntax_error(syntax_error)
            raise ConceptStructureGeneratorError(
                msg, structure_class_python_code=generated_code, syntax_error_data=syntax_error_data
            ) from syntax_error
        except (ConceptStructureValidationError, ValueError, ImportError, Exception) as exc:
            msg = f"Error validating generated code: {exc}\nGenerated code:\n```python\n{generated_code}\n```"
            raise ConceptStructureGeneratorError(msg, structure_class_python_code=generated_code) from exc

        return generated_code, the_class

    def validate_generated_code(
        self,
        python_code: str,
        *,
        expected_class_name: str,
        base_class_name: str | None = None,
    ) -> type:
        """Validate that the generated Python code is syntactically correct and executable.

        Args:
            python_code: The generated Python code to validate
            expected_class_name: The name of the class that should be created
            base_class_name: Optional name of a custom base class to use

        """
        ast.parse(python_code)

        compile(python_code, "<generated>", "exec")

        return self._validate_execution(
            python_code=python_code,
            expected_class_name=expected_class_name,
            base_class_name=base_class_name,
        )

    ############################################################
    # Private methods
    ############################################################

    def _escape_string_for_python(self, value: str) -> str:
        """Escape a string value for safe inclusion in generated Python code.

        This method ensures that strings containing special characters like quotes,
        backslashes, newlines, etc. are properly escaped when inserted into generated
        Python source code.

        Args:
            value: The string to escape

        Returns:
            A properly escaped string representation suitable for Python code with double quotes
        """
        # Use repr() which handles all escaping correctly (backslashes, newlines, quotes, etc.)
        # repr() returns a string with surrounding quotes included
        escaped = repr(value)

        # If repr used single quotes, convert to double quotes
        # This is for consistency with existing code expectations
        if escaped.startswith("'") and escaped.endswith("'") and not escaped.startswith("'''"):
            # Single-line string with single quotes
            # Remove the single quotes and re-add as double quotes
            inner = escaped[1:-1]
            # Unescape single quotes that repr escaped (since we're switching to double quotes)
            inner = inner.replace("\\'", "'")
            # Escape any double quotes
            inner = inner.replace('"', '\\"')
            return f'"{inner}"'

        # If repr already used double quotes (because the string contains single quotes), return as is
        return escaped

    def _format_default_value(self, value: Any) -> str:
        """Format default value for Python code, ensuring strings use double quotes."""
        if isinstance(value, str):
            return self._escape_string_for_python(value)
        # `repr()` module-qualifies temporal values ("datetime.datetime(...)"/"datetime.date(...)"),
        # but the generated code imports the bare classes ("from datetime import date/datetime"), so
        # the qualified form raises AttributeError at eval. Rebuild via fromisoformat() — a lossless,
        # offset-preserving round-trip that uses those imported bare names. (datetime is a date subclass.)
        if isinstance(value, datetime):
            return f'datetime.fromisoformat("{value.isoformat()}")'
        if isinstance(value, date):
            return f'date.fromisoformat("{value.isoformat()}")'
        if isinstance(value, time):
            return f'time.fromisoformat("{value.isoformat()}")'
        if isinstance(value, list):
            value_list = cast("list[Any]", value)
            formatted_items = [self._format_default_value(item) for item in value_list]
            return f"[{', '.join(formatted_items)}]"
        if isinstance(value, tuple):
            value_tuple = cast("tuple[Any, ...]", value)
            formatted_items = [self._format_default_value(item) for item in value_tuple]
            trailing_comma = "," if len(formatted_items) == 1 else ""
            return f"({', '.join(formatted_items)}{trailing_comma})"
        if isinstance(value, dict):
            value_dict = cast("dict[Any, Any]", value)
            formatted_items = [
                f"{self._format_default_value(dict_key)}: {self._format_default_value(dict_value)}" for dict_key, dict_value in value_dict.items()
            ]
            return f"{{{', '.join(formatted_items)}}}"
        return repr(value)

    def _format_class_docstring(self, docstring: str, *, indent: str = "    ") -> str:
        """Render a class docstring, wrapping it across multiple lines when the single-line
        form would exceed _MAX_LINE_LENGTH.
        """
        single_line = f'{indent}"""{docstring}"""'
        if len(single_line) <= _MAX_LINE_LENGTH:
            return single_line
        # Wrap the docstring text. The first wrapped line follows """, subsequent lines are
        # plain indented text, and the closing """ sits on its own line.
        wrap_width = _WRAP_WIDTH
        wrapped_lines = textwrap.wrap(docstring, width=wrap_width, break_long_words=False, break_on_hyphens=False)
        if not wrapped_lines:
            return single_line
        body = "\n".join(f"{indent}{line}" for line in wrapped_lines)
        return f'{indent}"""\n{body}\n{indent}"""'

    def _format_field_description(self, description: str) -> str:
        """Render the `description=` argument for a Field call. For short values, emit a
        single-line `description="..."`. For long values, emit a parenthesized
        implicit-string-concatenation block so each emitted line stays under the line limit.
        """
        escaped = self._escape_string_for_python(description)
        if len(escaped) <= _WRAP_WIDTH:
            return f"description={escaped}"
        chunks = textwrap.wrap(description, width=_WRAP_WIDTH, break_long_words=False, break_on_hyphens=False)
        if len(chunks) <= 1:
            return f"description={escaped}"
        # Join trailing space on each chunk except the last so the concatenation reads
        # naturally; textwrap dropped the original spaces.
        # Indent chunk literals (and the closing paren) so `ruff format` preserves the
        # implicit-string-concat — un-indented chunks get collapsed back to a single line.
        chunk_literals: list[str] = []
        for index, chunk in enumerate(chunks):
            content = chunk if index == len(chunks) - 1 else f"{chunk} "
            chunk_literals.append(f"        {self._escape_string_for_python(content)}")
        body = "\n".join(chunk_literals)
        return f"description=(\n{body}\n    )"

    def _generate_class_source_code_from_blueprint(
        self,
        *,
        class_name: str,
        structure_blueprint: dict[str, ConceptStructureBlueprint],
        base_class_name: str | None = None,
        description: str = "",
    ) -> str:
        """Generate a class definition from ConceptStructureBlueprint.

        Args:
            class_name: Name of the class
            structure_blueprint: Dictionary mapping field names to their ConceptStructureBlueprint definitions
            base_class_name: Optional base class name to inherit from (defaults to StructuredContent)
            description: Description for the class docstring (uses class_name if empty)

        Returns:
            Generated class code with markers for regeneration

        """
        # Determine base class
        base_class = base_class_name or "StructuredContent"

        # Add import for the base class if it's a native content class (other than StructuredContent which is already imported)
        if NativeConceptCode.is_native_structure_class(base_class):
            cls = NativeConceptCode.get_native_structure_class(base_class)
            if not cls:
                msg = f"Native structure class '{base_class}' not found"
                raise ConceptStructureGeneratorError(msg)
            self.imports.add(f"from {cls.__module__} import {cls.__name__}")
        elif base_class != "StructuredContent":
            # Cross-package refines: base class lives in another already-installed package — recover its module via the class registry.
            registered_cls = _get_class_registry().get_class(name=base_class)
            if registered_cls is not None and registered_cls.__name__ == base_class and registered_cls.__module__ not in {"__main__", "builtins"}:
                self.imports.add(f"from {registered_cls.__module__} import {base_class}")

        # Generate class header with docstring (use class name if no description provided)
        docstring = description or f"Generated {class_name} class"
        class_header = f"class {class_name}({base_class}):\n{self._format_class_docstring(docstring)}\n"

        # Generate fields through the neutral resolved-field layer shared by every emitter.
        resolved_fields = resolve_structure_fields(structure_blueprint, local_domain=self.local_domain)
        field_definitions = [self._generate_field_line(resolved_field) for resolved_field in resolved_fields]

        if not field_definitions:
            # Empty class - docstring is sufficient, no need for pass
            return class_header

        fields_code = "\n".join(field_definitions)
        return class_header + "\n" + fields_code

    def _generate_field_line(self, resolved_field: ResolvedField) -> str:
        """Render one Python field definition from a neutral resolved field."""
        python_type = self._python_type_from_resolved(resolved_field.resolved_type)

        # Make optional if not required
        if not resolved_field.required:
            python_type = f"Optional[{python_type}]"

        # Generate Field parameters (default/... first, then description)
        field_params = [self._format_field_description(resolved_field.description)]
        default_value = resolved_field.default_value
        if resolved_field.required and default_value is None:
            field_params.insert(0, "...")
        elif default_value is not None:
            field_params.insert(0, f"default={self._format_default_value(default_value)}")
        else:
            field_params.insert(0, "default=None")

        field_call = f"Field({', '.join(field_params)})"
        return f"    {resolved_field.name}: {python_type} = {field_call}"

    def _python_type_from_resolved(self, resolved_type: ResolvedType) -> str:
        """Map a neutral resolved type to a Python type annotation, accumulating the imports it needs."""
        match resolved_type.kind:
            case ResolvedTypeKind.TEXT:
                return "str"
            case ResolvedTypeKind.NUMBER:
                return "float"
            case ResolvedTypeKind.INTEGER:
                return "int"
            case ResolvedTypeKind.BOOLEAN:
                return "bool"
            case ResolvedTypeKind.DATE:
                self.imports.add("from datetime import date")
                return "date"
            case ResolvedTypeKind.DATETIME:
                self.imports.add("from datetime import datetime")
                return "datetime"
            case ResolvedTypeKind.TIME:
                self.imports.add("from datetime import time")
                return "time"
            case ResolvedTypeKind.LITERAL:
                choices = resolved_type.choices or []
                return f"Literal[{', '.join(repr(choice) for choice in choices)}]"
            case ResolvedTypeKind.CONCEPT:
                return self._python_type_for_concept(resolved_type)
            case ResolvedTypeKind.LIST:
                item_type = self._python_type_from_resolved(resolved_type.item) if resolved_type.item else "Any"
                return f"List[{item_type}]"
            case ResolvedTypeKind.DICT:
                key_type = self._python_type_from_resolved(resolved_type.key) if resolved_type.key else "str"
                value_type = self._python_type_from_resolved(resolved_type.value) if resolved_type.value else "Any"
                return f"Dict[{key_type}, {value_type}]"
            case ResolvedTypeKind.ANY:
                return "Any"

    def _python_type_for_concept(self, resolved_type: ResolvedType) -> str:
        """Resolve a CONCEPT node to a Python type annotation.

        The concept ref is already normalized by the resolved-field layer (natives flagged, bare
        refs promoted to the local domain). Emits:
        - for native concepts: an import of the native content class and its class name;
        - otherwise: a domain-qualified forward reference (resolved via model_rebuild at runtime).
        """
        concept_ref = resolved_type.concept_ref
        if not concept_ref:
            return "Any"

        if resolved_type.is_native:
            native_concept_code = extract_concept_code_from_concept_ref_or_code(concept_ref)
            try:
                native_code = NativeConceptCode(native_concept_code)
            except ValueError:
                native_code = None
            if native_code is not None:
                structure_class = native_code.structure_class
                if structure_class:
                    self.imports.add(f"from {structure_class.__module__} import {structure_class.__name__}")
                    return structure_class.__name__

        concept_code = extract_concept_code_from_concept_ref_or_code(concept_ref)
        parsed_ref = QualifiedRef.parse_stripping_cross_package(concept_ref)
        if parsed_ref.domain_path and not NativeConceptCode.is_native_concept_ref_or_code(concept_ref_or_code=concept_ref):
            qualified_name = make_qualified_structure_class_name(domain_code=parsed_ref.domain_path, concept_code=concept_code)
            return f'"{qualified_name}"'
        return f'"{concept_code}"'

    def _validate_execution(
        self,
        python_code: str,
        *,
        expected_class_name: str,
        base_class_name: str | None = None,
    ) -> type:
        """Validate that the code executes and creates the expected class."""
        # exec_globals with basic types but let native class imports execute naturally
        # This ensures we use the same class objects for inheritance checks
        exec_globals: dict[str, Any] = {
            "__builtins__": __builtins__,
            # Provide these directly as they're used in generated code but not imported from pipelex
            "date": date,
            "datetime": datetime,
            "time": time,
            "Enum": Enum,
            "Optional": Optional,
            "List": List,  # noqa: UP006
            "Dict": dict,
            "Any": Any,
            "Literal": Literal,
            "Field": Field,
        }

        # Add all native content classes to exec_globals so they're available during validation
        # This is needed because exec() with separate globals/locals puts imports in locals,
        # but class annotations look in globals
        for native_code in NativeConceptCode:
            structure_class = native_code.structure_class
            if structure_class:
                exec_globals[structure_class.__name__] = structure_class

        validation_code = python_code

        # If a custom base class is specified that's not a native class, get it from the registry
        if base_class_name:
            if not NativeConceptCode.is_native_structure_class(base_class_name):
                # Not a native class, provide it from registry
                custom_base_class = _get_class_registry().get_class(name=base_class_name)
                if custom_base_class is None:
                    msg = f"Base class '{base_class_name}' not found in native classes or class registry"
                    raise ConceptStructureValidationError(msg)
                exec_globals[base_class_name] = custom_base_class  # type: ignore[assignment]

        exec_locals: dict[str, Any] = {}
        exec(validation_code, exec_globals, exec_locals)

        # Verify the expected class was created
        if expected_class_name not in exec_locals:
            msg = f"Expected class '{expected_class_name}' not found in generated code"
            raise ConceptStructureValidationError(msg)

        the_class = exec_locals[expected_class_name]

        # Verify it's actually a class
        if not isinstance(the_class, type):
            msg = f"'{expected_class_name}' is not a class"
            raise ConceptStructureValidationError(msg)

        # Verify it inherits from the required base class
        # Check the MRO (Method Resolution Order) by class name to handle cases
        # where the class object references might differ due to exec() context
        mro_class_names = [cls.__name__ for cls in the_class.__mro__]

        if StuffContent.__name__ not in mro_class_names:
            msg = f"'{expected_class_name}' does not inherit from StuffContent. MRO: {mro_class_names}"
            raise ConceptStructureValidationError(msg)

        return the_class
