"""Agent CLI run pipe command - execute a pipeline by pipe code."""

from __future__ import annotations

import asyncio
import functools
from pathlib import Path
from typing import Annotated, Any

import typer

from pipelex.cli.agent_cli.commands.agent_cli_factory import make_pipelex_for_agent_cli
from pipelex.cli.agent_cli.commands.agent_output import (
    CliOutputFormat,
    agent_error,
    agent_success_formatted,
    run_failure_fields,
    set_agent_cli_error_format,
)
from pipelex.cli.agent_cli.commands.run._output_helpers import format_run_markdown
from pipelex.cli.agent_cli.commands.run._run_core import run_pipeline_core
from pipelex.cli.agent_cli.commands.run._run_hosted import (
    BASE_URL_OPTION_HELP,
    HOSTED_OPTION_HELP,
    RUNNER_OPTION_HELP,
    refuse_local_only_flags,
    resolve_agent_run_execution,
    run_hosted_for_agent,
)
from pipelex.cli.agent_cli.commands.run.stdin_resolver import parse_cli_inputs
from pipelex.cli.commands.run._hosted_sources import hosted_pipe_library_files
from pipelex.cli.method_resolver import resolve_pipe_from_exports
from pipelex.hosted.exceptions import HostedRunSourceError
from pipelex.hosted.hosted_run import HostedRunRequest
from pipelex.hosted.run_config import RunExecution  # ruff: ignore[typing-only-first-party-import] - typer reads the --runner annotation at runtime
from pipelex.mthds_parsing.helpers import MTHDS_EXTENSION, is_pipelex_file
from pipelex.pipe_operators.exceptions import PipeOperatorModelAvailabilityError
from pipelex.pipelex import Pipelex
from pipelex.pipeline.exceptions import PipelineExecutionError


def run_pipe_cmd(
    pipe_code: Annotated[
        str,
        typer.Argument(help="Pipe code to run"),
    ],
    inputs: Annotated[
        str | None,
        typer.Option("--inputs", "-i", help="Inputs: a JSON or TOML file (by its extension), or inline JSON starting with {"),
    ] = None,
    dry_run: Annotated[
        bool,
        typer.Option("--dry-run", help="Run pipeline in dry mode (no actual inference calls)"),
    ] = False,
    mock_inputs: Annotated[
        bool,
        typer.Option("--mock-inputs", help="Generate mock data for missing required inputs (requires --dry-run)"),
    ] = False,
    graph: Annotated[
        bool,
        typer.Option("--graph/--no-graph", help="Generate execution graph visualizations (saved alongside output)"),
    ] = True,
    costs: Annotated[
        bool,
        typer.Option("--costs/--no-costs", help="Emit usage (cost) tracing events. Default on."),
    ] = True,
    library_dir: Annotated[
        list[str] | None,
        typer.Option("--library-dir", "-L", help="Directory to search for pipe definitions (.mthds files)"),
    ] = None,
    with_memory: Annotated[
        bool,
        typer.Option("--with-memory", help="Include full working memory in output (for piping to another method)"),
    ] = False,
    output_format: Annotated[
        CliOutputFormat,
        typer.Option("--format", help="Success output format: markdown (default) or json (structured)"),
    ] = CliOutputFormat.MARKDOWN,
    error_format: Annotated[
        CliOutputFormat | None,
        typer.Option("--error-format", help="Error output format (defaults to --format value): markdown or json"),
    ] = None,
    runner: Annotated[
        RunExecution | None,
        typer.Option("--runner", help=RUNNER_OPTION_HELP),
    ] = None,
    hosted: Annotated[
        bool | None,
        typer.Option("--hosted/--local", help=HOSTED_OPTION_HELP),
    ] = None,
    base_url: Annotated[
        str | None,
        typer.Option("--base-url", help=BASE_URL_OPTION_HELP),
    ] = None,
) -> None:
    """Execute a pipeline by pipe code and output the results.

    Default output is markdown; use --format json for structured JSON.
    Results go to stdout on success, errors to stderr with exit code 1.
    Graph visualizations are generated by default; use --no-graph to disable.

    Examples:
        pipelex-agent run pipe my_pipe
        pipelex-agent run pipe my_pipe --inputs data.json
        pipelex-agent run pipe my_pipe --dry-run --mock-inputs
        pipelex-agent run pipe my_pipe --format json
        pipelex-agent run pipe my_pipe -L my_library/ --runner hosted --inputs data.json
    """
    set_agent_cli_error_format(error_format or output_format)

    # Helpful error if the user passes a path instead of a pipe code
    target_path = Path(pipe_code)
    if target_path.is_dir() or is_pipelex_file(target_path) or pipe_code.endswith(MTHDS_EXTENSION):
        agent_error(
            f"'{pipe_code}' looks like a file path or directory. "
            f"Use 'run bundle {pipe_code}' for bundles/directories, or 'run pipe <code>' for pipe codes.",
            error_type="ArgumentError",
        )

    # Validate --mock-inputs requires --dry-run
    if mock_inputs and not dry_run:
        agent_error("--mock-inputs requires --dry-run", error_type="ArgumentError")

    # Check installed methods' exports for additional library dirs
    try:
        export_dirs = resolve_pipe_from_exports(pipe_code)
    except ValueError as exc:
        agent_error(
            f"Ambiguous pipe code '{pipe_code}': {exc}",
            error_type="ArgumentError",
            cause=exc,
        )
    if export_dirs:
        if library_dir is None:
            library_dir = export_dirs
        else:
            library_dir = [*export_dirs, *library_dir]

    # Load inputs: --inputs flag takes priority, then stdin fallback
    parsed_inputs = parse_cli_inputs(inputs_arg=inputs, stdin_fallback=True)
    pipeline_inputs: dict[str, Any] | None = parsed_inputs.pipeline_inputs

    execution = resolve_agent_run_execution(runner=runner, hosted=hosted, base_url=base_url)
    if execution.is_hosted:
        refuse_local_only_flags(dry_run=dry_run, mock_inputs=mock_inputs)
        # The hosted API holds no library of yours: the one a local run would load is sent along.
        try:
            library_files = hosted_pipe_library_files(library_dirs=library_dir)
        except HostedRunSourceError as exc:
            agent_error(exc.message, error_type=type(exc).__name__, cause=exc)
        request = HostedRunRequest(
            mthds_files=library_files,
            pipe_code=pipe_code,
            inputs=pipeline_inputs,
            inputs_base_dir=parsed_inputs.inputs_base_dir,
        )
        run_hosted_for_agent(request=request, base_url=base_url, with_memory=with_memory, output_format=output_format)
        return

    make_pipelex_for_agent_cli(needs_inference=not dry_run)

    try:
        result = asyncio.run(
            run_pipeline_core(
                pipe_code=pipe_code,
                inputs=pipeline_inputs,
                dry_run=dry_run,
                mock_inputs=mock_inputs,
                library_dirs=library_dir,
                graph=graph,
                costs=costs,
                with_memory=with_memory,
                inputs_base_dir=parsed_inputs.inputs_base_dir,
            )
        )
        agent_success_formatted(
            result, markdown_renderer=functools.partial(format_run_markdown, with_memory=with_memory), output_format=output_format
        )

    except PipelineExecutionError as exc:
        agent_error(exc.message, error_type="PipelineExecutionError", cause=exc, **run_failure_fields(error=exc))

    except PipeOperatorModelAvailabilityError as exc:
        availability_extra: dict[str, Any] = {
            "pipe_code": exc.pipe_code,
            "model_handle": exc.model_handle,
        }
        if exc.fallback_list:
            availability_extra["fallback_list"] = exc.fallback_list
        if exc.pipe_stack:
            availability_extra["pipe_stack"] = exc.pipe_stack
        agent_error(exc.message, error_type="PipeOperatorModelAvailabilityError", cause=exc, **availability_extra)

    except Exception as exc:  # ruff: ignore[blind-except]
        # Agent CLI command boundary: agent_error() (NoReturn) converts any unexpected failure into the structured error payload.
        agent_error(str(exc), error_type=type(exc).__name__, cause=exc)

    finally:
        Pipelex.teardown_if_needed()
